### ISSUE TITLE
Support for transmission

### ISSUE THREAD

**Issue by lakulish** [ValveSoftware/steam-audio#10]
To allow sounds to be heard through solid objects (albeit muffled) even when reflection and diffraction paths do not exist, transmission of sound through solid objects should be modeled.

**Comment by AndersMalmgren** [comment]
Hi, 
Any roadmap or such for important features like these?

**Comment by achandak** [comment]
@AndersMalmgren - we have added support for transmission in Steam Audio 2.0-beta.5 release.

See release notes [here](http://steamcommunity.com/games/596420/announcements/detail/1263670339945800564).

**Comment by AndersMalmgren** [comment]
Perfect thanks! I think there also are alot of people waiting for this feature until they will be able to use Steam Audio in their projects

https://github.com/ValveSoftware/steam-audio/issues/9
