### ISSUE TITLE
[C API] libphonon has no Android support for devices with x86/x86_64 cpu?

### ISSUE THREAD

**Issue by NielsHygum** [ValveSoftware/steam-audio#100]
As I understand I cant make libphonon run on Android devices with x86 cpu as the linux version for libphonon for x86 is not compatible with the Android x86 toolchain?

Please compile libphonon for Android with x86 cpu. Should be easy...

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), includes support for x86 and x86_64 CPUs on Android.
