### ISSUE TITLE
[Unity] Audio makes a random loud pop and stops playing until restart

### ISSUE THREAD

**Issue by Frooxius** [ValveSoftware/steam-audio#101]
Hello,

I have recently switched my project from using the Oculus Spatializer to the Steam Audio. It works great for the most part, but I've encountered a severe issue.

Sometimes there's a random loud pop and all audio completely stops until the game is restarted. It seems to occur when there's several new audio sources spawned at once, but it's not reliable.

Sometimes spawning just a few triggers the pop, sometimes I can spawn dozens at once and it still works fine. I cannot unfortunately find any pattern in this. Is there anything that would help diagnose this issue?

There is however another thing I have noticed. With many (dozens) of active audio sources, adding new ones causes severe performance hitches. For attaching a single additional audio source takes 5 ms just to attach the Unity AudioSource and setting the "spatializePostEffects" property on it takes 30-40 ms. With OculusSpatializer this doesn't occur and adding a new one is fast.

**Comment by achandak** [comment]
Is there a scene or project you can share with us so we can reproduce the issue? Also, what version of Unity and Steam Audio are you using?

**Comment by Frooxius** [comment]
Sorry, I haven't managed to find a way to reproduce this, it seems to happen randomly over the course of running my app. It seems it's more likely to occur when there's multiple sound effects created at the same time, but only sometimes.

I was using Unity 2019.2.x (happened on multiple subversions) and the latest 2.0-beta.17. I have also 
tried 2.0-beta.16 which had the same issue.

I believe that this issue is likely the same as the one reported here with the DSP usage spike, since in my case it would occur when instantiating many sound effects at the same time: https://github.com/ValveSoftware/steam-audio/issues/104

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue. Feel free to reopen if the issue persists on your end.

**Comment by yuma1217** [comment]
This issue remain with Steam Audio 2.0-beta20.
