### ISSUE TITLE
The state of Steam Audio 

### ISSUE THREAD

**Issue by AndersMalmgren** [ValveSoftware/steam-audio#102]
Hi, I revisited steam audio today, about 2 years later. It seems oclussion is still too agressive (No diffraction #9)  and it also cuts of audio in wierd ways when moving through door ways and similar. What's the general state of the software? It seems it was a long time since project members were active here in the issue section?

Here I showcase some of my problems, steam audio 2 beta 17

https://youtu.be/77pR0z87-T4

**Comment by Schroedingers-Cat** [comment]
Not a solution to your problem, but there is an alternative to steam audio whose devs are more responsive via email than the steam audio devs (if they still exist at all): https://docs.microsoft.com/en-us/azure/cognitive-services/acoustics/what-is-acoustics

**Comment by AndersMalmgren** [comment]
Thanks @Schroedingers-Cat funny I have Googled for diffraction solutions and this didn't surface. Will have a look. Have tested oculus and Google resonance, both have oclussion but no diffraction

**Comment by lakulish** [comment]
@AndersMalmgren To help us better identify the issues you're encountering, could you point us to specific time points in the video you linked, and describe what behavior you would expect vs what behavior you're observing?

That said, it looks like the main issue you're facing is that indirect (reflected) sound is suddenly dropping out near doorways. What are your simulation settings? Can you try increasing a) number of rays, or b) number of bounces?

Have you tried using baked indirect simulation instead of real-time? Or is baking not an option for your application?

**Comment by AndersMalmgren** [comment]
Hi @lakulish 

Here are some time codes were you can see too aggressive cut offs

https://youtu.be/77pR0z87-T4?t=99
https://youtu.be/77pR0z87-T4?t=126

Throwing a grenade around a corner and its almost completely silent.

**Comment by lakulish** [comment]
@AndersMalmgren Thanks for providing this. The first case seems to be a mix of direct-path occlusion cutting off too sharply, and not enough indirect sound reaching the listener; the second case seems to me to be mostly the latter (not enough indirect sound). Does increasing the number of bounces help? What about baking?

As for the grenades, I noticed that they all sound much quieter than I would have expected. Is the emitter for the grenade placed exactly on the floor where the grenade lands? If so, it might be incorrectly self-occluding, and we can look into a repro for this separately.

**Comment by AndersMalmgren** [comment]
@lakulish I have tried increasing bounces. It does lower cut off, but it also increases sound artifacts and reverb. I havent tried bakign since we have both  moving listener and sources which baking does not suppport.

The center of the audiosource is the center of the grenade. So its close to the floor

![image](https://user-images.githubusercontent.com/817577/64997265-79d84000-d8e0-11e9-94a0-5bb804c3a838.png)

**Comment by adamdelong** [comment]
Adam

**Comment by lakulish** [comment]
@AndersMalmgren I'm closing this issue out; let us know if you continue to face this issue in the latest release of Steam Audio, and we'll reopen it.

**Comment by AndersMalmgren** [comment]
@Schroedingers-Cat I want to thank you for pointing us to Project Acoustics. We ended up moving to their solution, 

https://www.youtube.com/watch?v=SVAPrjuizLc
