### ISSUE TITLE
Unity: SteamAudio output level is 4dB lower

### ISSUE THREAD

**Issue by Schroedingers-Cat** [ValveSoftware/steam-audio#103]
When SteamAudio is used to spatialize an AudioSource, the volume of the audio is being reduced by roughly 4dB. The issue occurs across multiple Unity versions (2018, 2019) with Steam Audio 2.0 beta 17.

Steps to reproduce:
1. Load a test signal (for instance white noise) as AudioClip into an AudioSource with PlayOnAwake=true
2. Position the camera at the same spot as the AudioSource so the 3D Audio Engine has no effect on the AudioSource.
3. Add a SteamAudioSource Component to the AudioSource and disable `Direct Binaural`
4. Start the scene and toggle the Spatialize-bool. Using an RMS meter, I get a difference of 4dB between Spatialize-On and Off.
5. Enable `Direct Binaural` in the SteamAudioSource Component.
6. Toggle the Spatialize-bool. The volume difference is now much much less.

So the issue occurs on step 4. Step 5 and 6 are merely there to demonstrate this has something to do with the audio rendering when HRTFs are disabled.

For reference, I'm posting the settings I used: 
![grafik](https://user-images.githubusercontent.com/6382400/65595824-1657ad80-df85-11e9-8a4c-b1f53790eb9a.png)

**Comment by Schroedingers-Cat** [comment]
It seems that this effect depends on the current speaker configuration. If that is set to `stereo`, you'll end up with a 4dB difference in volume.
If using a speaker layout of 7.1, the difference will be more dramatic and Steam Audio's output will be roughly 15dB(!) less thatn a non-spatialized version of the AudioSource.  

@freemancw @lakulish @achandak this behaviour is possibly caused by this:  https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/spatialize_effect.cpp#L789-L799
It's not obvious why the `level` parameter from the SteamAudioSource-Component just isn't a simple constant factor but needs to be calculated from things like `outChannels` or `numSamples`. Anyway, given the fact that the volume differences become stronger with more channels used by the speaker layout, it looks like that is coming from these lines.

**Comment by Schroedingers-Cat** [comment]
I had some more time today to look into this. Seems like the part I quoted above does the volume adjustment over time to avoid hard volume jumps? 
Got the source code to compile on my machine and put some std::cout in there to check the `level` value, but that stays at 1 in these lines. 
So the issue is coming from somewhere else.

I created a video showcasing the minimal setup involved and the observations: https://klops.filmuniversitaet.de/index.php/s/vZbzoP7lAr1sWNg

Also I added some speaker layout dependent constants into the lines above which fixes the problem. I'll try to make a PR later this month.

**Comment by Schroedingers-Cat** [comment]
I believe this is still true.

My guess is that the root problem occurs from down mixing the input channels which forces some level changes to prevent clipping?

**Comment by lakulish** [comment]
@Schroedingers-Cat The panning algorithm in Steam Audio uses constant power panning, whereas the HRTF is normalized using a more complex frequency-dependent algorithm that accounts for perceptual loudness. For this reason, it's possible that there is some loudness discrepancy between HRTF and panning, and that this difference may vary as a function of direction.

One way to deal with this might be to use the **HRTF Volume Gain** setting in the Steam Audio Settings to bring the binaural audio to a similar level as panned audio.

**Comment by Schroedingers-Cat** [comment]
Thanks a lot for adding the HRTF Volume Gain setting. I had to hard-bake the offset into the plugin for my projects. The new setting allows me to use the release binaries again.
