### ISSUE TITLE
[Unity] Switching scenes causes massive dsp cpu usage spike and silences all audio with no error message

### ISSUE THREAD

**Issue by wils1387** [ValveSoftware/steam-audio#104]
Every time I switch scenes, with each scene having a steam audio manger with everything pre exported, there is a loud pop and then silence in the audio, with no error message. Everything works as intended if I navigate to a scene in the Unity editor hierarchy and press play, but then switching to a new scene from that scene causes the spike and all the audio to stop working. Any help would be greatly appreciated.

**Comment by achandak** [comment]
Is there a scene or project that you can share with us so we can reproduce the issue? Also, what version of Unity and Steam Audio are you using?

**Comment by wils1387** [comment]
I don't know about sharing a scene as it is not a personal project my apologies. I am on Unity 2019.1.2f1 and using beta 2.0-beta. 17 for Steam Audio. Also just to check again I don't see anything about switching scenes in the documentation, but do I have this set up properly? Steam Audio is enabled in the Unity project settings, and then every scene in the game has a steam audio settings window that is pre exported, with the corresponding phonon file in streaming assets. There are objects with an audio source and steam audio source at attached that emit sound, there is a steam audio geometry and material script on the walls of a room. Everything works as intended when playing from the scene, but then switching between scenes in play mode the audio "pops" and spikes dsp usage, causing all sound to fail to play. And again no errors when this happens.
