### ISSUE TITLE
[Unity]: Magic Leap (AArch64) support? 

### ISSUE THREAD

**Issue by chmontagne** [ValveSoftware/steam-audio#105]
We're trying to port an app that uses Steam Audio from Windows/Unity to Magic Leap, which uses the ARMV8 AArch64 architecture. When we built the app to the Magic Leap sounds would play, but would not be spatialized. What happens is an exception for System.EntryPointNotFoundException is thrown when trying to access the Phonon's binaural renderer related methods. At this point we realized libphonon.so needed to be compiled for AArch64. 

Ultimately, we're wondering if there are plans to compile the Phonon library for MagicLeap/AArch64 support?

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), includes support for arm64 CPUs on Android.
