### ISSUE TITLE
MacOS Mojave doesnt allow steam to use microphone.

### ISSUE THREAD

**Issue by dddavo** [ValveSoftware/steam-audio#106]
When i try to use microphone on steam into the settings, isnt working. I tried to go into security and privacy>privacy>microphone and i have only discord and telegram cause the app asked me to use microphone, but steam didnt. I did something on the terminal with the reset of permissions, but nothing, steam doesnt show up. Is there a way to add steam manually on privacy and setting into microphone, or a fix?

**Comment by kisak-valve** [comment]
Hello @dddavo, [this project](https://valvesoftware.github.io/steam-audio/) is an audio sub-component for 3d game engines like Unity and Unreal, not the steam client. Please use [Steam Support](https://help.steampowered.com/en/) to report issues with the Steam on Mac client.
