### ISSUE TITLE
[Unity] Indirect sound doesn't work properly on scaled audio listener

### ISSUE THREAD

**Issue by Nehluxhes** [ValveSoftware/steam-audio#109]
Just want to report a small bug I was stuck on for quite some time...

I was using an audio listener attached to a gameobject with a scaled transform, because I am prototyping and I was using a basic cylinder mesh as the player, and it turns out doing so make indirect sound not working at all.
There is no reverberation and weirdly in some positions you can hear the sound like if you were just next to it, even if there are walls between you and the audiosource.

With an unscaled transform (1,1,1) everything works properly though!

**Comment by SanielX** [comment]
Also it needs to be scaled (1;1;1) especially in global space.
When I set (1;1;1) in local scale wrong behaviour appears

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue. Feel free to reopen if the issue persists on your end.
