### ISSUE TITLE
[Unreal][Feature Request]Add a field to specify an LOD to use for creating the phononscene

### ISSUE THREAD

**Issue by DavidWLejeune** [ValveSoftware/steam-audio#111]
In really complex worlds the phononscene file size can get extremely large, which effects load times and potentially performance for real-time reverb.

This can be worked around a bit by just creating a hidden lower-poly scene and putting the phononcomponents on that, but that's not very efficient. 

It would be nice if on the PhononGeometry component we could specify LODs from which the phononscene will be generated. This would allow the creation of more optimized phononscenes without dramatically affecting the acoustics of the environment.

**Comment by 1runeberg** [comment]
Thanks for the feedback @DavidWLejeune !

We're also looking at supporting sublevels which in some cases may help in audio design, potentially not with dynamic geometry.

this request seems reasonable, will have a look for the next release and put an update here.

@kisak-valve - can i be set as the assignee to this issue please. thanks! :)

**Comment by funkysandwich** [comment]
I second this. I'm using high-poly modular assets, so simply using 'Add Geometry component to all actors' results in very large file sizes and long export/load times.

It'd be nice to set a min LOD level for static mesh geometry exports under World Settings.
Also, a property on the geometry component to specify a proxy static mesh asset would be great too, to use that mesh instead during the baking/export process.
