### ISSUE TITLE
[Unity] First Order Ambisonics not rendering correctly + volume issue when scaling GameObject

### ISSUE THREAD

**Issue by errorjones** [ValveSoftware/steam-audio#112]
## Channel Order Issue:
First order ambisonics files are not rendering correctly for binaural playback in Unity 2019.2.19f1 using Windows 10 64 bit. It seems like the channels get mixed up (right and left are definitely reversed, if something else is going on). The files I tested are in the standard Ambix/ACN/SN3D format (4 channels).

When using either the FB360, ResonanceAudio or Oculus spatializers, the same files are rendered correctly.

Unfortunately, there is no info in the documentation concerning steam audio's preferred ambisonics channel format, so I guessed it's Ambix/ACN.

## How to reproduce:
- create an empty scene with a plane and a simple first person controller to look around
- import the steam audio unity package (2.0-beta.17) and set everything up as described in the documentation
- create an audiosource at the same coordinates as the audio listener in the scene, select an ambisonics audio clip, turn off the "Spatialize" option and turn on "Play On Awake". Make sure the option "Ambisonic" is turned on in the audio clip's settings.

## Volume Issue:
If you double the scale of the GameObject containing the audio source, the volume will get twice as loud! If your AudioSource has a scale of 100,100,100, then say goodbye to your ears... Strangely, not all directions within the ambisonic soundfield are equally affected by the increase in volume while looking forward. For example, sounds coming from the front center and rear center don't get much louder at all, while everything coming from the sides gets boosted.

**Comment by errorjones** [comment]
## Update:
I flipped the phase of the second channel in my test file (the X-channel) and now the file is rendering correctly. So steam audio seems to require the following ambisonics format: W -X Y Z. This seems strange to me.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue. Feel free to reopen if the issue persists on your end.
