### ISSUE TITLE
Steam Audio + Fmod + Unreal

### ISSUE THREAD

**Issue by duplexsystem** [ValveSoftware/steam-audio#113]
Are there plans to make a Unreal Fmod Steam Audio plugin?

**Comment by Qianfulong** [comment]
Still no answer on this very simple question?

**Comment by RaphpowerUE4** [comment]
That would be very nice, I have tried but it doesn't work, and it's so sad actually. Only works for Unity, you have to use the UE4 plugin without FMOD, please Valve, update this

**Comment by ptrefall** [comment]
Bump

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

This version includes support for using FMOD Studio along with Unreal Engine.
