### ISSUE TITLE
[UE4] no static meshes crashes using embree

### ISSUE THREAD

**Issue by andyfedak** [ValveSoftware/steam-audio#122]
Hi there - more of a minor bug, but I thought I'd post it for you.  

If you have a scene with all dynamic objects (no static ones), this seems to crash phonon if you are using embree.  

This took me a few days to figure out, so I thought I'd at least share it here for posterity;-)
-a

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if you continue to face this issue in the new version.
