### ISSUE TITLE
UE4 - 4.25 throws exception - phonon.pdb not loaded

### ISSUE THREAD

**Issue by avivazran** [ValveSoftware/steam-audio#124]
Exception thrown at 0x00007FFECEB9B60E (phonon.dll) in UE4Editor.exe: 0xC0000005: Access violation reading location 0x0000001000000019. occurred

Symbol load information
C:\Program Files\Epic Games\UE_4.25\Engine\Binaries\Win64\phonon.pdb: Cannot find or open the PDB file.
C:\Program Files\Epic Games\UE_4.25\Engine\Binaries\ThirdParty\Phonon\Win64\phonon.pdb: Cannot find or open the PDB file.
D:\perforce\phonon\rel_2.0-beta.17\core\bin\windows-vs2015-x64-release\phonon.pdb: Cannot find or open the PDB file.
C:\Windows\phonon.pdb: Cannot find or open the PDB file.
C:\Windows\symbols\dll\phonon.pdb: Cannot find or open the PDB file.
C:\Windows\dll\phonon.pdb: Cannot find or open the PDB file.
C:\Users\Aviv\AppData\Local\Temp\SymbolCache\phonon.pdb\5b65719903954abbb8b0241a67b591092\phonon.pdb: Cannot find or open the PDB file.
C:\Users\Aviv\AppData\Local\Temp\SymbolCache\MicrosoftPublicSymbols\phonon.pdb\5b65719903954abbb8b0241a67b591092\phonon.pdb: Cannot find or open the PDB file.

**Comment by lakulish** [comment]
Can you provide more details on what you were doing when the crash occurred? If there are specific steps that we can take to try to reproduce the crash, or a minimal test scene you can provide that reproduces the crash, that would be useful.

**Comment by avivazran** [comment]
I actually just following your guide for unreal engine.
I'm trying to use the real-time propagation.
I've installed Intel Embree and followed the steps in your guide step by step.

the exception happens every time I press the play in editor button

**Comment by 1runeberg** [comment]
Hi Aviv - Can you share the project log and/or a test project?

Also, we've released new binaries for 4.25.2/3, if you're using a custom engine build, you may need to run Setup again to download these binaries as we've statically linked embree in them.

**Comment by avivazran** [comment]
I’m using the official 4.25.3 release and the plugin version available is beta 17 only. 
And I really need some of the features of beta 18. 
As for the issue with phonon.pdb, it seems that it happens when there isn’t any static phonon geometry component in the scene. Maybe it’s already fixed in beta 18

**Comment by 1runeberg** [comment]
Hi @avivazran - Thanks for the feedback. The current unreal plugin that's integrated in UE is version 2.0 release and is used in some released titles, therefore we would want to investigate closely what's causing the crash on your use case as it could be a regression we haven't anticipated when we statically linked embree in 4.25.2

Is there any issues providing us with a minimum repro project and/or the full UE4 log to help us assess your issue properly?

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if you continue to face this issue in the new version.
