### ISSUE TITLE
Phonon material coefficients and creating custom materials

### ISSUE THREAD

**Issue by avivazran** [ValveSoftware/steam-audio#126]
Where can I find information about the coefficints used for phonon material settings?
![image](https://user-images.githubusercontent.com/39994570/89772407-9e499600-db0a-11ea-8179-4746dc84d904.png)

Specifically:

1. What are the units of the coefficients?
2. What are the frequency ranges of "Low"/'Mid"/"High/ frequencies?
3. How does those coefficients are used to define an acoustic material? (for understanding how to simulate other materials not provided with the plugin.)
4. Can I simulate non-solid materials with Phonon material? water for example? if I can, how is it done?

Thanks!

**Comment by lakulish** [comment]
More details are available in the docs for the Unity plugin: https://valvesoftware.github.io/steam-audio/doc/unity/material.html. Unreal plugin works the same way.

The coefficients are fractions, so setting low frequency absorption to 10% means that 10% of low-frequency sound is absorbed (i.e., 90% of low-frequency sound is reflected).

As for frequency ranges: low is 0-800Hz, mid is 800Hz-8kHz, and high is above 8kHz.

Steam Audio doesn't simulate the physics of non-solid materials, but depending on your application, you may be able to approximate the effects using absorption and transmission coefficients. More likely you will want to configure "underwater" filters manually, though.

Hope this helps!
