### ISSUE TITLE
Assertion failed with Unity 2020.1

### ISSUE THREAD

**Issue by ArgentumPhoenix** [ValveSoftware/steam-audio#130]
Unity 2020.1.6F1, Steam Audio 2.0 b 18, Win 10 64bit.
This error occurs when the scene is launched for the first time after opening the Unity editor. At runtime, the input system stops working. The same thing happens if run application after build.
This error happens only when SteamAudioManager presents in the scene.
``Assertion` failed
UnityEngine.DebugLogHandler:Internal_Log(LogType, LogOption, String, Object)
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Assert(Boolean)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:DepthFirstOnClippingChanged(RenderChain, VisualElement, VisualElement, UInt32, Boolean, Boolean, Boolean, Boolean, Boolean, UIRenderDevice, ChainBuilderStats&)
UnityEngine.UIElements.UIR.Implementation.RenderEvents:ProcessOnClippingChanged(RenderChain, VisualElement, UInt32, ChainBuilderStats&)
UnityEngine.UIElements.UIR.RenderChain:ProcessChanges()
UnityEngine.UIElements.UIRRepaintUpdater:Update()
UnityEngine.UIElements.VisualTreeUpdater:UpdateVisualTreePhase(VisualTreeUpdatePhase)
UnityEngine.UIElements.Panel:UpdateForRepaint()
UnityEngine.UIElements.Panel:Repaint(Event)
UnityEngine.UIElements.UIElementsUtility:DoDispatch(BaseVisualElementPanel)
UnityEngine.UIElements.UIElementsUtility:UnityEngine.UIElements.IUIElementsUtility.ProcessEvent(Int32, IntPtr, Boolean&)
UnityEngine.UIElements.UIEventRegistration:ProcessEvent(Int32, IntPtr)
UnityEngine.UIElements.<>c:<.cctor>b__1_2(Int32, IntPtr)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
 
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 35)``

Link to test project: [](url)https://drive.google.com/file/d/1fA3eQHaL8G0P6B1TpUvVHfa2POhD0Z40/view?usp=sharing[/url]

**Comment by Milk-Drinker01** [comment]
I have the same issue. are you on HDRP? i am on HDRP 8.2.0

**Comment by ArgentumPhoenix** [comment]
> 
> 
> I have the same issue. are you on HDRP? i am on HDRP 8.2.0

No. Standard 3D.

**Comment by ArgentumPhoenix** [comment]
The same problem on  Unity 2020.1.7F1 and Unity 2019.4.11F1 LTS. On Unity 2017.4.40F1 LTS all works fine.

**Comment by lakulish** [comment]
This seems to be related to a change in Steam Audio 2.0-beta.18 that changes the CPU's handling of floating-point denormals when iplCreateContext is called. See #128 and the linked forum issue (https://steamcommunity.com/app/596420/discussions/0/2948124408722607237/) for more information. The workaround mentioned in the forum post (2nd reply) describes a change they made to a GameEngineState.cs in the Unity plugin that lets them work around the issue.

Specifically, they run iplCreateContext in a separate thread, so that the denormals stuff only affects code running on that separate thread, but since that thread only runs the iplCreateContext and immediately exits, the denormals stuff doesn't affect anything.

Try this workaround and let us know if the issue persists.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.19](https://github.com/ValveSoftware/steam-audio/releases/), includes a fix for this issue.
