### ISSUE TITLE
OBJ geometry loaded from Unity's Asset Bundle?

### ISSUE THREAD

**Issue by Sorgon** [ValveSoftware/steam-audio#131]
I exported my scene geometry as .obj, and built it as an asset bundle.

I started the game, and from my script I loaded the asset:
`bundle.LoadAsset<UnityEngine.Object>(downloadTicket.File);`

Then I loaded the actual scene, but it seems Steam Audio did not recognize that this obj would be loaded. It was trying to find .phononscene geometry instead.

Is there something I am missing here?

**Comment by lakulish** [comment]
The .obj export functionality is only there for testing/debugging purposes, so you can open the .obj file in a 3D model viewer and make sure Steam Audio is using the correct geometry. For Steam Audio to actually load and use a scene at runtime, you will have to do the normal export (to .phononscene).

**Comment by Sorgon** [comment]
I see. Thank you and sorry for my ignorance.
