### ISSUE TITLE
Type.GetType("FMOD.DSP" + assemblySuffix) does not work

### ISSUE THREAD

**Issue by b-pos465** [ValveSoftware/steam-audio#132]
**Using:**

- Unity version: 2020.1.10f1
- FMOD version: 2.01.05
- SteamAudio 2.0.18

When using Unity + FMOD + Steam Audio the following exception occurs on start:

```
NullReferenceException: Object reference not set to an instance of an object
SteamAudio.FMODAudioEngineSource.BindToFMODStudioPlugin () (at Assets/SteamAudio/AudioEngineSource_FMODStudio.cs:38)
SteamAudio.FMODAudioEngineSource.FindDSP (UnityEngine.GameObject gameObject) (at Assets/SteamAudio/AudioEngineSource_FMODStudio.cs:66)
SteamAudio.FMODAudioEngineSource.Initialize (UnityEngine.GameObject gameObject) (at Assets/SteamAudio/AudioEngineSource_FMODStudio.cs:26)
SteamAudio.SteamAudioSource.Awake () (at Assets/SteamAudio/SteamAudioSource.cs:43)

```

Replacing it in `FMODAudioEngineSource` with the following code fixes the issue:

```
FMOD_DSP = Assembly.Load("FMODUnity").GetType("FMOD.DSP");
FMOD_ChannelGroup = Assembly.Load("FMODUnity").GetType("FMOD.ChannelGroup");
FMOD_Studio_EventInstance = Assembly.Load("FMODUnity").GetType("FMOD.Studio.EventInstance");
FMODUnity_StudioEventEmitter = Assembly.Load("FMODUnity").GetType("FMODUnity.StudioEventEmitter");
```

I got the solution from [this](https://answers.unity.com/questions/206665/typegettypestring-does-not-work-in-unity.html).

**Comment by TobiasNienhaus** [comment]
I've got the same error, using Steam Audio 2.0.19, FMOD 2.01.05 and Unity 2019.4.14f.

The same solution worked for me (so thank you very much😄).

**Comment by lakulish** [comment]
We are able to repro this issue. It occurs because the FMOD Studio assembly name has changed between FMOD Studio 1.x and 2.x. Previously, it was "Assembly_CSharp-firstpass", now it's "FMODUnity". We have implemented a fix for this, and it will be available in an upcoming release.

**Comment by lakulish** [comment]
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
