### ISSUE TITLE
Steam Audio + FMOD + Unity freezes on Mac OSX 10.13.6

### ISSUE THREAD

**Issue by b-pos465** [ValveSoftware/steam-audio#133]
**Using:**

- Unity version: 2020.1.10f1
- FMOD version: 2.01.05
- SteamAudio 2.0.18
- OSX 10.13.6

The scene contains an FMOD studio event emitter and a Steam audio source. The scene works on Windows but freezes on Mac OSX 10.13.6.

**Expected behaviour:**

The scene execution does not freeze.

**Comment by lakulish** [comment]
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
