### ISSUE TITLE
unity reflections not working on 2020.1 HDRP

### ISSUE THREAD

**Issue by Milk-Drinker01** [ValveSoftware/steam-audio#134]
I am on unity 2020.1 using HDRP. At first, I thought reflections were only working when looking straight up or down. Now, i realized that the realtime reflections ARE working when looking forward, but only for the first few seconds after the game is started. after that they only work when looking straight up and down.

I think the issue is related to either HDRP or the scriptable render pipeline in general, because reflections work as expected in a new project using the old rendering pipeline.

**Comment by Milk-Drinker01** [comment]
Edit: in the old render pipeline, my reflections only work when looking straight forward

**Comment by achandak** [comment]
Hey @Milk-Drinker01 - Thanks for reporting the issue. Is there a minimal standalone project you are able to share? We are going to try to repro the issue on our end meanwhile.

**Comment by Milk-Drinker01** [comment]
Thanks for the quick reply @achandak - i have uploaded my Assets folder and my packages folder to the link below. The scene I am testing in just the sample scene. the audio source is the sphere infront of the player. when creating a project, be sure to be on unity 2020.1 with the HDRP template selected. during runtime, if you hold left click, a gunshot will play from the audio source. 
https://drive.google.com/file/d/1d7LzqO8oVIOwerYjPDWu0hHBCcMS6YmI/view?usp=sharing

**Comment by Milk-Drinker01** [comment]
oh also a side note, you cannot "export all dynamic objects" in HDRP

**Comment by achandak** [comment]
Hi @Milk-Drinker01 -

- We fixed a bug with exporting dynamic objects. You can download, unzip, and copy [SteamAudioManagerInspector.zip](https://github.com/ValveSoftware/steam-audio/files/5525921/SteamAudioManagerInspector.zip) in Assets\SteamAudio\Editor

- For the issue with orientation and reflections not sounding right, you want to make sure that the scale for Audio Listener is Uniform. See the release notes from our [latest release](https://github.com/ValveSoftware/steam-audio/releases/tag/v2.0-beta.18) and specifically the following note: 

_Fixed bug where indirect sound was incorrect if the Audio Listener was scaled. The new behavior allows the Audio Listener to be uniformly scaled (non-uniform scales are currently not supported)._

- You might want to reset Steam Audio Material components in your project. I was able to get rid of not hearing direct sound occlusion issue once Reset all the Steam Audio Material components and assigned them the same materials again.

None of these issues are related to HDRP specifically. Thanks for bringing them up.
