### ISSUE TITLE
unity asset bundle compatibility

### ISSUE THREAD

**Issue by Milk-Drinker01** [ValveSoftware/steam-audio#136]
Due to the way the .phononscene, .obj, .mlt, and .probes files are stored and read (through the streaming assets folder), you cannot load them when your scene is exported as an asset bundle. An asset bundle is a way to add and load content after the game is built. I am using this assetbundle system for custom mapping in my game. The following content is added to an asset bundle when you label a scene with an assetbundle label:  
![Screenshot_10](https://user-images.githubusercontent.com/59656122/99891843-5b847780-2c3c-11eb-87c8-3d8a5dc79b0f.png)
It automatically includes all models, textures, lighting data, sounds, materials, etc when you add a scene. When the assetbundle is exported, it doesnt include the files that steam audio requires to work, and when i load the scene in the game, i get the error "scene not found. make sure to pre-export the scene". I have created 2 minimal unity projects that show this behavior, if you need them to fix this issue.

**Comment by Milk-Drinker01** [comment]
the reason for having 2 minimal projects is because one of the projects is for creating maps and exporting them, and the other one loads the map. it is also worth noting that i created these project before the beta 19 release, but i also tested it in beta 19 on my main project and the issue still persists

**Comment by lakulish** [comment]
Thanks for letting us know, we are able to repro this behavior, and have implemented new functionality that changes how scenes and baked data are saved and loaded in Unity. This functionality will be available in an upcoming release.

**Comment by lakulish** [comment]
Referenced on forums: https://steamcommunity.com/app/596420/discussions/0/3109145319597485539/

**Comment by Milk-Drinker01** [comment]
> Thanks for letting us know, we are able to repro this behavior, and have implemented new functionality that changes how scenes and baked data are saved and loaded in Unity. This functionality will be available in an upcoming release.

wondering if this was added in the new beta? i didnt see anything about it in the changelog

**Comment by Milk-Drinker01** [comment]
is there any kind of ETA for that? im holding off on releasing the mapping tools for my project until there is a less hacky way for people to store the necessary data

**Comment by lakulish** [comment]
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
