### ISSUE TITLE
Unreal Engine? 

### ISSUE THREAD

**Issue by spencercap** [ValveSoftware/steam-audio#14]
Any idea when the Unreal version will become available? Time estimate? 

Cheers, looks amazing !

**Comment by freemancw** [comment]
Hey spencercap,

The UE4 plugin will ship with 4.16 - I don't have an exact date (that is Epic's timeline), but I'd guess 1-2 months from now.

Check out the GDC demo here (at 4:16:30): https://www.twitch.tv/videos/125625961
