### ISSUE TITLE
Any plans for Steam Audio to support iOS? 

### ISSUE THREAD

**Issue by tonetechnician** [ValveSoftware/steam-audio#141]
Hey there,

I really love working with Steam Audio! I was wondering if there're any thoughts from the Valve team to have the API support iOS aswell? Recently been working with mixed reality experiences in iOS and feel a tool such as this could offer a lot to these experiences. There is quite a clear lack of spatial audio tools for iOS unfortunately.

**Comment by Hetagkaty** [comment]
Are there any updates on this? I would also like iOS support.

**Comment by PeterFox-Audio** [comment]
Are there any updates on this?

**Comment by broken-bytes** [comment]
Also wondering about this

**Comment by Xottab-DUTY** [comment]
This issue can be closed as iOS support has been added in the latest release https://github.com/ValveSoftware/steam-audio/releases/tag/v4.5.0.

> Add support for iOS. Steam Audio now supports iOS devices (including both iPhone and iPad) using 64-bit ARM processors and running iOS 11.0 or later.
