### ISSUE TITLE
Unreal: I can't include PhononProbeVolume

### ISSUE THREAD

**Issue by simongloor** [ValveSoftware/steam-audio#145]
We have buildings with large numbers of rooms with known bounding boxes. Our goal is to automatically spawn PhononReverbVolumes to the map.

Unfortunately. I seem to be unable to include the PhononProbeVolume.h. I suppose this is due to it being put in the Private folder.

Is it possible to move this class (and possibly other classes that might be of interest to other users with similar needs) to the public folder and expose them to the project and other plugins?

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if you continue to face this issue in the new version.

**Comment by kisak-valve** [comment]
Closing pending feedback.
