### ISSUE TITLE
Is the quick start documentation updated?

### ISSUE THREAD

**Issue by pedrohpf** [ValveSoftware/steam-audio#150]
I just tried the starting tutorial (https://valvesoftware.github.io/steam-audio/doc/capi/page_quickstart.html) and pasted the code located at the end of the page, but I'm getting some errors in the function "iplApplyBinauralEffect".
Am I doing something wrong?

**Comment by lakulish** [comment]
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
