### ISSUE TITLE
UE4 program crashes when using the latest AMD Graphic Driver (Ver 21.4.1)

### ISSUE THREAD

**Issue by Papyrus-G** [ValveSoftware/steam-audio#151]
When set Ray Tracer to AMD Radeon Rays or set Convolution Type to AMD TrueAudio Next, the packaged UE4 program crashes on startup.
![Crash](https://user-images.githubusercontent.com/66909320/115563278-f1a2f380-a2e9-11eb-903e-281401bf145b.jpg)
[Crash.zip](https://github.com/ValveSoftware/steam-audio/files/6351266/Crash.zip)

It's OK when using old AMD Graphic Driver (Ver 21.3.1)

**Comment by kisak-valve** [comment]
Hello @Papyrus-G, the minidump you attached is a EXCEPTION_ACCESS_VIOLATION_READ in amdocl64.dll, can you clarify why you think this is a steam-audio issue and not a video driver or upstream UE4 issue?

**Comment by Papyrus-G** [comment]
Sorry for causing trouble to you. I don't know much about dump file, I spend a while thinking who I should report this issue to.
Thanks for your Friendly response, I will test this on other platform and send an issue report to AMD if needed.
