### ISSUE TITLE
Steam audio 4 - no output at all

### ISSUE THREAD

**Issue by Nafrayu** [ValveSoftware/steam-audio#156]
I just compiled the example code from
https://valvesoftware.github.io/steam-audio/doc/capi/getting-started.html#full-program-listing
on windows 20H2 using visual studio 2013 without any modifications - everything seems to be fine, but the resulting output file always ends up beeing filled with zero-bytes instead of any kind of sound.

This happens even if i modify the example to use the IPLVirtualSurroundEffect* stuff instead of IPLBinauralEffect*

Does anyone have an idea what's causing this? A few months ago i wrote an app to create HRIR files for HeSuVi using steam audio, and i'd love to update it to 4.0, but i can't get any output, no matter what i try *shrugs* 

EDIT:
I just noticed that the minimum requirements say "visual studio 2015", oops.
I'll try it on a newer copy of VS In about 12 hours and report back :D

**Comment by Nafrayu** [comment]
I just tried the same on a fresh installation of windows 10 20H2 and visual studio 2015, but i still don't get any output whatsoever, even when just compiling the getting-started program and then feeding it with a 32 bit raw pcm file :/

**Comment by youngsbt** [comment]
run as admin

**Comment by lakulish** [comment]
This appears to be an oversight in the sample code. Replace the following lines:

```
    IPLContext context{};
    IPLContextSettings contextSettings{};
```

with the following:

```
    IPLContextSettings contextSettings{};
    contextSettings.version = STEAMAUDIO_VERSION;

    IPLContext context{};
```

We will update the documentation with this change.

**Comment by lakulish** [comment]
The documentation has been updated with this change.
