### ISSUE TITLE
[Unity] Adding realtime reverb to the Steam audio listener result in a crash when entering play mode.

### ISSUE THREAD

**Issue by RedChainsaw** [ValveSoftware/steam-audio#158]
Hello,

I created an empty project with Unity 2021.1.15f1 and only added the Steam Audio 4.0.0 plugin.
Unity crashes every time when entering play mode if there is a Steam audio listener component in the scene with real-time reverb activated.

[Crash_2021-08-03_143427955.zip](https://github.com/ValveSoftware/steam-audio/files/6924970/Crash_2021-08-03_143427955.zip)

edit: Looks like the crash happens because I had the scene type set to Unity in the ray tracer settings. Setting it back to Default fixes the crash.

**Comment by lakulish** [comment]
We are able to reproduce this behavior (with the scene type set to Unity). A fix will be included in the next patch release.

**Comment by lakulish** [comment]
This issue is fixed in the latest patch release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.1.
