### ISSUE TITLE
Steam audio not updating in play mode when moving dynamic objects

### ISSUE THREAD

**Issue by antoniopoi** [ValveSoftware/steam-audio#159]
Hi everybody,
I have some problems in simulating reflections using dynamic objects. I built a very simple scene: main camera (with steam audio listener), a cube with the acoustic source (and with steam audio source) and a single wall (defined as steam audio dynamic object). In play mode, moving the wall has no effect on the reflection audio which simply keeps static. If I move the wall before entering in play mode, then it works properly. What could be wrong?

My configuration is:
- Unity 2021.1.16
- Steam audio 4.0.0
- Mac os Big Sur 11.2.3

Thank you for your help

**Comment by lakulish** [comment]
We are able to reproduce this behavior. A fix will be included in the next patch release.

**Comment by lakulish** [comment]
This issue is fixed in the latest patch release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.1.
