### ISSUE TITLE
Phonon geometry  : export all children don't work twice on same scene

### ISSUE THREAD

**Issue by ymarzack** [ValveSoftware/steam-audio#16]
Room A with a gameobject "Walls" (full of wall children elements) and phonon geometry with "export all children enabled" on it, and phonon material -> works well with occlusion (all realtime)

A second Room B, with same structure -> no sound at all (when occlusion enable)

Second room B works if i remove Wall tree from A

**Comment by achandak** [comment]
@ymarzack 

1) Make sure to Pre-Export Scene everytime you make changes to the scene. Windows > Phonon > Scene > Pre-Export scene. Let us know if that solves your issue.

2) Export to OBJ and see if the geometry exported in the OBJ file makes sense given your scene. Windows > Phonon > Scene > Export to OBJ.

3) Still facing issue then paste hierarchy where you are facing the issue. We tried to reproduce the issue but couldn't.

**Comment by ymarzack** [comment]
Thanks,

I pre-export and export OBJ geometry every time.

Maybe this is not the good cause, but there is, however, a link.
I have just noted that the sound stop playing when the audio source is beyond 40 meters from the room A, regardless the listener position. 

(even if the listener is close to the source, so it is not distance atenuation)

And works when A is disabled because B is then closer

In this screenshot, the sound is not playing because the audio source is just behind the "red line".

There is no invisible wall, i've deleted the OBJ files and pre-export again.

![capture](https://cloud.githubusercontent.com/assets/4447354/24210496/9df0ac76-0f29-11e7-8b1f-052597a9985e.PNG)

**Comment by ymarzack** [comment]
This is the Obj File, seems ok.
![objfile](https://cloud.githubusercontent.com/assets/4447354/24211060/3d686f4a-0f2b-11e7-8266-f0b8fe4c095f.PNG)

**Comment by ymarzack** [comment]
Seems it's working with a simple cube as an audio source.
My previous audio sources were animated characters, maybe an interference.

I close this ticket because i doubt it is an issue from steam Audio.
I'll re-open it eventually if i find something

**Comment by ymarzack** [comment]
Found something : 

(occlusion activated) 
The strange sound behaviour disapear when i disable the nav mesh agent of the audio source or, when i clear the bake navigation.

**Comment by achandak** [comment]
@ymarzack - What is the location of your Audio Source? Is it somehow too close to the floor?

Are there steps we can follow to reproduce the issue on our end?

**Comment by ymarzack** [comment]
@achandak : You're right !

The audio source was on the parent gameobject character, Y origin at 0.01
There was a little height difference between the two floors i didn't notice, and on B the audio source went under/in floor.

Work perfect when set at convenient height.

Shame on me for the inconvenience, guys. you're doing very good job.

**Comment by achandak** [comment]
No worries, happy to help. Thanks for providing all the useful information for us to take a guess!
