### ISSUE TITLE
phonon.h fails to compile due to empty structs

### ISSUE THREAD

**Issue by bjornbytes** [ValveSoftware/steam-audio#161]
I'm upgrading to phonon 4, but including the phonon header file in a translation unit does not compile because `IPLRadeonRaysDeviceSettings` and `IPLEmbreeDeviceSettings` are empty structs which isn't valid C.  This is minor, and I can adjust compiler settings to work around it for this file, but it's annoying.  It would be nice to have this fixed upstream.

**Comment by lakulish** [comment]
This issue is fixed in the latest patch release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.1.
