### ISSUE TITLE
Steam Audio 4.0 Spike when using additive load level

### ISSUE THREAD

**Issue by laurelhach** [ValveSoftware/steam-audio#165]
Hi,

I am getting a huge spike in the profiler under Unity when loading a level in additive.
1. I load an additive level using the low priority settings 
2. I use Unity 2020.3.16.f1.
3. Standalone build hooked to the Unity Profiler (not standalone profiler)
4. I have quite a lot of meshes that have the Steam Audio Geometry 

Here is the result:
![image](https://user-images.githubusercontent.com/6070076/130677583-c5679674-e0cd-40f4-9252-a88b2d1d8ae3.png)

I was wondering what I could do to minimize the impact.
Is it possible to delay the Commit() on multiple frames (or should I enable my meshes on multiple frames)? 

Thanks!

PS: I disabled the Steam Audio in the project settings as it still crashes in my project, but I notice that the steam manager is still called.

**Comment by CodeHatchling** [comment]
I like how the point that Steam Audio crashes is demoted to a post-script as a side note, like it were no biggie. ::P

**Comment by lakulish** [comment]
@laurelhach In the Steam Audio Settings, what is Scene Type set to? If it's set to Default, try switching it to Embree, it might reduce the impact.

Note that disabling the Steam Audio Spatializer and Steam Audio Ambisonic Decoder in the Unity project settings only disables those specific audio rendering plugins. Having Steam Audio installed in your project still means that the Steam Audio Manager will be active in case any sources are configured for simulation.

By the way, does commenting out the line `mCurrentScene.Commit();` in the `SteamAudioManager.LateUpdate` function (which is in the file `SteamAudioManager.cs`) help with the crashes?

**Comment by lakulish** [comment]
@laurelhach A patch release is out: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.2. Can you try it and let us know if it helps with the crashes and/or CPU usage spikes you're experiencing? Thanks!

**Comment by kisak-valve** [comment]
Closing pending confirmation this is still an issue.
