### ISSUE TITLE
Android ARM64 is completely broken (v4.0.2). Only ARMv7 works. (Unity + IL2CPP + Oculus Quest 2)

### ISSUE THREAD

**Issue by ForemanDesigns** [ValveSoftware/steam-audio#172]
I have integrated Steam Audio 4.0.2 in my Unity project by installing the "SteamAudio.unitypackage". I am targeting Android (Oculus Quest 2) with the IL2CPP scripting backend.

By default, the target architecture of my project was initially set to ARMv7, and builds with this configuration ran just fine on the Oculus Quest 2.

However, I just changed the target architecture to ARM64 (recommended by Oculus due to performance) and this causes Steam Audio to completely stop functioning in Android builds. I am faced with a multitude of errors that are constantly streaming (unable to load DLL 'phonon'), no spatialized audio sources play, and the game sometimes crashes. What can be done to fix Steam Audio for ARM64?

See images below:

![ARMv7](https://user-images.githubusercontent.com/49407845/138141230-64760351-25c4-40db-befd-18a92ca8a39f.png)
![ARM64](https://user-images.githubusercontent.com/49407845/138141250-89140bbe-081a-44c8-9356-6d6a4feea7d0.png)
![Error 01](https://user-images.githubusercontent.com/49407845/138141279-cbe7e275-ddd8-495d-bf23-3d1454745c09.png)
![Error 03](https://user-images.githubusercontent.com/49407845/138141287-e17ee8fe-0fce-4253-8995-188fa3168c82.png)
![Error 04](https://user-images.githubusercontent.com/49407845/138141311-b6bdcd82-8f33-438b-b7ca-e89bcaef2370.png)
(Logs from the Oculus Quest were taken via Android Logcat in Unity)

**Comment by vanGeck** [comment]
Similar issue, but the project fails to build with IL2CPP and ARM64. SteamAudio 4.0.2, Unity 2020.3.20, with all XR-related libraries updated to their newest versions.

**Comment by lakulish** [comment]
We are able to reproduce this issue. A fix will be included in an upcoming patch release.

@vanGeck We are, however, unable to reproduce the build failure with IL2CPP and ARM64. Could you provide build logs from the Unity console with the error messages? Thanks.

**Comment by ForemanDesigns** [comment]
@lakulish Thank you for the update and for confirming the issue! I am very pleased to hear that the issue will be fixed.

Do you have any estimate (even a rough guess) as to when the patch will be released? Public launch for my VR app is on November 18th (10 days from now). If the patch will not be released by then, would it be possible to directly receive a fixed version ahead of time? I would really appreciate any help, and if so, my email can be found in my profile.

Thank you!

**Comment by lakulish** [comment]
@ForemanDesigns We're aiming to release the patch early next week. Meanwhile, I've uploaded the latest internal build of the Steam Audio SDK to Dropbox at: https://www.dropbox.com/sh/6prxtdgqqt4kqfh/AACrenFM1fSbvEO7DtoiC9vGa?dl=0. It's not fully tested, but should be close to what we eventually ship.

You'll have to unzip `steamaudio.zip`, and copy the file `steamaudio/lib/android-armv8/libphonon.so` to `Assets/Plugins/SteamAudio/Binaries/Android/arm64` in your Unity project.

Let us know if this build fixes the issue you're encountering. Thanks!

**Comment by ForemanDesigns** [comment]
@lakulish Thank you very much! I will let you know once I update it.

**Comment by lakulish** [comment]
This issue should be fixed in the latest patch release: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.3. Let us know if this issue persists, we're keeping this issue open pending confirmation.

**Comment by dooly123** [comment]
Heyo, just wanted to say the  libphonon file swap. Did the trick for me was able to load test without issues. Thanks for sharing the release file early made my week at work.

**Comment by ForemanDesigns** [comment]
@lakulish Thank you for the update and for the release! I will implement it ASAP and let you know.

Also as a side note, I really appreciate you and the Valve team improving and maintaining this plugin! It doesn't go unnoticed! In my opinion it is superior to other spatializers I've tried, and I'm so delighted I can use it for mobile VR! So thank you. :)

**Comment by ForemanDesigns** [comment]
@lakulish I've confirmed that this has fixed the issue! We are now up and running with ARM64 architecture on the Quest 2 with Steam Audio fully-functional. Thank you! :)
