### ISSUE TITLE
Why there are no updates for the Unreal Engine plugin?

### ISSUE THREAD

**Issue by TheHoodieGuy02** [ValveSoftware/steam-audio#173]
With the Unity and FMOD plugins getting the up to date 4.0.x versions, why not the Unreal Engine plugin catching up as well, or no further news/plans about it whatsoever? Apart from a short "coming soon", that is.

As of 4.27 and 5.0 Early Access 2, the built-in Steam Audio still stuck in version 2.0-beta.17, and that version is still very prone to crashing with the callstack blaming on Phonon libs, even in packaged builds. I'm concerned that this issue will plague to shipping builds played on other machines.

Because as of now the plugin is still part of the main UE codebase, are there any plans to make the plugin separate from it, allowing for quicker updates without having to wait for the engine's new versions?

With Steam Audio 4.0 being rolled out, I assumed it was a good opportunity for making major changes such as decoupling it from the engine's upstream codebase.

**Comment by SkacikPL** [comment]
They're being very deliberately quiet about it, while answering other topics every now and then so i assume they lost interest in UE4 as giving it any improvements would be counter productive to their silent war with Epic/EGS.
I can't guess any other reason why they wouldn't walk out in public and openly state their reasoning for quietly dropping UE4 than some petty shenaningans behind the scenes.

**Comment by TheHoodieGuy02** [comment]
> as giving it any improvements would be counter productive to their silent war with Epic/EGS.

While it would be comedic if this actually happen, the same can't be said with Steamworks integration with UE4.
Some guys from Epic said it was partly a complication from the plugin being part of upstream UE4 repo, and supposedly barely anyone actually worked on the integration.

**Comment by DavidWLejeune** [comment]
I think runeberg left Valve, and they were the only person working on the Unreal plug-in. All of the issues that were assigned to them got closed with no resolution a while back.

I'd make a fork of the Unreal plug-in for community development, but I don't really know my way around C APIs or low level audio code so I wouldn't have much to contribute.

**Comment by TheHoodieGuy02** [comment]
Well, I guess I had to step in myself for the community fork.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes an updated Unreal Engine plugin: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.
