### ISSUE TITLE
Activating reflections with FMOD 2.0.10 and Steam Audio 4.0.2 causes editor to freeze when playing

### ISSUE THREAD

**Issue by jamoy1993** [ValveSoftware/steam-audio#175]
When I add a steam audio source to the scene and enable reflections using the Unity scene type, the editor freezes totally with no error logs. It will not unlock so I have to kill the process in the Task Manager.

I am using FMOD and Steam Audio. Versions are Steam Audio 4.0.2 and FMOD 2.00.10

I have a steam and FMOD listener in the scene and the steam audio manager is initialised correctly as occlusion works without issue.

I tested in a fresh project using the exact same settings I used in my main project. It appears when I set the ray-cast mode to unity it completely freezes the editor out when a sound has reflections enabled.

I've tried the other 3 ray tracer settings in the steam audio settings file. Embree, Default and Radeon Rays either are not compatible with my card or just don't work for even occlusion or reflections. I have baked a set of basic walls into a steam audio static mesh.

The only one that has worked remotely is the Unity setting. But it still freezes the editor completely in an update editor loop every time I start the scene when an audio source has reflections enabled.

I can provide an example project if required.

I have tested this in both versions 2021.2.0f1 and 2021.1.22f1

**Comment by jamoy1993** [comment]
I have also tried this without FMOD. It does seem to break on Unity scene mode. It however does work on Default mode without FMOD.

**Comment by achandak** [comment]
Hey @jamoy1993 - I will try to repro it on my end. If you have a test scene that readily repors the issue, please feel free to share.

**Comment by jamoy1993** [comment]
> 
> 
> Hey @jamoy1993 - I will try to repro it on my end. If you have a test scene that readily repors the issue, please feel free to share.

Certainly here is the scene (I have also packaged the mesh and probe batch as well)

[https://www.pastefile.com/qknwkq](url)

**Comment by achandak** [comment]
@jamoy1993 - I am not able to reproduce the issue on the project you shared. Here are a few additional questions for you.

- What platform are you on? I did my testing on windows.
- I used FMOD 2.1.10 and Unity 2021.1.14 (this should not be be factor)
- Attached is updated version of your project which worked fine for me. I tested with Scene Type: Default.
- Also tested with Scene Type: Embree and that worked too.  Also, I used real time reflections - seems like that is what you are using but I see some probe batches. 
- FMOD + Scene Type: Unity and simple occlusion worked for me as well. It uses Unity's internal ray tracer and at the moment [not suitable for reflection](https://valvesoftware.github.io/steam-audio/doc/unity/settings.html?highlight=scene%20type) or pathing in Steam Audio

[issue-175.zip](https://github.com/ValveSoftware/steam-audio/files/7499616/issue-175.zip)

**Comment by jamoy1993** [comment]
Here is a minimal project. Which consists of what I sent you and the project. When I activate unity's raytracer I get the same freezing behaviour I have mentioned. It works fine with Embree.

NOTE: For some reason, FMOD keeps losing reference to the phonon_fmod dll. You will have to add these in when you open up the project.

https://drive.google.com/file/d/1ToDEZuJsUgfT2k9-OI0fXVYi8yP8JsaC/view?usp=sharing

**Comment by achandak** [comment]
@jamoy1993  What platform are you on - Windows? Unity raytracer + reflections won't work at the moment. So, hang behavior makes sense. This for a technical reason where we have to call Unity's inbuilt ray tracer from the main thread, which takes quite a bit of time, and therefore hangs the Editor.

So, you are able to get reflections to work with Default and Embree raytracer? I think I misread your 2nd post from 6 days ago. If yes, there is not much we can do at the moment about Unity raytracer + reflections. Thanks.

**Comment by jamoy1993** [comment]
Hey, I am using Windows 10. My reflections work fine using Embree, that is correct. 

Perhaps it would be best to make it more apparent there is currently an issue with the unity raytracing module within steam audio?

Thanks for the help.
