### ISSUE TITLE
Does it only support [pcm_f32le] format data, does it not support [pcm_s16le] data, or is there any way to convert [pcm_s16le] data to [pcm_f32le]

### ISSUE THREAD

**Issue by wgx954418992** [ValveSoftware/steam-audio#177]
Does it only support [pcm_f32le] format data, does it not support [pcm_s16le] data, or is there any way to convert [pcm_s16le] data to [pcm_f32le]

**Comment by lakulish** [comment]
The Steam Audio API only supports 32-bit float audio buffers. Conversion to/from signed 16-bit int samples (or any other sample format) will have to be managed by the application or audio engine integration.
