### ISSUE TITLE
Per frame memory allocations Unity il2cpp

### ISSUE THREAD

**Issue by SimonFireproof** [ValveSoftware/steam-audio#178]
Steam Audio 4.0.3
Unity 2021.1.28

When building using il2cpp I am seeing a significant amount of runtime memory allocation - 3 x 112 bytes per audio source per frame.
However, if I build with Mono there are zero per frame memory allocations.

I have profiled builds for Windows and Android which seem to give the same results. This is what I'm seeing in the profiler:
![Screenshot 2021-12-01 120613](https://user-images.githubusercontent.com/95351561/144231662-c836635c-62b6-4b73-858b-ad17d664f1cd.jpg)
We're building for Quest 2 and previously we're run into problems with garbage collection causing spikes. So I'm keen on keeping per frame allocations to a minimum.

**Comment by PavPod** [comment]
Bump, this is causing us untold pain on Quest 2 with allocations in the 60kb/frame with lots of sources active. Causes GC collections every 2 seconds or so.

**Comment by lakulish** [comment]
We are able to reproduce the `GC.Alloc` calls (attributed to `API.iplSourceSetInputs` in the main thread as shown above) in Unity 2021.1. However, we are unable to reproduce the same issue in Unity 2022.3. @SimonFireproof @vTimePav are you able to reproduce the issue in the latest version of Unity?

There is a separate issue where `GC.Alloc` calls happen on the Steam Audio simulation thread, which we are aiming to fix for the next release.

**Comment by SimonFireproof** [comment]
Sorry I decided not to use Steam Audio because of this issue, and we’re still using 2021, so it’s not easy for me to test.

**Comment by lakulish** [comment]
We have just released v4.3.0 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.3.0), which fixes this issue.
