### ISSUE TITLE
Does Steam Audio work in Unity Editor for ambisonic sounds?

### ISSUE THREAD

**Issue by ryan-motive** [ValveSoftware/steam-audio#179]
I'm trying to get a simple ambisonic sound playing in Unity. I've followed the steps in the Getting Started guide but I can't seem to get ambisonics working at all in the editor (haven't tried a build yet--that's next). Does this plug-in work in the editor or is it expected that it doesn't?

It's also possible that the sound is playing ambisonic properly, but the effect is just difficult to notice. Can anyone recommend a source file that would make the effect very distinct--e.g. a distinct sound coming from only one direction?

Finally, I may be missing some settings. I've so far:

- Set the Spatializer Plugin and Ambisonic Decoder Plugin to Steam Audio
- Imported an AmbiX file and marked it as ambisonic
- Attached the file to an Audio Source
> Source is *not* marked Spatialize
> Set Spatial Blend to full 3D

Beyond this I haven't changed any other settings. In particular I haven't added any of the Steam-specific components because from what I can tell the plugin should work without these.

If there are any other settings that might affect this please let me know!

**Comment by ryan-motive** [comment]
I realize that the Spatial Blend is most likely supposed to be 2D for ambisonic? This un-3Ds the sound, but it still seems stuck to my head (I'm testing this in VR).

**Comment by achandak** [comment]
@ryan-motive - You are right. It should just work with the way you described it.

You can attach a [Steam Audio Ambisonic Source](https://valvesoftware.github.io/steam-audio/doc/unity/ambisonic-source.html) component and toggle Apply HRTF to hear the difference. Reopen the issue if you still think you can't hear any difference or it is not what you expect. Also, please share Ambisonic file if possible in that case.

**Comment by ryan-motive** [comment]
Ok can you please verify that attaching Steam Audio Ambisonic Source is required? I did not do that and the documentation makes it sound like it should work with a normal, unaltered audio source. This is an important distinction and I want to make sure I understand that this is a requirement because it will have an impact on how or if we decide to use this package.

**Comment by achandak** [comment]
It is not required. But you can attach and toggle Apply HRTF option to hear the spatialized and unspatialized Ambisonic audio. Let us know what you hear.
