### ISSUE TITLE
Custom HRTF data on Binaural renderer

### ISSUE THREAD

**Issue by Furtivo89** [ValveSoftware/steam-audio#18]
I'm interested to use a custom HRTF for the binaural renderer. I see there is a parameter to set to do this task: `IPLbyte* hrtfData`, a pointer to a byte array containing HRTF data in the function `IPLAPI IPLerror iplCreateBinauralRenderer(IPLContext context, IPLRenderingSettings renderingSettings,
        IPLbyte* hrtfData, IPLhandle* renderer);`
There is no documentation about the format of this byte array. Anyone can help me?

<img width="851" alt="binaural renderer" src="https://cloud.githubusercontent.com/assets/10852577/24357879/6dcf1bb6-12ff-11e7-862d-bc97d12381fd.png">

**Comment by Luux** [comment]
I would like to use this, too. If it's possible to use custom HRTF data, I could use this for our virtual reality project @university we have to do this semester...

Is this option theoretically available in the unity integration, too?

**Comment by achandak** [comment]
@Furtivo89, @Luux - We have added support for custom HRTFs in Steam Audio C API in the latest release. For more details see [release notes](http://steamcommunity.com/games/596420/announcements/detail/1299696599437459444) and download the latest version.
