### ISSUE TITLE
Transmission not working right for me

### ISSUE THREAD

**Issue by veganburrito86** [ValveSoftware/steam-audio#182]
I'm using Steam Audio 4.0.3, FMOD 2.02, Unity 2021.2.7f1

When I have Transmission set to "Simulation-defined" in FMOD Studio, I can't hear the sound at all. When I set it to "user-defined" and I turn the transmission knobs up, I can hear it and it works fine.

What might cause this issue? A few other notes:

- I have Steam Audio Materials applied to the geometry with the Steam Audio Geometry component. The materials have transmission turned up, and it doesn't seem to matter how high or low I set them - the issue remains either way.
- The scene is exported with Steam Audio > Export Active Scene.
- I tried with a gameobject that has a FMOD Studio Event Emitter, and also with an object that just has its own script where an FMOD event instance is created and played at runtime.

Again, it seems to work completely fine when Transmission is set to "user-defined" and I play with the knobs in FMOD Studio. So either my scene is missing some setup step OR Transmission is not getting properly updated through the Steam Audio Source.

Thank you in advance for any help with this.

**Comment by Mak2021-lol** [comment]
same problem((
