### ISSUE TITLE
(audioplugin_phonon) UnityGetAudioEffectDefinitions crash in Unity

### ISSUE THREAD

**Issue by themars2011** [ValveSoftware/steam-audio#185]
Hello,

this issue was noted as fixed but it still happens to me with the latest version of Steam Audio and Unity (2021.2.8f1).
These are the stack frames:
Received signal SIGSEGV
Obtained 55 stack frames
0x00007ff9c56ed012 (audioplugin_phonon) UnityGetAudioEffectDefinitions
0x00007ff73129ecc1 (Unity) UnityAudioEffect_InternalSetFloatParameterCallback
0x00007ff732b0673e (Unity) FMOD::DSP::setParameter
0x00007ff7312c94b5 (Unity) AudioSource::SetSpatializerFloat
0x00007ff730222dcd (Unity) AudioSource_CUSTOM_SetSpatializerFloat
0x0000014678e0ede9 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.AudioSource:SetSpatializerFloat (UnityEngine.AudioSource,int,single)
0x0000014678e0f08b (Mono JIT Code) [UnityAudioEngineSource.cs:94] SteamAudio.UnityAudioEngineSource:SetSpatializerIntPtr (intptr,int&) 
0x0000014678e0eb7b (Mono JIT Code) [UnityAudioEngineSource.cs:56] SteamAudio.UnityAudioEngineSource:UpdateParameters (SteamAudio.SteamAudioSource) 
0x0000014678e0dce1 (Mono JIT Code) [SteamAudioSource.cs:166] SteamAudio.SteamAudioSource:Awake () 
0x00000146a226ad48 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007ff9bebee034 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ff9beb2e724 (mono-2.0-bdwgc) [object.c:3064] do_runtime_invoke 
0x00007ff9beb2e8bc (mono-2.0-bdwgc) [object.c:3111] mono_runtime_invoke 
0x00007ff730dd4e44 (Unity) scripting_method_invoke
0x00007ff730dcfa64 (Unity) ScriptingInvocation::Invoke
0x00007ff730dcfb4e (Unity) ScriptingInvocation::InvokeChecked
0x00007ff730e48d66 (Unity) SerializableManagedRef::CallMethod
0x00007ff730d9d274 (Unity) MonoBehaviour::CallAwake
0x00007ff730d9bb35 (Unity) MonoBehaviour::AddToManager
0x00007ff730d9c4b1 (Unity) MonoBehaviour::AwakeFromLoad
0x00007ff730e89587 (Unity) AwakeFromLoadQueue::InvokeAwakeFromLoad
0x00007ff730e84553 (Unity) AwakeFromLoadQueue::AwakeFromLoadAllQueues
0x00007ff7308a09b2 (Unity) AwakeAndActivateClonedObjects
0x00007ff7308a1d75 (Unity) CloneObject
0x00007ff72ffead43 (Unity) Object_CUSTOM_Internal_CloneSingleWithParent
0x000001462f37b2f8 (Mono JIT Code) (wrapper managed-to-native) UnityEngine.Object:Internal_CloneSingleWithParent (UnityEngine.Object,UnityEngine.Transform,bool)
0x000001462f37b10b (Mono JIT Code) UnityEngine.Object:Instantiate (UnityEngine.Object,UnityEngine.Transform,bool)
0x000001462f37affb (Mono JIT Code) UnityEngine.Object:Instantiate<T_REF> (T_REF,UnityEngine.Transform,bool)
0x00000146a101865b (Mono JIT Code) [PZ_Zombie.cs:421] ProjektZ.AI.PZ_Zombie:OnStartServer () 
0x00000146564a2618 (Mono JIT Code) [NetworkIdentity.cs:669] Mirror.NetworkIdentity:OnStartServer () 
0x00000146564a2203 (Mono JIT Code) [NetworkServer.cs:1025] Mirror.NetworkServer:SpawnObject (UnityEngine.GameObject,Mirror.NetworkConnection) 
0x00000146564a1f43 (Mono JIT Code) [NetworkServer.cs:1048] Mirror.NetworkServer:Spawn (UnityEngine.GameObject,Mirror.NetworkConnection) 
0x00000146a0e49c9b (Mono JIT Code) [PZ_GameModeWave.cs:505] ProjektZ.GameModes.Wave.PZ_GameModeWave:OnUpdate (ProjektZ.GameModes.Wave.PZ_WaveNetwork) 
0x00000146a0e49173 (Mono JIT Code) [PZ_WaveNetwork.cs:119] ProjektZ.GameModes.Wave.PZ_WaveNetwork:Update () 
0x00000146a0db8118 (Mono JIT Code) (wrapper runtime-invoke) object:runtime_invoke_void__this__ (object,intptr,intptr,intptr)
0x00007ff9bebee034 (mono-2.0-bdwgc) [mini-runtime.c:3445] mono_jit_runtime_invoke 
0x00007ff9beb2e724 (mono-2.0-bdwgc) [object.c:3064] do_runtime_invoke 
0x00007ff9beb2e8bc (mono-2.0-bdwgc) [object.c:3111] mono_runtime_invoke 
0x00007ff730dd4e44 (Unity) scripting_method_invoke
0x00007ff730dcfa64 (Unity) ScriptingInvocation::Invoke
0x00007ff730d9d424 (Unity) MonoBehaviour::CallMethodIfAvailable
0x00007ff730d9d52c (Unity) MonoBehaviour::CallUpdateMethod
0x00007ff73089dd58 (Unity) BaseBehaviourManager::CommonUpdate<BehaviourManager>
0x00007ff7308a533a (Unity) BehaviourManager::Update
0x00007ff730ab395d (Unity) `InitPlayerLoopCallbacks'::`2'::UpdateScriptRunBehaviourUpdateRegistrator::Forward
0x00007ff730a9a97c (Unity) ExecutePlayerLoop
0x00007ff730a9aa53 (Unity) ExecutePlayerLoop
0x00007ff730aa0669 (Unity) PlayerLoop
0x00007ff7319ce1e8 (Unity) PlayerLoopController::UpdateScene
0x00007ff7319cc3cf (Unity) Application::TickTimer
0x00007ff731e0803a (Unity) MainMessageLoop
0x00007ff731e0c90b (Unity) WinMain
0x00007ff73311d942 (Unity) __scrt_common_main_seh
0x00007ffa36977034 (KERNEL32) BaseThreadInitThunk
0x00007ffa38582651 (ntdll) RtlUserThreadStart

I attached the dmp file
[crash.zip](https://github.com/ValveSoftware/steam-audio/files/7892003/crash.zip)
.

**Comment by stepperman** [comment]
Because the crashing is so sporadic, I've decided on building the audioplugin_phonon.dll from source together with the PBD files on a newer toolset so I can provide more information when something happens. So far I couldn't trigger any crashes. (except for one in the editor, but that was a different exception this time) I will check back in this thread later when I have updates.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes various crash fixes: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if these crashes persist in the new version.

**Comment by DenisSulyagin** [comment]
> We've just released Steam Audio 4.1.0, which includes various crash fixes: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.
> 
> Try it out and let us know if these crashes persist in the new version.

4.1.1 has this problem

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.2, which contains a potential fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2. Try it out, and let us know if the issue persists.

**Comment by kisak-valve** [comment]
Closing pending feedback.
