### ISSUE TITLE
Photon errors with Fmod/Unity

### ISSUE THREAD

**Issue by antondoggo** [ValveSoftware/steam-audio#188]
Hey, I am implementing steam audio into a unity project using FMOD. I got the spatialization to work, but the occlusion does not work and I get these errors.
I followed the documentation with moving the plugin files. I am using Unity 2020.3.27f1, FMOD 2.02.04 and steam audio 4.0.3.

Multiple plugins with the same name 'phonon_fmod' (found at 'Assets/Fmod/FPS_Fmod_Project/Plugins/phonon_fmod.dll' and 'Assets/Plugins/FMOD/platforms/win/lib/x86_64/phonon_fmod.dll'). That means one or more plugins are set to be compatible with Editor. Only one plugin at the time can be used by Editor.

Multiple plugins with the same name 'phonon' (found at 'Assets/Fmod/FPS_Fmod_Project/Plugins/phonon.dll' and 'Assets/Plugins/SteamAudio/Binaries/Windows/x86_64/phonon.dll'). That means one or more plugins are set to be compatible with Editor. Only one plugin at the time can be used by Editor.

Thanks!

Nicolai.

**Comment by constantinpopp** [comment]
the error sounds like you have several copies of the phonon.dll and phonon_fmod.dll installed. remove the ones found at Assets/Fmod/FPS_Fmod_Project/Plugins/phonon_fmod.dll and Assets/Fmod/FPS_Fmod_Project/Plugins/phonon.dll. it's actually using only the plugins found at: 'Assets/Plugins/FMOD/platforms/win/lib/x86_64/phonon_fmod.dll'.
hope this helps.

**Comment by lakulish** [comment]
That's correct, you seem to have an extra copy of both `phonon.dll` and `phonon_fmod.dll`. You only need:

* `Assets/Plugins/FMOD/platforms/win/lib/x86_64/phonon_fmod.dll` (delete the other copy of `phonon_fmod.dll`)
* `Assets/Plugins/SteamAudio/Binaries/Windows/x86_64/phonon.dll` (delete the other copy of `phonon.dll`)

Let us know if the issue persists after removing the duplicate DLLs.
