### ISSUE TITLE
[FMOD/Unity] Duplicate Min/Max-Distance settings

### ISSUE THREAD

**Issue by constantinpopp** [ValveSoftware/steam-audio#193]
Hi,
I am using FMOD Studio 2.02.05. Firelight technologies changed the way the max distance setting is handled and have moved this now to the "event macros" setting.  However SteamAudio still uses the old way with setting it within the plugin dialog. Which of the two settings will actually be regarded? The slider within the plugin dialog is very fiddly, i.e. the scale is too large, with one being unable to set smaller values, such as 15 or 5 or 20 ms. 

![image](https://user-images.githubusercontent.com/2156449/158868508-10590b5c-2961-407e-ada9-3a7186d59f0d.png)

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes support for the new min/max distance sliders in FMOD Studio 2.02+: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.
