### ISSUE TITLE
TAN on Linux?

### ISSUE THREAD

**Issue by duplexsystem** [ValveSoftware/steam-audio#195]
It's possible to build TAN on linux. Will the provided linux binaries work with TAN binaries with the same public header files as the windows version? Thanks.

**Comment by lakulish** [comment]
@duplexsystem While it might be possible to build Steam Audio with TAN support on Linux, now that the entire SDK is open source, we have not built or tested this combination, and do not have any plans to support it. That said, if you are able to get this to work, feel free to open a pull request.
