### ISSUE TITLE
Sporadically, Steam Audio Return does not work

### ISSUE THREAD

**Issue by DenisSulyagin** [ValveSoftware/steam-audio#197]
In most cases, Steam Audio Return does not work. In the editor, it is solved by reassignment. v4.0.3 Release. In version v2.0-beta.20 Release this was not observed

**Comment by lakulish** [comment]
Can you provide more details on what steps need to be taken in order to reproduce the issue? Alternately, could you provide a minimal scene/project that reproduces the issue? Thanks!

**Comment by DenisSulyagin** [comment]
this problem occurs only in the editor, steamAudioReturn does not work at all in the assembly (223)

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.2, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2. Try it out, and let us know if the issue persists.
