### ISSUE TITLE
SetSpatializerFloat memory leak

### ISSUE THREAD

**Issue by DenisSulyagin** [ValveSoftware/steam-audio#199]
SetSpatializerFloat allocates the amount of memory once, which is not cleared after the destroying of SteamAudioSource.

void SetSpatializerIntPtr(IntPtr ptr, ref int index) <-- only if the pointer is correct

mAudioSource.SetSpatializerFloat(index++, valueLow);  <-- allocating
mAudioSource.SetSpatializerFloat(index++, valueHigh); <-- allocating

Unity 2021.2.3f1
SteamAudio 4.0.3.

**Comment by DenisSulyagin** [comment]
I am sending you a project reproducing this problem

1. Press Play
2. Watch out for RAM

https://drive.google.com/file/d/1vAoL0tdLG13C2OPWHiD5Yk44km9TdwZ0/view?usp=sharing

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0, which includes a fix for the memory leak: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0.

Try it out and let us know if the memory leaks persist in the new version.

**Comment by lakulish** [comment]
Thanks for letting us know, we've released a new version: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.1. This should hopefully fix the memory leak. Try it out, and let us know if this fixes the issue.

**Comment by DenisSulyagin** [comment]
> Thanks for letting us know, we've released a new version: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.1. This should hopefully fix the memory leak. Try it out, and let us know if this fixes the issue.



> Thanks for letting us know, we've released a new version: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.1. This should hopefully fix the memory leak. Try it out, and let us know if this fixes the issue.

it works fine
