### ISSUE TITLE
No Longer supported? 

### ISSUE THREAD

**Issue by aflatau** [ValveSoftware/steam-audio#203]
Is Valve no longer working on this project for Unity? 

There are some serious issues with the current branch, causing a lot of random crashes on loading. 
Last update was over 7 months ago. 

Is any one else considering not even using Steam Audio for there Unity project? 
I am seriously considering removing it, because of this, and it's really disappointing.

**Comment by futurecreep-dev** [comment]
The main dev's latest forum activity was on April 25 2022. Work is submitted to some Valve internal Perforce server then occasionally pushed onto here for releases.

It's also worth noting that Steam Audio evolved from Phonon by Impulsonic. Impulsonic was acquired by Valve. All past Valve company acquisitions have been put to good use, and Steam Audio has already proven its worth with games like Half Life: Alyx and Budget Cuts (VR game, Unity).

It's a free solution with no promises made, it's up to each developer to make the call about committing to it. I think these integrations are really close to being production ready and it would be a great shame if updates stopped here. It's important to show interest and support for it and hope it doesn't get afflicted with "Valve time".

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.0: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.0. This release includes various bug fixes, new API features, and a major update to the Unreal Engine plugin.
