### ISSUE TITLE
Incorrect plugin paths for phonon_fmod

### ISSUE THREAD

**Issue by GabrielHare** [ValveSoftware/steam-audio#205]
SETUP:
SteamAudio v4.0.3
FMODv2.2.4
Unity2019.4.36f1

The phonon_fmod plugins in the Unity package are located in 'Assets/Plugins/FMOD/lib/OS/ARCH/phonon_fmod.xxx'
However, in order for this version of FMOD to load the plugin the path must be 'Assets/Plugins/FMOD/platforms/OS/lib/ARCH/phonon_fmod.xxx'

If the plugin files are not in the correct location, FMOD cannot automatically load them. Additionally, there will be a stream of the following error in the console, which I did not initially realize was related to the FMOD plugin location issue:

DllNotFoundException: phonon_fmod
SteamAudio.FMODStudioAudioEngineState.Initialize (System.IntPtr context, System.IntPtr defaultHRTF, SteamAudio.SimulationSettings simulationSettings) (at Assets/Plugins/SteamAudio/Scripts/Runtime/FMODStudioAudioEngineState.cs:16)
SteamAudio.SteamAudioManager.OnApplicationStart (SteamAudio.ManagerInitReason reason) (at Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs:383)
SteamAudio.SteamAudioManager.Initialize (SteamAudio.ManagerInitReason reason) (at Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs:565)
SteamAudio.SteamAudioManager.AutoInitialize () (at Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs:1225)

WORKAROUND: Just move the plugin files to the correct location.

REQUEST: Hopefully this can be fixed in the next release (or the documentation can be updated)

**Comment by SnovlLokk** [comment]
Thank you very much for the information, it helped me. This is still relevant.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.2 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2), which contains a new menu command for ensuring that the plugin files are placed in the correct directory: https://valvesoftware.github.io/steam-audio/doc/unity/menu-commands.html.
