### ISSUE TITLE
UE5 Please

### ISSUE THREAD

**Issue by whostea** [ValveSoftware/steam-audio#210]
Please, build plugin for ue5.0 and later

**Comment by ShaneTim** [comment]
I've been looking into what's holding it back and there are two things I can see right now.

One is SteamAudioSDK.Build.cs has a reference to the Win32 target platform.  This entire block can be removed (I think).

The second is two vector conversions throwing errors in lines 107 and 291 of SteamAudioScene.cpp

I'm far from an expert but I'm going to see if I can get the plugin to compile after resolving those issues.  There's a good chance I'll hit more snags but if I have luck, I'll report back. :)

**Comment by devhyper** [comment]
I got it to compile with these changes:
https://github.com/devhyper/steam-audio/commit/77d58a76a83e00418e3ccb31fee69a48997612cf

**Comment by aptrn** [comment]
> I got it to compile with these changes: [devhyper@77d58a7](https://github.com/devhyper/steam-audio/commit/77d58a76a83e00418e3ccb31fee69a48997612cf)

I could get the plugin to compile but the "Steam Audio" Mode doesn't show up (therefore cannot export the scene nor bake reverbs).
Did you find a way to make it work in your fork?

**Comment by devhyper** [comment]
> I could get the plugin to compile but the "Steam Audio" Mode doesn't show up (therefore cannot export the scene nor bake reverbs). Did you find a way to make it work in your fork?

The steam audio mode shows up for me.
![51531](https://user-images.githubusercontent.com/57877914/202829410-7b64e6a0-27bc-42f6-96c8-cdad8e789ece.PNG)

**Comment by aptrn** [comment]
Hey @devhyper that's really great news for me, I was going to use the 2.1.1 version since I couldn't make it work but this really gives me hope!

Sad news is that I tried again and again and I still cannot get the Steam Audio Mode to show up 😭 

What I'm doing atm is:
 - Clone your fork
 - Add ```shutil.copy("steamaudio/lib/windows-x64/phonon.lib", "src/SteamAudioUnreal/Plugins/SteamAudio/Source/SteamAudioSDK/lib/windows-x64")``` to line 50 of `setup.py` (without this one the build fails while looking for "phonon.lib", I guess this is the problematic bit!)
 - Run `setup.py`
- `cd build` and `mkdir windows-vs2019-x64` and `cmake-gui ../..`
- Configured like this 
![image](https://user-images.githubusercontent.com/39311247/202906677-74329ba9-3c25-4518-88a3-328220d8f6fd.png)

- Double click on `Phonon.sln` and build solution

Build doesnt finish for `phonon_unreal_fmod` and `phonon_unreal_fmod_setup` reporting error below, but I guess that should not matter since I won't use Fmod Studio (not sure if that's needed anyway, also not sure of what's breaking the copy process).

```Error copying directory from "C:/sa/steam-audio/unreal/src/SteamAudioUnreal/Plugins/FMODStudio" to "C:/sa/steam-audio/unreal/build/windows-vs2019-x64/src/HostProjectFMOD/Plugins/FMODStudio".```


Then build finishes for `phonon_unreal_win64`  and therefore I can open up ```unreal\build\windows-vs2019-x64\src\HostProject\HostProject.uproject``` 🙏 

When opened I can select Steam Audio as spatialization plugin in the project settings,

![image](https://user-images.githubusercontent.com/39311247/202907021-42c993a9-0da9-465b-8a90-d621de1750f0.png)

add Steam Audio components to actors ,

![image](https://user-images.githubusercontent.com/39311247/202907128-6562492c-f086-4010-88c5-679faaf03708.png)

but cannot select the Steam Audio Mode in the dropdown! 😭😭😭 

![image](https://user-images.githubusercontent.com/39311247/202907163-3eb42ef4-6987-4a16-81c3-0231273d9d66.png)


If you have time could you please help me finding what's wrong on my side?
And eventually, if that's doable to you, share the working compiled plugin?

Thank you anyway, your screenshot will make me push this until I get it to work anyway

**Comment by devhyper** [comment]
Here is the compiled plugin:
[https://github.com/devhyper/steam-audio/releases/download/v4.1.1/steam-audio-package.zip](url)

As for the build, I used the build.py script after running setup.py:

1. Open steam-audio/unreal/build/FindUnreal.cmake and replace ${UNREAL_EXECUTABLE_DIR} with the path to unrealbuildtool (ENGINEDIR/Engine/Binaries/DotNET/AutomationTool)
2. Open build.py and find -DSTEAMAUDIOUNREAL_BUILD_DOCS=TRUE, change it to false
3. Open a command prompt in that directory and run `python build.py -o install` it will error out, should be fine.
4. Go to steam-audio/unreal/bin/unreal and copy SteamAudio directory to replace ENGINEDIR/Engine/Plugins/Runtime/Steam/SteamAudio

**Comment by aptrn** [comment]
First of all, thank you a lot for your immediate response, that's very kind of you!

Sad thing is that basically I've been doing same steps you wrote down and the build that come out of that still didn't t show the Steam Audio Mode. 
So I tried your compiled plugin package and it does behave the same, no Steam Audio Mode available!

I'm not sure what's the error at this point.
I repaired my 5.0.3 installation and also tried with 5.1 but that the mode just never appears in the editor  🤔 😭

**Comment by aptrn** [comment]
Continuing with strange behaviour, I noticed that if I go in the Tools dropdown menu with a Level opened up nothing shows up

![2022-11-21 12_07_36-Test_CompileSA - Unreal Editor](https://user-images.githubusercontent.com/39311247/203047078-93202da1-8759-4fd8-930d-5eb438851580.png)

But then, if I move to the Plugins tab and check the Tools dropdown again, a "Bake Indirect Sound" options appears

![2022-11-21 12_07_52-Test_CompileSA - Unreal Editor](https://user-images.githubusercontent.com/39311247/203047334-87d79379-aa3e-48e2-85ef-ce5c8b577ef4.png)

🤔

**Comment by devhyper** [comment]
So turns out I was using the 2.0 version of the plugin. When I put my build in I wasn't able to see the Steam Audio Mode either. I did find the issue though. https://github.com/devhyper/steam-audio/commit/2ee6775131b0343cf6d1001da3165e522a78331e The mode is now a toolbar button:
![steamaudio](https://user-images.githubusercontent.com/57877914/203657069-dd7b0e23-8c19-4fb1-b2b5-07177ce1a5c6.PNG)

@aptrn

**Comment by aptrn** [comment]
Ohhh, that's SO great!
Compiled off your fork, usual two fixes to make it compile and now IT WORKZ 🎉 
Thank you a lot for your work, my winter is now unlocked 🤯 🎇

**Comment by whostea** [comment]
hi, can you give a build for ue5.1?

> So turns out I was using the 2.0 version of the plugin. When I put my build in I wasn't able to see the Steam Audio Mode either. I did find the issue though. [devhyper@2ee6775](https://github.com/devhyper/steam-audio/commit/2ee6775131b0343cf6d1001da3165e522a78331e) The mode is now a toolbar button: ![steamaudio](https://user-images.githubusercontent.com/57877914/203657069-dd7b0e23-8c19-4fb1-b2b5-07177ce1a5c6.PNG)
> 
> @aptrn

**Comment by devhyper** [comment]
@whostea 
https://github.com/devhyper/steam-audio/releases/tag/v4.1.2

**Comment by MikeGO2611** [comment]
How about the SteamAudioFMODStudio integration plugin?
SteamAudio plugin for unreal works good for me, what is giving me an issue is the integration plugin, and I don't have any idea on how to fix that.
I'm trying to use FMOD in UE 5.1 and using the steam audio too as stated in the documentation.

**Comment by MikeGO2611** [comment]
Nevermind, I decided to go back to UE5.0.3, using @devhyper fork, and it works flawlessly now. Thank you!!!

**Comment by googleooer** [comment]
> @whostea https://github.com/devhyper/steam-audio/releases/tag/v4.1.2

Doesn't work on my end, it says it was compiled for 5.0.0

**Comment by devhyper** [comment]
@googleooer Edit the .uplugin file and change 5.0.0 to 5.1.0

**Comment by RYRY1002** [comment]
@devhyper
After trying to use your prebuild version and following your instructions to compile the plugin, I receive this error no matter what I try.
![Screenshot 2022-12-24 023548](https://user-images.githubusercontent.com/56659369/209361240-38b86888-5263-45d5-bcd4-34605b0cff97.png)

Do you have any suggestions?

**Comment by MikeGO2611** [comment]
@RYRY1002 I had the same issue. Which version of UE5 are u using? Did you try compiling in Visual Code? If so, what errors did it returned?

**Comment by googleooer** [comment]
> @googleooer Edit the .uplugin file and change 5.0.0 to 5.1.0

Yeah I tried that, but I get the errors above

**Comment by RYRY1002** [comment]
> @RYRY1002 I had the same issue. Which version of UE5 are u using? Did you try compiling in Visual Code? If so, what errors did it returned?

I used 5.1. Compiled with the build.py script

**Comment by MikeGO2611** [comment]
> > @RYRY1002 I had the same issue. Which version of UE5 are u using? Did you try compiling in Visual Code? If so, what errors did it returned?
> 
> I used 5.1. Compiled with the build.py script only.

So, what I did was compiling the project with the plugin, not the plugin itself. To do so, you need a c++ unreal project, I would suggest creating a new project with C++ instead of blueprints just for compiling. Delete SteamAudio plugin folders from the engine installation path. On your project, copy the plugins in the folder "Plugins" (you will need to create that folder next to the .uproject). Then you should add the SteamAudio plugin from @devhyper fork, start the project and enable the plugins, close unreal. Open the .snl created and located next to the project .uproject with visual studio.
On Visual Studio you can build your project as in the next image:
![image](https://user-images.githubusercontent.com/9802509/209378745-7bcb3d2b-91f9-4026-81b9-90db368855b4.png)

It will try to compile. If it compiles, great, you can just copy the plugins of the project to your project. If not (the most probable one), show us what errors visual studio returns.

**Comment by googleooer** [comment]
> > > @RYRY1002 I had the same issue. Which version of UE5 are u using? Did you try compiling in Visual Code? If so, what errors did it returned?
> > 
> > 
> > I used 5.1. Compiled with the build.py script only.
> 
> So, what I did was compiling the project with the plugin, not the plugin itself. To do so, you need a c++ unreal project, I would suggest creating a new project with C++ instead of blueprints just for compiling. Delete SteamAudio plugin folders from the engine installation path. On your project, copy the plugins in the folder "Plugins" (you will need to create that folder next to the .uproject). Then you should add the SteamAudio plugin from @devhyper fork, start the project and enable the plugins, close unreal. Open the .snl created and located next to the project .uproject with visual studio. In a window you will see a list with your project, right click over your project name and choose "Build".
> 
> It will try to compile. If it compiles, great, you can just copy the plugins of the project to your project. If not (the most probable one), show us what errors visual studio returns.

If it worked for you, can you share your successfuly compiled version?

**Comment by MikeGO2611** [comment]
> 

I can, sadly I don't have access to the computer with the compile version until 9 of January. Until then, I cannot share it.

**Comment by googleooer** [comment]
I got it to compile and load, but it's nowhere to be seen in the editor even though it's enabled

**Comment by googleooer** [comment]
Nevermind it worked, i was trying to compile the release instead of the source lol

**Comment by RYRY1002** [comment]
> Replying to [#210 (comment)](https://github.com/ValveSoftware/steam-audio/issues/210#issuecomment-1364141910)

Thanks! Following this tutorial, I managed to get it to compile.
[Here is my compiled version](https://cdn.discordapp.com/attachments/814066163075252230/1056765257344880731/SteamAudio.7z) (place in `UE_5.1\Engine\Plugins\Runtime\Steam`)

**Comment by googleooer** [comment]
> > Replying to [#210 (comment)](https://github.com/ValveSoftware/steam-audio/issues/210#issuecomment-1364141910)
> 
> Thanks! Following this tutorial, I managed to get it to compile. [Here is my compiled version](https://cdn.discordapp.com/attachments/814066163075252230/1056765257344880731/SteamAudio.7z) (place in `UE_5.1\Engine\Plugins\Runtime\Steam`)

Does it actually work properly for you? Whenever I try to play in editor with my version and a SteamAudioSource is active it crashes with an access violation error related to SteamAudioSourceComponent's BeginPlay code.

**Comment by RYRY1002** [comment]
> > > Replying to [#210 (comment)](https://github.com/ValveSoftware/steam-audio/issues/210#issuecomment-1364141910)
> >
> > Thanks! Following this tutorial, I managed to get it to compile. [Here is my compiled version](https://cdn.discordapp.com/attachments/814066163075252230/1056765257344880731/SteamAudio.7z) (place in `UE_5.1\Engine\Plugins\Runtime\Steam`)
> 
> Does it actually work properly for you? Whenever I try to play in editor with my version and a SteamAudioSource is active it crashes with an access violation error related to SteamAudioSourceComponent's BeginPlay code.

Yes, assuming you've configured it correctly, it works just fine for me.

**Comment by devhyper** [comment]
> > > Replying to [#210 (comment)](https://github.com/ValveSoftware/steam-audio/issues/210#issuecomment-1364141910)
> > 
> > 
> > Thanks! Following this tutorial, I managed to get it to compile. [Here is my compiled version](https://cdn.discordapp.com/attachments/814066163075252230/1056765257344880731/SteamAudio.7z) (place in `UE_5.1\Engine\Plugins\Runtime\Steam`)
> 
> Does it actually work properly for you? Whenever I try to play in editor with my version and a SteamAudioSource is active it crashes with an access violation error related to SteamAudioSourceComponent's BeginPlay code.

Send the log and I'll take a look.

**Comment by googleooer** [comment]
> > > > Replying to [#210 (comment)](https://github.com/ValveSoftware/steam-audio/issues/210#issuecomment-1364141910)
> > > 
> > > 
> > > Thanks! Following this tutorial, I managed to get it to compile. [Here is my compiled version](https://cdn.discordapp.com/attachments/814066163075252230/1056765257344880731/SteamAudio.7z) (place in `UE_5.1\Engine\Plugins\Runtime\Steam`)
> > 
> > 
> > Does it actually work properly for you? Whenever I try to play in editor with my version and a SteamAudioSource is active it crashes with an access violation error related to SteamAudioSourceComponent's BeginPlay code.
> 
> Send the log and I'll take a look.

`Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000030

phonon
phonon
phonon
phonon
phonon
phonon
phonon
phonon
phonon
UnrealEditor_SteamAudio!USteamAudioSourceComponent::BeginPlay() [Y:\Unreal Engine\Projects\steamaudiocompile\Plugins\SteamAudio\Source\SteamAudio\Private\SteamAudioSourceComponent.cpp:235]
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_Engine
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor_UnrealEd
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
UnrealEditor
kernel32
ntdll`

**Comment by RoflanTsar** [comment]
What is the point if it doesn't work on 5.0? You cannot even export static geometry. HRTF seems to be broken too. Need to wait for an official release

**Comment by Lexo783** [comment]
Hello !
I try to add Steam audio on my project (Unreal engine 5.0.3) i follow the steps but its not working maybe i miss something si you have a read me with all the steps ?

**Comment by Dylanyz** [comment]
Hi everyone! Just want to share here - it seems that you can just download the latest version of the plugin made for Unreal here: https://valvesoftware.github.io/steam-audio/downloads.html

Then you just 
"Copy the unreal/SteamAudio folder into the Engine/Plugins/Runtime/Steam subfolder of the folder where Unreal Engine has been installed. This will replace the version of Steam Audio bundled with Unreal Engine, and update it to the latest version."

As said in the manual: https://valvesoftware.github.io/steam-audio/doc/unreal/getting-started.html

**Comment by SpaceCraft33** [comment]
> Here is the compiled plugin: [https://github.com/devhyper/steam-audio/releases/download/v4.1.1/steam-audio-package.zip](url)

Any possibility to compile it for 5.1.1 ? Thx

**Comment by devhyper** [comment]
> > Here is the compiled plugin: [https://github.com/devhyper/steam-audio/releases/download/v4.1.1/steam-audio-package.zip](url)
> 
> Any possibility to compile it for 5.1.1 ? Thx

https://github.com/devhyper/steam-audio/releases/download/UE-5.1.1/SteamAudio.zip
@SpaceCraft33

**Comment by SpaceCraft33** [comment]
Thank you @devhyper for the quick answer ! Unfortunatly, just like @RoflanTsar the Export Static Geometry function isn't working.

> LogSteamAudio: Error: No material specified for object.
> LogSteamAudioEditor: Error: Failed to export static geometry for level TestWorld.

I guess an official update might be needed at some point. Too bad ! But still, Thank you.

**Comment by SpaceCraft33** [comment]
Hey @devhyper, Thanks a lot for the compiled Zip file in a record time. Very much appreciated. And thanks again for the tips on the default mesh material !

**Comment by lakulish** [comment]
We have just released v4.1.3: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.3, which includes support for UE 5.0 and 5.1. Note that when you try to open a project with SteamAudio or SteamAudioFMODStudio plugins enabled, Unreal Editor will prompt you to rebuild the plugins. Just click OK/Yes and wait for the build process to finish.
