### ISSUE TITLE
Unity SteamAudio 4.1.1 crashes

### ISSUE THREAD

**Issue by Killers0992** [ValveSoftware/steam-audio#213]
In any scene type editor just crashes while trying to bake

Unity Version 2019.4.31f1

[Editor.log](https://github.com/ValveSoftware/steam-audio/files/9209106/Editor.log)
[error.log](https://github.com/ValveSoftware/steam-audio/files/9209108/error.log)

**Comment by lakulish** [comment]
Could you provide a minimal project in which this issue can be reproduced? Alternatively, could you provide us with the minidump from this crash? Thanks!

**Comment by Killers0992** [comment]
[crash.zip](https://github.com/ValveSoftware/steam-audio/files/9213003/crash.zip)

**Comment by Killers0992** [comment]
Seems like after creating a new project it works somehow, now idk what is wrong in my project

**Comment by Killers0992** [comment]
And this crash happened because of me mixing assets.
