### ISSUE TITLE
iplStaticMeshCreate crash on IPL_SCENETYPE_DEFAULT but not IPL_SCENETYPE_EMBREE, testcase provided

### ISSUE THREAD

**Issue by ogniK5377** [ValveSoftware/steam-audio#216]
When adding specific static meshes on scenes that are of type `IPL_SCENETYPE_DEFAULT` it leads to an access violation on `iplStaticMeshCreate`

The current workaround is to use `IPL_SCENETYPE_EMBREE` to prevent this from happening.
Below I've provided a test binary built in debug mode with an attached pdb
https://github.com/ogniK5377/steamaudio-issue-repro/releases/tag/StaticMeshCrash
The source for the following test case is provided here too
https://github.com/ogniK5377/steamaudio-issue-repro/blob/main/src/StaticMeshCrash/main.cpp

The scene is provided as well as a command line option to only provide a limited subset of triangles up to the crashing triangle of the static mesh

Edit: Looks as if I can reproduce it as well if there are 130 overlapping triangles

**Comment by lakulish** [comment]
Thanks for providing the test cases. We are able to reproduce this issue, and a fix will be included in the next release.

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.2, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2.
