### ISSUE TITLE
PS5 Support

### ISSUE THREAD

**Issue by Scraft** [ValveSoftware/steam-audio#217]
I downloaded the Unity source and was able to add support to the python/CMake system and successfully build a PS5 compatible phonon runtime library, however I this only appears to be the Unity part, the underlying library seems to be supplied as binary only.

Am I missing anything? If the source is available, I would like to use it to make a PS5 dynamic library. If the source isn't available have I reached a deadend? Or does Valve have a PS5 library that they can provide me if I prove my PS5 developer status?

**Comment by Oldnice** [comment]
> Steam Audio supports Windows (32 bit and 64 bit), Linux (32 bit and 64 bit), macOS, and Android (armv7, arm64, x86, x64) platforms.

Source code is available for integration layers (C-API, FMOD, Unity, Unreal), not the underlying (audio implementation) library. It is likely that a PS5 version does not exist.

**Comment by achandak** [comment]
@Scraft - Sent you a note. We have not yet released the C-API source code. You will need to port that to PS5 as well in addition to integration layers for a full PS5 port.
