### ISSUE TITLE
Ambisonics decode effect creation crashes without HRTF

### ISSUE THREAD

**Issue by Oldnice** [ValveSoftware/steam-audio#218]
iplAmbisonicsDecodeEffectCreate crashes if no HRTF is supplied via IPLAmbisonicsDecodeEffectSettings, even if user does not intend to utilize HRTF, but use panning instead. If HRTF is required for panning, and this is working as intended, HRTF should probably be renamed, or at least a mention added to the documentation that a valid HRTF is always required.

**Comment by lakulish** [comment]
We've just release Steam Audio 4.1.2, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2.
