### ISSUE TITLE
Popping Artifact in Unity Plugin with smaller DSP Buffer Size

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#22]
There are popping artifacts when using different DSP Buffer Sizes than Default in Unity. We are able to reproduce the popping for DSP Buffer Size set to Best Latency.

**Comment by achandak** [comment]
Issue seems to be outside Steam Audio Unity plugin and more related to audio driver capabilities to playback with DSP Buffer Size set to Best Latency.

http://steamcommunity.com/app/596420/discussions/0/133261370008671286/

**Comment by achandak** [comment]
Further, C API does not exhibit any popping issue in a standalone application when using buffer sizes equivalent to Best Latency in Unity (256 samples per frame)

**Comment by grrrwaaa** [comment]
Could it be related to #37? I also hear pops with C API iplApplyBinauralEffect() and moving sources if the DSP size is small -- very noticeable at 256 samples, unbearable at 64 samples.
