### ISSUE TITLE
[Unity] Occlusion not working PhysicsScene/Local physics.

### ISSUE THREAD

**Issue by CryptoJanne** [ValveSoftware/steam-audio#220]
Occlusion does not currently work if one is using PhysicsScene.Simulate() to simulate a local physicsscene. 
The issue is that the raycasts which determines occlusion is using Physics.Raycast, which dont work in simulated physics. PhysicsScene.Raycast does.

An option to choose would be nice. In the meantime, im having a hard time tracking down where in the code the rays are being shot. Any help to locate the specific code is greatly appreciated.

**Comment by lakulish** [comment]
The rays are traced in the C# functions `SteamAudioManager.ClosestHit` and `SteamAudioManager.AnyHit`. Let us know if modifying these functions lets you resolve your issue, or if you have any other questions. If you'd like, you can also open a pull request for us to look at.
