### ISSUE TITLE
[Unity] Steam Audio Return does not work in the build (4.1.1)

### ISSUE THREAD

**Issue by DenisSulyagin** [ValveSoftware/steam-audio#223]
It works properly in the editor, after building the build, it takes over the reflections and does not output.

1. Open a project.
2. Press Play
3. Click on the Toggle Steam Reflection
4. Make sure that the reflections are output via Steam Audio Return
5. Build a project
6. Run the build and click on the Steam Reflection switch
7. Make sure that reflections are not output via Steam Audio Return
[TestSteam.zip](https://github.com/ValveSoftware/steam-audio/files/9525985/TestSteam.zip)

**Comment by lakulish** [comment]
We've just released Steam Audio 4.1.2, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2. Try it out, and let us know if the issue persists.

**Comment by DenisSulyagin** [comment]
> We've just released Steam Audio 4.1.2, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.2. Try it out, and let us know if the issue persists.

works in the build
