### ISSUE TITLE
Steam Audio Static Mesh NullReferenceException

### ISSUE THREAD

**Issue by AnonPartyHard** [ValveSoftware/steam-audio#225]
Hello. I am using:
FMOD 2.02.07 (studio and unity)
Steam audio  4.1.1 (unity and FMOD)
Unity 2021.3.8.f1
As I understand to add occlusion i need to add some SteamAudioGeometry in scene and export scene. 
After exporting a game object "Steam Audio Static Mesh" automatically created with SteamAudioStaticMesh component and with asset of exported scene.
In Unity:
![image](https://user-images.githubusercontent.com/103405590/191818424-4dcd13fe-0b87-4aa7-86f0-6fd5f6734e8c.png)
In FMOD:
![image](https://user-images.githubusercontent.com/103405590/191818560-ba999f3f-45a8-4ec5-ba53-52d1b2ea1473.png)

I can hear that spatialize is working, but there is no any occlusions.
Unity console is throwing error in loop:
![image](https://user-images.githubusercontent.com/103405590/191819163-1e5377f1-bba0-4e9d-9fe8-2714eb9c2417.png)

**Comment by AnonPartyHard** [comment]
I also can see the same error if any steam dynamic objects added and exported.
Seems like SteamAudioManager.CurrentScene is always null.

**Comment by Matusson** [comment]
Hi there, I experienced the same issue in #219. Could changing Enter Play Mode Settings in Project Setting help as well, or is this a different issue?
