### ISSUE TITLE
SteamAudioFMODStudio Does not work with UE5!

### ISSUE THREAD

**Issue by worbarry** [ValveSoftware/steam-audio#228]
project wont open with plugin enabled

**Comment by MikeGO2611** [comment]
Same issue, apparently is not compiled for the current version.

**Comment by lakulish** [comment]
We have just released v4.1.3: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.3, which includes support for UE 5.0 and 5.1. Note that when you try to open a project with SteamAudio or SteamAudioFMODStudio plugins enabled, Unreal Editor will prompt you to rebuild the plugins. Just click OK/Yes and wait for the build process to finish.
