### ISSUE TITLE
[Unity] NullReferenceException if `AudioListener` component isn't present when `SteamAudioManager.AutoInitialize` is invoked

### ISSUE THREAD

**Issue by robinnorth** [ValveSoftware/steam-audio#229]
In projects where an `AudioListener` instance is not present until after `SteamAudioManager.AutoInitialize` is invoked on entering play mode/starting the app, [SteamAudioManager.OnSceneLoaded:L399](https://github.com/ValveSoftware/steam-audio/blob/8b08c92c2b9f8ea6afd607ed94d1ec9d3f139fbb/unity/src/project/SteamAudioUnity/Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioManager.cs#L399) will cause a `NullReferenceException` to be thrown, as both `UnityAudioEngineStateHelpers` and `FMODStudioAudioEngineStateHelpers` attempt to return the `Transform` of a found `AudioListener` component without first checking if that component actually exists i.e. is not null.

```
mListener = AudioEngineStateHelpers.Create(SteamAudioSettings.Singleton.audioEngine).GetListenerTransform();
```

This could occur for a number of legitimate architectural reasons, e.g. additively loading a camera rig scene containing an audio listener or instantiating an environment-specific camera rig prefab after the Steam Audio Manager instance has been initialized.

To fix this, I would suggest that implementers of `AudioEngineStateHelpers.GetListenerTransform` should return `null` if an `AudioListener` component is not found, and all usages of `SteamAudioManager.mListener` should also first check if that reference is null before proceeding.

**Comment by lakulish** [comment]
We have just released v4.3.0 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.3.0), which fixes this issue.
