### ISSUE TITLE
Unity crashes on Scene Export when using special charachters in the project path

### ISSUE THREAD

**Issue by vacuum-packed** [ValveSoftware/steam-audio#23]

**Comment by achandak** [comment]
@vacuum-packed  - Can you provide an example?

**Comment by vacuum-packed** [comment]
When the Unity project path has a parent folder with a special character like `C:\ä\ProjectFolder` and you try to `Pre-Export Scene` from the Phonon window the Unity editor crashes

**Comment by achandak** [comment]
Thanks for reporting, confirming that I can reproduce the issue on our end.

**Comment by achandak** [comment]
@vacuum-packed - we have resolved this issue in the latest release for Steam Audio. Here are the release notes - http://steamcommunity.com/games/596420/announcements/detail/1299696599437459444
