### ISSUE TITLE
FMOD Integration plugin interface doesn't look right

### ISSUE THREAD

**Issue by MikeGO2611** [ValveSoftware/steam-audio#233]
In the SteamAudio FMOD Integration spatializer reference wiki, the Spatializer looks like this:
![image](https://user-images.githubusercontent.com/9802509/208776942-d3a7e625-1436-490d-bcf5-ac5d252f0f97.png)

But on my FMOD project, it looks like the following (without the curves of attenuation nor directionality):

![image](https://user-images.githubusercontent.com/9802509/208776850-f32dc70e-44dc-48ff-ac9a-b03028dec934.png)

I've followed the FMOD plugin guide in the wiki (copying the win64 lib .dll into my Plugins folder in the FMOD project), and I don't think is not installed because it works, it just has a different UI, one that seemengly seems less intuitive and doesn't let me edit the curves.

**Comment by dpiltzVFS** [comment]
I solved this issue by putting the phonon_fmod.plugin.js JavaScript File into the FMOD plugins folder

**Comment by MikeGO2611** [comment]
> i

Thank you! That fixed it. I thought the .js it was only used for custom implementations.
