### ISSUE TITLE
Audio Occlusion is too abrupt & missing default HRTF

### ISSUE THREAD

**Issue by jnbbender** [ValveSoftware/steam-audio#236]
I've got audio occlusion working with different materials but when I transition behind a wall, let's say, the audio immediately cuts down to the occluded value.  Is there a way to Lerp to the new Audio Occluded value?

Also, when running the application I get the following error:
`Unable` to load HRTF: D:/Unity/Projects/Sci-Fi-2022/Assets/StreamingAssets\.sofa.
UnityEngine.Debug:LogError (object)`

I was under the impression that adding a sofa file was for custom configuration.  Not a requirement.

**Comment by Oldnice** [comment]
Assuming the Unity integration supports this (and I don't see why it wouldn't): have you tried settings the occlusion type to volumetric, and modifying the occlusion sample count & radius? This should allow your virtual head to sample bigger radius, with partial audio occlusion.

**Comment by achandak** [comment]
What does your Steam Audio Settings look like? Make sure [SOFA files](https://valvesoftware.github.io/steam-audio/doc/unity/guide.html#use-a-custom-hrtf) count is set to 0 or if it is non-zero it is pointing to valid sofa files.
