### ISSUE TITLE
[Unity] Released Linux libaudioplugin_phonon.so Missing iplUnityAddSource

### ISSUE THREAD

**Issue by summerblind** [ValveSoftware/steam-audio#242]
I was receiving an error related to an EntryPointException when trying to run the provided 4.1.2 package in Unity on Linux. This occurred if I tried to run a scene with a Steam Audio Source component instantiated. I grep'd through the release tarball for the symbol and found it in the Windows, Android, and MacOS releases but not Linux. I built the library manually from this repo and it did indeed contain the symbol, so I replaced the deployed library in my Unity project's assets and restarted Unity to get it to load the updated library. Things work now, but I suspect there's an issue with the packaging methodology for official releases.

**Comment by Schroedingers-Cat** [comment]
I can confirm everything you wrote.  
Had to install python2 which the doc just calls `python` and run all commands declared as `python` in the doc as `python2`.

**Comment by summerblind** [comment]
Yeah I noticed it was all geared towards python2 as well, I decided to locally mod it into python3 which wasn't too bad.

**Comment by lakulish** [comment]
I double-checked the symbols exported from `libaudioplugin_phonon.so`, both in the `lib/` subdirectory in the zip file, and in `SteamAudioUnity.unitypackage`, and both the 32-bit and 64-bit versions contain the `iplUnityAddSource` function. Can you point me to the exact location of the file which is missing the symbol?

Also, can you try deleting the `Assets/Plugins/SteamAudio/Binaries` subdirectory of your Unity project (making sure Unity is closed first), and re-importing `SteamAudio.unitypackage`?

Thanks!

**Comment by summerblind** [comment]
I deleted the Binaries directory and reimported the SteamAudioUnity.unitypackage. I now get the following error again:
`EntryPointNotFoundException: iplUnityAddSource assembly:<unknown assembly> type:<unknown type> member:(null)
SteamAudio.UnityAudioEngineSource.Initialize (UnityEngine.GameObject gameObject) (at Assets/Plugins/SteamAudio/Scripts/Runtime/UnityAudioEngineSource.cs:24)
SteamAudio.SteamAudioSource.Awake () (at Assets/Plugins/SteamAudio/Scripts/Runtime/SteamAudioSource.cs:162)

`
I navigated to the Binaries folder of the extracted Unity package. Running nm -gD to list the symbols shows iplUnityAddSource in the Android/x86 libaudioplugin_phonon.so but not in Linux/x86_64:
` nm -gD Android/x86/libaudioplugin_phonon.so | grep iplUnityAdd
00029c40 T iplUnityAddSource
 nm -gD Linux/x86_64/libaudioplugin_phonon.so | grep iplUnityAdd
`

Some notes: 
OS: I use Arch, btw (not Ubuntu but I figure it's valid since SteamOS is Arch-based)
Unity version 2021.3.18f1 LTS Linux
steam-audio Unity version 4.1.2

**Comment by lakulish** [comment]
My mistake, I was looking at the `libaudioplugin_phonon.so` built on a different branch. I can confirm that the file included in v4.1.2 does not contain `iplUnityAddSource`. This will be fixed in the next release.

**Comment by lakulish** [comment]
We have just released v4.1.3: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.1.3, which should contain a fix for this issue.

**Comment by Schroedingers-Cat** [comment]
Can confirm it's working fine now on Linux without any changes necessary. Thanks a lot!
