### ISSUE TITLE
[Unity] Steam Audio not running on Apple Silicon Macs

### ISSUE THREAD

**Issue by anilcamci** [ValveSoftware/steam-audio#246]
Hi all, 

I left a post about this on the Steam Audio forum as well, but I thought I would follow up here with more detail in case it helps with resolving the issue more quickly. Here are the errors I am getting when I import the Steam Audio 4.1.3 package into Unity on an M1 Max MacBook Pro running macOS 13.2: 

Plugins: Couldn't open /Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, error: dlopen(/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, 0x0002): tried: '/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file), '/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Plugins: Couldn't open Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, error: dlopen(Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon, 0x0002): tried: 'Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OSAssets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file), '/Applications/Unity/Hub/Editor/2021.3.8f1/Unity.app/Contents/Frameworks/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file), '/Applications/Unity/Hub/Editor/2021.3.8f1/Unity.app/Contents/Frameworks/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file), '/usr/lib/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file, not in dyld cache), 'Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (no such file), '/Users/---/Desktop/Steam Test/Assets/Plugins/SteamAudio/Binaries/macOS/audioplugin_phonon.bundle/Contents/MacOS/audioplugin_phonon' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

Thanks for your help with this!

**Comment by kisak-valve** [comment]
Hello @anilcamci, this issue is already being tracked at #186. Closing as a duplicate.
