### ISSUE TITLE
Difference on the acoustics when changing materials?

### ISSUE THREAD

**Issue by ariadnasc** [ValveSoftware/steam-audio#25]
Hi all,

I don't know if it is just me, but I cannot find a proper difference in the room acoustics when changing materials. For example, metallic materials should turn to a more reverberant environment because the attenuation rate is lower; with carpet material, the other way around.
I have also tried the Custom material and, in my opinion, I can't see a difference.

Am I doing something wrong? Because that is not working for me. 

Thank you!

**Comment by wderstine** [comment]
Did you pre-export and generate the probes after making the changes?

**Comment by ariadnasc** [comment]
I pre-exported the scene. I haven't generate the probes, I thought it didn't matter if I was using Real-time?

**Comment by Luux** [comment]
We are working on a small project with 4 people and have the same issue. Sometimes changes to materials etc. seem to be ignored by steam audio (e.g. I couldn't hear a source as soon as it's around a corner even when I set up the scene for maximum reverb...)

One time it worked for me when I used git clean directly after I pulled changes from github, but another project member reported that he tried that and still has the problem.

Maybe some temporary/cached files aren't overwritten and are still reused every time?

**Comment by Luux** [comment]
Update: For him worked "git clean -fx", too. Maybe this can be a workaround for @ariadnasc if the issue has the same cause. (Or if he doesn't use git: cleaning all unity-generated temporary files in the project directory)

**Comment by wderstine** [comment]
Yeah, you're right about the probes. After pre-exporting it on mine it seemed to work just fine between carpet and concrete. It echoed for concrete, and was pretty dry on carpet. Do you have your reverb enabled on your listener?

**Comment by wderstine** [comment]
@ariadnasc Oh yeah real-time you don't need the probes. How complex is your scene? Is all of your geometry the same material in the space?

**Comment by ariadnasc** [comment]
@Luux I tried doing that but it still doesn't work. I have also tried with different audios but nothing seems to change.

@wderstine right now I am testing with a simple room made of cubes, and a wall in the middle (another cube) to test the occlusion. And yeah, I am trying Custom material, changing the absorptions to see if there is any difference... but still none.

**Comment by Luux** [comment]
Did you use the git command or did you delete the files manually? If case 1: did you use a .gitignore for unity (like https://github.com/github/gitignore/blob/master/Unity.gitignore)? 

(Just in case: did you add the Phonon Listener script and set it to realtime, too?)

**Comment by ariadnasc** [comment]
@Luux I erased them manually because I am not using git.
I have the Phonon Listener added in an FPS Controller. I have the Real time reverb selected.

**Comment by wderstine** [comment]
Is your geometry script attached to a parent of all of your cubes with export all children checked?

Btw which version of Steam Audio do you have? I just recently had to update to the 2.0-beta.4 release from .2 because I was having some issues and it seemed to help. Although, I have the .1 release on another comp and it was working fine.  I don't know if it'll help or not.

**Comment by ariadnasc** [comment]
@wderstine All my cubes are attached to the same parent, yes. And I have that option checked. I really think I am not missing anything, I followed the manual step by step.

I started testing Steam Audio 2 or 3 days ago so I have the 2.0-beta.4 as well.

**Comment by ariadnasc** [comment]
I am using Unity on a OSX, I don't know if that changes anything or there are some incompatibility problems? My Unity is 5.5.2f1 free version.

**Comment by wderstine** [comment]
Yeah, I'm always forgetting little things like that so I just try to double check. I'm on a PC so if there is some issue with Mac then I won't be able to help. I'm gonna keep looking into it and see if I find anything that isn't OS related.

**Comment by lakulish** [comment]
@ariadnasc Does increasing the Indirect Mix Fraction on the Phonon Listener help? We're also trying to reproduce the issue, and to figure out if this is a macOS-specific thing or not.

**Comment by ariadnasc** [comment]
@lakulish have you found out if it is an macOS thing? 
However, I am going to try to increase that parameter this afternoon and I'd let you know if that helps.

**Comment by ariadnasc** [comment]
@lakulish I have increased the Reverb Mix Fraction (I couldn't find the Indirect Mix Fraction in my Phonon Listener) and I don't appreciate any difference. I used a custom material with all the absorption parameters to 0 and another with all of them to 1. I also tried with Wood and Metal but no difference

**Comment by lakulish** [comment]
@ariadnasc I haven't been able to reproduce this on macOS. I tried a custom material with all parameters set to 0, followed by all parameters set to 1, and things seem to be working fine. Can you confirm whether you're pre-exporting the scene after changing the materials?

**Comment by ariadnasc** [comment]
@lakulish yes, I am pre-exporting the scene after changing the materials.

**Comment by lakulish** [comment]
@ariadnasc Can you try deleting the .phononscene file (which is created under Assets/StreamingAssets) and pre-exporting again? Also, are you modifying the default material, or a material component attached some geometry? If the latter, are you modifying the materials for all geometry that has a material component?

**Comment by ariadnasc** [comment]
@lakulish I deleted the .phononscene file but still the same.
I have a room made with cube geometry and a wall, all of them linked to an Empty GameObject (which is the parent). I clicked on Export all children. All materials are the same for all the different walls of the room.

**Comment by achandak** [comment]
@ariadnasc Can you try the following scenario?

Remove Phonon Material from all children object and use global material to change material settings. Pre-export scene. Does that change reverb, now?

There is currently a bug we are fixing when material is attached to children objects. Basically, either just use global material or do not use Export All Children option until we provide a fix.

**Comment by ariadnasc** [comment]
@achandak I have already just one material in the parent object (not in the childrens), and the reverb does not change.
If I unselect the Export All Children option it doesn't work because then Vertices and Triangles are 0.

Am I understanding it wrong?

**Comment by achandak** [comment]
@ariadnasc - No, your response is fine. Do the following then.

- Select Export All Children.
- Remove Phonon Material from the GameObject with Phonon Geometry. (now, only Global Material is used, see Window > Phonon for Global Material settings).
- Change the Global Material and pre-export scene. Change it again to see if reverb changes.

**Comment by ariadnasc** [comment]
@achandak I just did that, and used Custom reverb (one set to 0 and another set to 1) and it's just the same. It is very weird. I would try it on a windows PC to see if it works, but I don't have any.

**Comment by achandak** [comment]
@ariadnasc - At this time, we do not have any more ideas on what might be going on. Our next update will be out next week, try it out and see if that fixes your issue.

If you continue to face the same issue and are willing to share a project where we can reproduce the issue, we can look into that further.

**Comment by ariadnasc** [comment]
@achandak That's fine, thank you very much. 

If the problem persists, I will upload a sample project so you can reproduce the issue.

**Comment by achandak** [comment]
@ariadnasc - We have fixed issue with materials on macOS. This was a problem on other platforms as well, but may not manifest itself depending on how your scene geometry is organized.

See release notes [here](http://steamcommunity.com/games/596420/announcements/detail/1263670339945800564).
