### ISSUE TITLE
No Reverb and other issues after compiling apk for Android

### ISSUE THREAD

**Issue by Luux** [ValveSoftware/steam-audio#26]
As soon after I create an apk for Android, only the occlusion continues to work. Any reverb/material settings and so on just stop working. This affects the android application as well as the editor.

After I compiled the apk, I only can clean all of unity's temporary files via git clean -fx or make a compile a build for windows to get it working in the editor again. But that doesn't solve the problem that I can't use Steam Audio on Android properly.

**Comment by achandak** [comment]
@Luux - Steam Audio on Android only supports HRTF based audio rendering and direct sound occlusion features. Other parts are compute intensive and currently not supported on Android.

We will try to reproduce the issue with Editor after building APK.

**Comment by Luux** [comment]
Shouldn't recent Android Devices be beefy enough to compute the baked reverb? I mean, even my 10 year-old notebook was able to handle our realtime test scenes (but I don't want to bake anything on that, that takes years... ;))

We wanted to do a small project with mobile gyroscope controls, focusing on the 3D audio, that's why I'm asking.

**Comment by achandak** [comment]
@Luux - You should be able to do at least HRTF-based spatial audio + occlusion.

Enabling physics-based propagation and reverb stuff on Android is something we plan to work on but do not have any definitive timeline for that, sorry about that.

**Comment by ariadnasc** [comment]
@achandak is the material reverb working for Unity in OSX? Because it doesn't work and I literally don't know why.

**Comment by achandak** [comment]
@Luux - We looked into the issue you reported on Android. 
Once you build an APK, platform is switched to Android for the Editor. Since, reverb is not supported on Android, you don't hear reverb in Editor now.
If you switch the platform again to PC, you should start hearing reverb again.

**Comment by wickerman123** [comment]
So it's been 2 years now, is this possible? I'm using the UE4 plugin and there's no way to assign Steam Audio as the reverb plugin.
