### ISSUE TITLE
No audio in FMOD Studio when 'Apply HRTF to direct' enabled, in v4.2

### ISSUE THREAD

**Issue by EdwinGray** [ValveSoftware/steam-audio#260]
As the title suggests, when adding the Spatializer to a track in FMOD Studio then you get no sound from that track, unless Apply HRTF is deselected. 

This was working fine in 4.1

**Comment by lakulish** [comment]
We have just released v4.4.0, which contains a fix for this issue: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.4.0.
