### ISSUE TITLE
[Unity] High memory usage. Memory leak

### ISSUE THREAD

**Issue by Murram9** [ValveSoftware/steam-audio#262]
When entering playmode in unity steam audio spikes up an insane memory usage (20+ gb). Memory does not go away when exiting playmode. Memory keeps stacking as you continue entering playmode. Makes using Unity a nightmare.

**Comment by achandak** [comment]
Can you describe a little bit more about how you are using Steam Audio? In particular, your Steam Audio Settings and what features / components you are using?

**Comment by Murram9** [comment]
I am using steam audio sources with reflections and occlusion. Just walls, gaps, and doors have audio geometry. Only doors have dynamic geometry. I have steam audio settings set to lowest right now but that does not seem to make a difference. I had set all audio sources (333) to have a steam audio source. I know not every object should have this component but that still causes a massive increase in ram usage that does not clear when exiting playmode. When removing the steam audio source components the amount of ram increase in significantly lower. I am not using any baked audio sources right now though i found that did not increase memory usage. I have no probe batches, ambisonic sources or files, baked listeners, or static meshes. My main camera has a baked listener and baked source. Changing the ray tracer settings has no effect though i am currently using embree. Reflection effect settings is set to convolution.

**Comment by achandak** [comment]
Thanks for the info. What version of Steam Audio are you using? Are all the sources active at the same time? Also, do you have any effects on mixers in Unity?

We will try to repro this on a simple scene with large number of sources. If you have something reproable, feel free to send our way.

**Comment by Murram9** [comment]
It is unity version 2022.2.11 and steam audio version 4.2.0. All of the sources are enabled but not playing. I have no effects on mixers. The leak only affects the editor but not build. 
Here is the steps I took to get the results in my specific case <html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-5438b2d0-7fff-028b-2dbe-fa719f8f69f1"><div dir="ltr" style="margin-left:0pt;" align="left">

Step | Memory
-- | --
Pre Steam Audio | Normal
Imported | 100 MB increase, builds up slightly
Listener + Baked Listener | No effect
Steam audio geometry | 2,000 MB increase + 100 MB every enter playmode
Add audio mixer | No effect
Set spatializer plugins to steam audio | No effect
Set audio sources to spatialize | Slight increase in memory buildup
Add steam audio source to audio sources (333) | 2000 MB increase in Memory every enter playmode
Remove steam audio source to test if problem persists | Problem goes away when removing steam audio sources
Keep steam audio sources removed for now |  
Add steam audio dynamic geometry | No effect
Export Active Scene | No effect
Bake Listeners | No effect
Add steam audio sources (333) | 2000 MB increase is Memory every enter playmode

</div></b>
</body>
</html>

**Comment by jeremymetzler** [comment]
steam audio 4.1.1 seems to not have this issue, at least for me.

**Comment by achandak** [comment]
Confirming memory leak issue in Steam Audio 4.2. We are looking into it and fix will be out in next update.

**Comment by lakulish** [comment]
We have just released v4.3.0 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.3.0), which fixes this issue.
