### ISSUE TITLE
Steam Audio attenuation issue in animation. Crash

### ISSUE THREAD

**Issue by Denis-Semenovykh** [ValveSoftware/steam-audio#264]
Hello! Unreal Engine 5.1.1 ... I have a problem when working in animations, for example I add sounds of steps through Playsound. When switching the sound attenuation to Binural and specifying Steam Audio in Spatialization plugin settings, the sound disappears and the editor crashes. What can be the problem? 
![image](https://github.com/ValveSoftware/steam-audio/assets/90043919/9f2ab66a-87e5-48c9-8686-f3686f0845cb)

**Comment by Denis-Semenovykh** [comment]
I found the cause of the problem. It happens if the metasounds in mono, and in the game mode all is normal, but in the mode of work with animation, it crash editor. It should switch the used metasounds in stereo, the sound appears and everything is fine. I think it's a bug....Is there any documentation for UE 5? You have on the official resource outdated only for UE4, which is not very good.

**Comment by lakulish** [comment]
We have recently released Steam Audio 4.4.1 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.4.1), which fixes an issue with real-time audio in the Unreal editor. Could you check if this fix resolves your issue? Thanks!

**Comment by kisak-valve** [comment]
Closing pending feedback.
