### ISSUE TITLE
[UE5.2, FMOD] Pathing crashes editor

### ISSUE THREAD

**Issue by sociofall** [ValveSoftware/steam-audio#265]
To reproduce this issue, create a new blueprint with an audio source and insert a Steam Audio component into it. Bake reflections with probes and set them up so that our Steam Audio source uses pathing. Now, place it on the map in a way that there is an obstacle between the source and the listener (wall, for example). Click play and enjoy the crash, that only happens in editor. If you'll launch it standalone - there won't be any crash. 
I don't think FMOD plays any role here, but i'll mention i use it.

**Comment by lakulish** [comment]
Can you provide more details on how your project is set up? In particular:

* In the blueprint, do you have Unreal's built-in Audio component, or FMOD Studio's FMODAudio component?
* Do you bake pathing information in the probe batch? You mentioned that you've baked reflections, but this is a different feature from pathing.

If you can share a minimal project that reproduces this issue, that would be ideal. Alternatively, screenshots of how your actors and components are configured might also be helpful for us to diagnose the issue.

**Comment by sociofall** [comment]
Can't reproduce it myself now, topic can be closed.

**Comment by sociofall** [comment]
Was too fast to close the topic...  Got this crash. To reproduce:
1) Drag'n'drop any Fmod event from content browser to the scene.
![изображение](https://github.com/ValveSoftware/steam-audio/assets/67294769/75cdc2a7-3970-478d-a059-5e3edeb361fb)

2) Add steam source component to it:
![изображение](https://github.com/ValveSoftware/steam-audio/assets/67294769/8acc6156-d556-4233-a166-cad4d74b1f63)

3) Enable pathing and link it to probe batch.
![изображение](https://github.com/ValveSoftware/steam-audio/assets/67294769/eecca8ad-255c-47c9-be4f-1d27d90306fb)

4) Click the blueprint convert button here:
![изображение](https://github.com/ValveSoftware/steam-audio/assets/67294769/dd0b6f94-04a6-4a38-96a5-94099c033c38)

5) Click select and save new blueprint.
![изображение](https://github.com/ValveSoftware/steam-audio/assets/67294769/2c4192db-d39e-4734-bec3-d75083fe75c3)

6) Drag it to the scene and click play (in editor).

Minimal project attached. Just skip dlss plugins check and click play to get crash: 
https://pixeldrain.com/u/HzVADxhV - Unreal project
https://pixeldrain.com/u/ephmcZq5 - Fmod project
