### ISSUE TITLE
"Failed to export static geometry" for Lyra maps in Unreal Engine 5

### ISSUE THREAD

**Issue by maxjaudio** [ValveSoftware/steam-audio#266]
Steam Audio ver. 4.2.0, Unreal Engine 5.0.3, Windows 11

When trying to export the static geometry I've tagged in the L_Expanse and L_Convolution_Blockout maps, I get an error message that says "LogSteamAudioEditor: Error: Failed to export static geometry for level [level name here]".

I did not receive this error when I exported the static geometry for the "L_ShooterGym" map. Is there any way to debug what exactly is causing the exports to fail?

**Comment by lakulish** [comment]
It looks like L_Expanse, at least, has a few static mesh actors that don't have valid static meshes set:

```
BakedStaticMeshActor_C_UAID_E04F43E623D4FAF700_1889961872
BakedStaticMeshActor_C_UAID_E04F43E623D4FAF700_1889911736
BakedStaticMeshActor_C_UAID_E04F43E623D4EED000_1249883444
BakedStaticMeshActor_C_UAID_E04F43E623D4A5F700_1120294702
BakedStaticMeshActor_C_UAID_E04F43E623D4FAF700_1889602990
BakedStaticMeshActor_C_UAID_E04F43E623D4A4F700_2095665523
```

Not sure if this is intended behavior, or a bug in the L_Expanse map.

**Comment by AndreWuuu** [comment]
Have you solved this problem?

**Comment by maxjaudio** [comment]
I was not able to solve this problem in either the original combo of UE5.0.3 + SA4.2.0 nor the most up-to-date combo of UE5.4.2 + SA4.5.3. Regardless, I'm closing as in not planned because it seems that, whether intentional or not, this is an issue with how Epic made a map with static mesh actors that didn't have valid static meshes set, not an issue on Valve/Steam Audio's end.
