### ISSUE TITLE
IPLSimulationSettings::maxConvolutionSources severely impacts performance

### ISSUE THREAD

**Issue by Slin** [ValveSoftware/steam-audio#27]
I have been trying to figure out how many sources with convolution could be in a scene and how many with only the direct sound and so on. I noticed that even if there is no convolution effect at all, the maxConvolutionSources value has a big impact on the execution speed of iplGetMixedEnvironmentalAudio. It is fast when set to 0 or 1 or even 5, but higher than that I start getting a lot of cracking independently of the actual number of convolution effects in use.

I would expect this setting to only effect memory consumption (since you need memory for each source to store the samples for a time of irDuration or something like that) and not the speed.

If for some internal reason, this is to be expected, you should mention it in the documentation.

**Comment by lakulish** [comment]
Can you share the relevant portions of code where you're setting up the simulation and rendering settings, and where you're creating and using the Environmental Renderer and Convolution Effect objects? We're trying to reproduce this on our end, and we want to be sure we're testing the same sequence of operations as you have.

Your expectation is correct: the value of maxConvolutionSources should only affect memory consumption, not speed.

**Comment by Slin** [comment]
After some more investigating it appears that it is mainly caused by not having any convolution effects with the following setup:

This is the rendering setup:
`
		_internals->context.allocateCallback = nullptr;
		_internals->context.freeCallback = nullptr;
		_internals->context.logCallback = nullptr;

		_internals->settings.samplingRate = 44100;
		_internals->settings.frameSize = 512;
		_internals->settings.convolutionType = IPL_CONVOLUTIONTYPE_PHONON;

		IPLHrtfParams hrtfParams{IPL_HRTFDATABASETYPE_DEFAULT, nullptr, 0, nullptr, nullptr};
		iplCreateBinauralRenderer(_internals->context, _internals->settings, hrtfParams, &_binauralRenderer);
`


This is the environment and environmental renderer part, scene can be a valid scene or nullptr:

`
		IPLSimulationSettings simulationSettings;
		simulationSettings.ambisonicsOrder = 3;
		simulationSettings.irDuration = 0.5f;
		simulationSettings.maxConvolutionSources = 20;
		simulationSettings.numBounces = 16;
		simulationSettings.numDiffuseSamples = 512;
		simulationSettings.numRays = 64000;
		simulationSettings.sceneType = IPL_SCENETYPE_PHONON;

		iplCreateEnvironment(_internals->context, nullptr, simulationSettings, _scene, nullptr, &_environment);	//TODO: 4th paramter should be a scene object for indirect sound modeling
		iplCreateEnvironmentalRenderer(_internals->context, _environment, _internals->settings, _internals->internalAmbisonicsFormat, &_environmentalRenderer);
`


Then I have a callback calling iplGetMixedEnvironmentalAudio every audio frame:
`
		iplGetMixedEnvironmentalAudio(_instance->GetEnvironmentalRenderer(),
				IPLVector3{ listenerPosition.x, listenerPosition.y, listenerPosition.z },
				IPLVector3{ listenerForward.x, listenerForward.y, listenerForward.z },
				IPLVector3{ listenerUp.x, listenerUp.y, listenerUp.z }, mixingBuffer[1]);
`

In this order, this is all that is needed to make it slow. Setting maxConvolutionSources to 0 or another low value makes it fast/better.

Once there is a convolution effect, a value of 20 is not a problem anymore. Setting it to higher numbers like 100 or more will introduce cracking again.

**Comment by lakulish** [comment]
@Slin Ah, got it. Not creating convolution effects results in an unexpected performance hit. We have been able to reproduce this issue, and will be working on a fix. Thanks!

**Comment by kisak-valve** [comment]
Closing per "Fixed potential performance issue when using Convolution Effects with custom memory allocator callbacks." in the [2.0-beta.5](https://github.com/ValveSoftware/steam-audio/releases/tag/v2.0-beta.5) release notes.
