### ISSUE TITLE
Dynamic objects with materials?

### ISSUE THREAD

**Issue by ReaLadge** [ValveSoftware/steam-audio#270]
Been experimenting with dynamic objects and it seems that the object completely occludes whatever sound is behind it even if you put a geometry component on there as well; which I assume static geometry steam components wont work with moveable objects. Just wondering if there is any way to have dynamic and have materials along with it, if not I would love a implementation of so.

**Comment by achandak** [comment]
Did you put any Steam Audio Material on the dynamic object? If so, can you share the settings. Also, did you enable transmission under [Occlusion Settings](https://valvesoftware.github.io/steam-audio/doc/unity/source.html?highlight=transmission)? 

If you have any reproducible self-contained project feel free to share.

**Comment by ReaLadge** [comment]
I should of mentioned I'm using Unreal Engine 5.2 sorry. Yeah I do have transmission enabled. The dynamic object works fine itself like it occludes fine but the object fully blocks the sound completely and putting material components on it doesn't seem to work.

**Comment by ReaLadge** [comment]
Oh I know why it's not working. I have to keep exporting dynamic object in the actor details even when changing material settings.
