### ISSUE TITLE
Possible problem with the official example

### ISSUE THREAD

**Issue by rogerlasch** [ValveSoftware/steam-audio#271]
Hello!
I'm new to Steam Audio and I have a question about the official example on this page:
[](https://valvesoftware.github.io/steam-audio/doc/capi/getting-started.html)
I followed the recommendations, imported an audio, converted it to mono, and saved it with the following options:

- Type: Uncompressed Other Files;
- Header: RAW (header-less)
- Encoding: 32-bit float

I also imported this audio to test and was able to hear the sound without any problems.

Then, I copied the code from the example above and compiled it.
After that, I ran the application, and it generated the output file for me. I then tried to play it in Audacity.
However, whenever I hit play, I don't hear anything, no sound at all. Was this the expected outcome?
This has really left me quite confused.
I compiled using Visual Studio 2022 on Windows 11.

**Comment by dawgcodes** [comment]
Hello I think maybe you have to update Visual Studio if it doesn't work please write me thank you

**Comment by rogerlasch** [comment]
Hi, your tip didn't work.

Below I leave the versions of the software I'm using and the step by step of how I'm 
testing it.

Microsoft Windows 11 Home Single Language
Version 22H2 (Operating System Compilation 22621.2134)

Build tools:

** Visual Studio 2022 Developer Command Prompt v17.7.2

SteamAudio 4.4.0

Steps to reproduce the problem:

Download the compiled binaries from:
[](https://github.com/ValveSoftware/steam-audio/releases/download/v4.4.0/steamaudio_4.4.0.zip)

Open Audacity and import any sound. For this example, I used the sound:
"C:\windows\media\Alarm01.wav"

- Select the imported audio by clicking on the Selection menu (may be a little different since I use Audacity in another language.)
- 
- In the tracks menu, select the option "Change sampling point" and select the option 44100

- Again in the tracks menu, open the submenu mix, and select the option "Mix Stereo to Mono"

- Now, file menu, export, and "export audio as"

- Name: "inputaudio"
- Type: Other uncompressed files
- Header: RAW (header-less)
- Codification: 32-bit float

Save the file, and adjust the name to "inputaudio.raw" if necessary...

Now, in the root of the steamaudio folder create the code file "main.cpp"
Inside it, copy the full code of the official example at:
[](https://valvesoftware.github.io/steam-audio/doc/capi/getting-started.html)

- Open Visual Studio Developer Tools prompt...
- "Start menu, All programs, visual studio 2022"
- "x64 Native Tools Command Prompt for VS 2022 "

It may vary depending on the version...
When opened, something like this should appear:

"
**********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.7.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
"

Now navigate to the steamaudio folder with the cd command...
In my case until "downloads\steamaudio"

Compile the program with the following commands:


- "cl /nologo /EHsc /c /std:c++latest /I "include" main.cpp"
- "link /nologo /INCREMENTAL:NO /out:"main.exe" /LIBPATH:"lib/windows-x64" /MACHINE:X64 /MANIFEST:NO main.obj  phonon.lib"

- copy "phonon.dll" to the same folder as "main.exe"

- Run "main.exe"

In audacity, go to the file menu, import, and "import audio without formatting 
(RAW)"

Configure import properties for


- Codification: 32-bit float
- Channels: Mono
- Rat: 44100

When the import is finished, and you press play, no sound will be heard.

Thank you!

**Comment by lakulish** [comment]
This is indeed a bug in the sample code. The fix involves replacing:

```
    IPLHRTFSettings hrtfSettings;
    hrtfSettings.type = IPL_HRTFTYPE_DEFAULT;
```

with:

```
    IPLHRTFSettings hrtfSettings{};
    hrtfSettings.type = IPL_HRTFTYPE_DEFAULT;
    hrtfSettings.volume = 1.0f;
```

in `main`. Let us know if this fixes the issue.

**Comment by rogerlasch** [comment]
Hi!
That was exactly what was missing. Now it works correctly and as expected.
Thank you!
