### ISSUE TITLE
Crashing on Nintendo Switch (Unity) - DllNotFoundException

### ISSUE THREAD

**Issue by 3ternal** [ValveSoftware/steam-audio#277]
Does Steam Audio support the Nintendo Switch? If not, is there any way to disable it per-platform?

I'm encountering the error `DllNotFoundException: Unable to load DLL 'phonon'.` at application launch. The stacktrace originates from `SteamAudio.SteamAudioManager.OnApplicationStart`.

I don't see a folder for the Switch under SteamAudio/Binaries, so I'm guessing that it isn't supported. But I also don't see a way to situationally disable the plugin on unsupported platforms.

**Comment by 3ternal** [comment]
Problem semi-resolved - I don't think Unity has a built-in solution for excluding folders from certain builds, but this asset provides that functionality: https://assetstore.unity.com/packages/tools/utilities/exclude-from-build-222791

More details here: https://forum.unity.com/threads/excluding-folders-from-build.408375/

**Comment by lakulish** [comment]
We have just released Steam Audio v4.4.1 (https://github.com/ValveSoftware/steam-audio/releases/tag/v4.4.1), which contains a fix for this issue. The Steam Audio C# assembly is disabled on unsupported platforms, and a new C# compiler define (`STEAMAUDIO_ENABLED`) can be used to conditionally compile out calls to Steam Audio in your own scripts.
