### ISSUE TITLE
(Unity) Steam Audio Probe Batch cause unity to crash

### ISSUE THREAD

**Issue by Zombie1111** [ValveSoftware/steam-audio#285]
**System Information**
Steam Audio version: 4.4.0 (Unity)
Unity version: 2021.2.0f1 (Also tested in 2021.3.29f1)
Operating System and version: Windows 10

**Issue Description**
Pressing the Generate Probes button on a Steam Audio Probe Batch script causes unity to crash. Enabling Pathing on a Steam Audio Source and assigning the Prove Batch script causes unity to crash when entering playmode.
Crashes if Export Settings Asset is null or assigned on the Probe Batch Script.

I expect it to generate the probes

**Steps To Reproduce**
1: Create a new project in 2021.2.0f1 and import Steam Audio Unity 4.4.0
2: Create a few cubes
3: Create a empty parent for the cubes, add Steam Audio Geometry and set Export All Children to true
4: Steam Audio -> Export Active Scene
5: Create empty object, add Steam Audio Probe Batch script and assign the Export Settings Asset with the exported geometry
6: Press the Generate Probes button and unity crashes
7: Create a Steam Audio Source, enable Pathning and assign the Pathning Prove Batch
8: Enter playmode and unity crashes

**Crash Dump**
[crash.dmp](https://github.com/ValveSoftware/steam-audio/files/13252808/crash.dmp)
[Editor.log](https://github.com/ValveSoftware/steam-audio/files/13252809/Editor.log)

**Comment by achandak** [comment]
Okay, here is the issue.

- In Step 5, do not assign anything in Export Settings: Asset. This Asset is automatically generated by Steam Audio. [Documentation here](https://valvesoftware.github.io/steam-audio/doc/unity/probe-batch.html).

So, if you Export Active Scene and make sure Export Settings: Asset is set to None before you hit Generate Probes, everything should work.

**Comment by Zombie1111** [comment]
> Okay, here is the issue.
> 
> * In Step 5, do not assign anything in Export Settings: Asset. This Asset is automatically generated by Steam Audio. [Documentation here](https://valvesoftware.github.io/steam-audio/doc/unity/probe-batch.html).
> 
> So, if you Export Active Scene and make sure Export Settings: Asset is set to None before you hit Generate Probes, everything should work.

Did not know that but as I said "Crashes if Export Settings Asset is null or assigned on the Probe Batch Script." so I have already tried not assigning it but it still crashes.
