### ISSUE TITLE
Steam Audio Plugin is not working with Unreal Engine 5.3.1

### ISSUE THREAD

**Issue by zsomborbencsik** [ValveSoftware/steam-audio#286]
**System Information**
Please provide the following information about your system:
- Steam Audio version:  4.4.1
- (If applicable) Unity version:
- (If applicable) Unreal Engine version: 5.3.1
- (If applicable) FMOD Studio version:
- Operating System and version: Win11
- (Optional) CPU architecture (e.g. x86-64, armv7): win 64

**Issue Description**
After enabling the plugin and restarting the engine. Steam Audio asks to be rebuilt, however rebuilding VS doesn't do anything.

**Comment by TreyOblad** [comment]
Did you find a fix for this?

**Comment by zsomborbencsik** [comment]
Yeah! You need to create an empty cpp file in Unreal. Then generate VS file from the project file and then build with VS.
