### ISSUE TITLE
Occlusion only ever occurs from camera, not from where my AudioListener is.

### ISSUE THREAD

**Issue by RebeccaBieleskiWeta** [ValveSoftware/steam-audio#288]
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.4.1
- (If applicable) Unity version: 2022.3.7f1
- Operating System and version: Windows 11

**Issue Description**
This might just be a problem from how I've set it up, but I'm using SteamAudio to drive our occlusion. When the audiolistener is on the camera, my ambience source is correctly occluded via some SteamAudio Geometry. However, when the audiolistener is on our character, the ambience source is never occluded.

**Steps To Reproduce**
1. Attach AudioListener to Main Camera, notice that it correctly occludes when I put SteamAudio Geometry between the camera and the audio source.
2. Attach AudioListener to the character, noice that it never occludes the audio source, including when I put SteamAudioGeometry between the character and the source.

**Comment by achandak** [comment]
Thanks. If you are able to put together a standalone repro, I can take a look.

**Comment by RebeccaBieleskiWeta** [comment]
Sure thing! I think this likely be something with how I've set it up in my project, some setting I've not understood. I'll make a new repo and project, replicate it and then link that project here.

**Comment by RebeccaBieleskiWeta** [comment]
Alright, so I build a basic Unity project, implemented SteamAudio, and occlusion was working perfectly there. Attached to the character, only occluded when raytrace from source to listener is blocked.
Within our own project, I've only been able to get the occlusion to work in 2 of two objects I have within my test scene, and only via sticking the source directly into the asset's wall. 
I'm looking at a way to extract the details from our project without breaking NDA.

**Comment by RebeccaBieleskiWeta** [comment]
Hi @achandak, I found the problem.
Within our game, the Player was being instantiated after the Steam Audio Manager was being created, meaning that line 46 in UnityAudioEngineState.cs would blindly search our scene with "var audioListener = GameObject.FindObjectOfType<AudioListener>();", find the deactivated audiolistener on the camera, and attach to that one.

In order to get it to work with out (although we will need to do some changes to ensure it is grabbing the correct audiolistener on our character), we run NotifyAudioListenerChanged() in SteamAudioManager once our Player has been instantiated.

**Comment by achandak** [comment]
Ah! Well done. We will add some notes in our documentation, as this might be reasonably common use case.
