### ISSUE TITLE
Exception when using a attenuation "Curve driven". Steam Audio 4.5.0

### ISSUE THREAD

**Issue by DenisSulyagin** [ValveSoftware/steam-audio#297]
ArgumentException: GCHandle value belongs to a different domain
System.Runtime.InteropServices.GCHandle.op_Explicit (System.IntPtr value) (at <787acc3c9a4c471ba7d971300105af24>:0)
System.Runtime.InteropServices.GCHandle.FromIntPtr (System.IntPtr value) (at <787acc3c9a4c471ba7d971300105af24>:0)
SteamAudio.SteamAudioSource.EvaluateDistanceCurve (System.Single distance, System.IntPtr userData) (at Assets/Shared/External/SteamAudio/Scripts/Runtime/SteamAudioSource.cs:489)
(wrapper native-to-managed) SteamAudio.SteamAudioSource.EvaluateDistanceCurve(single,intptr)

InvalidCastException: Specified cast is not valid.
SteamAudio.SteamAudioSource.EvaluateDistanceCurve (System.Single distance, System.IntPtr userData) (at Assets/Shared/External/SteamAudio/Scripts/Runtime/SteamAudioSource.cs:489)
(wrapper native-to-managed) SteamAudio.SteamAudioSource.EvaluateDistanceCurve(single,intptr)

**Comment by lakulish** [comment]
This issue should now be fixed in [v4.5.1](https://github.com/ValveSoftware/steam-audio/releases/tag/v4.5.1).
