### ISSUE TITLE
Dynamic objects does not work as expected

### ISSUE THREAD

**Issue by jordihuertas** [ValveSoftware/steam-audio#298]
**System Information**
- Steam Audio version: 4.4.1
- Unity version: 2022.3.12f1
- Operating System and version: W11 10.0.22631
- CPU architecture: x64

**Issue Description**
I have 2 rooms, 1 with a steam audio source (more audio sources playing the same audio so far away, playing the audio at the same time), and between them a dynamic object door.

All the walls and the door have occlusion 100%. So no sound should tresspass.

Then my tests are opening and closing the door from the room without audio.
It works great as the player keeps moving. But if I stop moving the player just before the door closes, I keep listening the audio as a reflection.

Example moving the dynamic object transform: https://www.youtube.com/watch?v=CZUDK2PGfXQ
Example moving the dynamic object rigidbody: https://www.youtube.com/watch?v=IPP6YmnLHtc

As you can see in the video, the audio keeps playing until the listener transform moves. 
 
EDIT
     * If I duplicate the audio source and disable the original it works, but only for the first time. So dynamic objects are only 
working with 1 audio source.

--

Also tried to reproduce it with 3 rooms and 2 audio sources (middle room is empty). The only thing I get so far is that the dynamic objects only works if the audio source is a new one.

I mean: If I duplicate the RoomA audio source (and disable the original copy) the dynamic object will oclude the sound and the RoomB will not.
Then I duplicate the RoomB audio source (and disable the original copy) and the dynamic object will oclude the sound and the roomA will not.

--

Also tested with primitive objects as walls and as dynamic objects.

All is being tested with realtime reflections.

Images attached:

Dynamics objects config (doors):
![image](https://github.com/ValveSoftware/steam-audio/assets/28887168/e3b90b3c-fe18-4be3-b896-439dd7d4e08a)

Audio sources:
![image](https://github.com/ValveSoftware/steam-audio/assets/28887168/5f9a1f3f-031c-4369-8e27-0f218519c181)

Steam Audio settings:
![image](https://github.com/ValveSoftware/steam-audio/assets/28887168/58c2425b-f8c5-458b-b2ab-7ec232950b99)

**Comment by achandak** [comment]
@jordihuertas - I cannot repro the issue on a setup similar to yours. Are you in a position to share a standalone issue? Might be faster to resolve the issue that way. Here is some additional insight:

See SteamAudioDynamicObject.cs (Lines 61-67). We rely on transform.hasChanged to make sure Steam Audio internal geometry structure is updated and that simulation is indeed updated. Is there a special way you might be handling transform for the door?

`            // Only update the dynamic object if it has actually move this frame
            if (transform.hasChanged)
            {
                mInstancedMesh.UpdateTransform(SteamAudioManager.CurrentScene, transform);
                SteamAudioManager.ScheduleCommitScene();
                transform.hasChanged = false;
            }
`

**Comment by jordihuertas** [comment]
@achandak I do not know what is a standalone issue, could you please explain to me?

There is no any special way, just a transform position. The second video I attached is just pushing a rigidbody with a hinge.

**Comment by jordihuertas** [comment]
@achandak I think I am a little closer to the problem. Maybe you can reproduce it this way.

2 audio sources playing the same clip from a script.
The dynamic object only excludes the last created one.

**Comment by achandak** [comment]
Sorry, I meant a standalone project or a small reproable unity project. We tried all obvious things we thought could go wrong.

I will try spawning additional sources.

**Comment by jordihuertas** [comment]
Yes, I will try to reproduce in a new project. I will feedback you tomorrow.

**Comment by jordihuertas** [comment]
@achandak here it is. https://drive.google.com/drive/folders/1BOPLlH_I8TjPL_-n-BS3vCa83EH6sjbb?usp=drive_link

Readme (also inside the assets folder)
STEPS:
- Import Steam Audio. 
- Created demo scenario (cubes).
- Configure SteamAudio settings like my project. 
- Created AudioSource_A and configured it like my project. 
- Duplicated AudioSource_A and renamed to AudioSource_B.
- Created Steam Audio Material like my project. 
- Added Steam Audio Geometry and Steam Audio Static Mesh to Scenario GameObject.
- Added Steam Audio Geometry and Steam Audio Dynamic Object to both DynamicObject_X GameObjects.
- Export Dynamic Objects and Export Active Scene.

Now for me, B door is occluding and A is not. 

There is a script attached to each dynamic object (orange ones) with a button to start/restart the moving process (open close doors).
On finish closing doorA, you can move the camera a little to stop playing the sound.

**Comment by jordihuertas** [comment]
Remember to configure the project settings audio to use Steam Audio.
With the imported project, Dynamic Objects will not occlude the audio when "close".

You can clone an audio source and disable the original copy to check that the new audio source will be occluded.
If you do the same with the second one, the first one will stop working as expected (the door will not occlude the audio).

**Comment by jordihuertas** [comment]
Here is a demo video https://www.youtube.com/watch?v=TZgbQ0Pz5so&ab_channel=PepeGrillo

**Comment by achandak** [comment]
@jordihuertas - Thanks for providing a repro. We indeed found a bug where only one source was being updated when dynamic geometry was present. The fix is inside phonon.dll so we should have this fixed in the next release.

**Comment by jordihuertas** [comment]
I'm glad to hear that you finally found it!

**Comment by lakulish** [comment]
This issue should now be fixed in [v4.5.1](https://github.com/ValveSoftware/steam-audio/releases/tag/v4.5.1).

**Comment by jordihuertas** [comment]
Sorry for the late response, I had some problems when updating because some unity crashes related to git.

Retested. It works!

**Comment by kisak-valve** [comment]
Thanks for retesting. Closing.
