### ISSUE TITLE
Error importing (updating) SteamAudio package due to permissions.

### ISSUE THREAD

**Issue by jordihuertas** [ValveSoftware/steam-audio#299]
**System Information**

- Steam Audio version: 4.4.1
- Unity version: 2022.3.12f1
- Operating System and version: W11 10.0.22631
- CPU architecture: x64

**Issue Description**

Trying to import 5.0.0 while 4.1.1 is already installed. 

`Copying Temp/Export Package/*/asset to Assets/Plugins/SteamAudio/Binaries/Windows/x86_64/audioplugin_phonon.dll: Access is denied.`

What is the correct way to update steam audio?

- Importing the package (but perhaps I am missing permissions) I get the error above.
- Deleting the old version and importing the new one deconfigures the project (having to reconfigure all the settings)
- Maybe unzip the package in windows explorer and manually overwrite the files with Unity closed?

I did not find an update guide in the docs.

**Comment by lakulish** [comment]
Unity loads `audioplugin_phonon.dll` as soon as the editor is launched, so importing a new version of Steam Audio from the editor will result in the "Access is denied" error that you encountered.

The best way to do an in-place upgrade of the plugin is to close Unity, then either:

* delete `Assets/Plugins/SteamAudio`, or
* delete `Assets/Plugins/SteamAudio/Binaries`, or
* delete `Assets/Plugins/SteamAudio/Binaries/Windows/x86_64/audioplugin_phonon.dll`

and then open Unity and import the new version of the plugin.

If deleting the entire `SteamAudio` folder causes issues with having to reconfigure various settings, you can try deleting the `Binaries` folder.

**Comment by jordihuertas** [comment]
Solved. Thank you!

(You should add this info to the docs)
