### ISSUE TITLE
steamaudio_api_2.0-beta.1.chm has blank pages

### ISSUE THREAD

**Issue by leif81** [ValveSoftware/steam-audio#3]
I downloaded the chm from the releases page, opened it up, i see the Contents on the left, but clicking on any of the pages seems to load nothing but a blank white page.

**Comment by TBBle** [comment]
The CHM viewer won't show pages from Internet-downloaded files. To fix it, right-click on the CHM file, hit properties, and click 'Unblock'. See https://blogs.msdn.microsoft.com/robcaron/2005/06/23/viewing-downloaded-chm-files/ for example.

**Comment by leif81** [comment]
Oh wow, I had never heard of unblocking a file before.

Thank you, that fixes it. 👍
