### ISSUE TITLE
FMOD: Steam Audio Spatializer plugin is stereo only and silent on Linux

### ISSUE THREAD

**Issue by Schroedingers-Cat** [ValveSoftware/steam-audio#311]
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.5.2
- (If applicable) FMOD Studio version: 2.2.20
- Operating System and version: macOS, Manjaro
- (Optional) CPU architecture ARM, x64

**Issue Description**
I'd expect the Steam Audio Spatializer to output sound when having incoming sound. Furthermore, I'd expect it to follow the track's output channel layout since it supports multichannel audio in Unity. However, the spatializer plugin stays silent on Linux and its output configuration seems fixed to stereo (Linux, macOS). Usually, you can change the channel layout on these meters in FMOD by right-clicking but that option isn't available for the Steam Audio spatializer plugin.

**Steps To Reproduce**
Example FMOD project is [here](https://owncloud.gwdg.de/index.php/s/dLkBXExoPEbritQ). Skip to step 4 if you use the downloaded project.  

1. Create an FMOD project with a sound on the timeline
2. Copy all content within "steamaudio_fmod/lib" to your FMOD project's Plugin directory as well as `phonon_fmod.plugin.js`
3. Reopen the FMOD project and add the Steam Audio spatializer plugin into the sounds chain, disable any distance-based effects (see screenshot)
4. Play a sound, nothing will come out of the spatializer (Linux). Also note how the spatializer's output is stereo while the track's output is 5.1 (Linux, macOS).
5. You can try this with various 3D event settings (right side "Overview", 3D Preview) but it doesn't change anything over here

![grafik](https://github.com/ValveSoftware/steam-audio/assets/6382400/cf0bf0ff-94e1-4e8d-bd11-a7ebc70fc065)

**Comment by raynax** [comment]
Related discussion on FMOD forum: https://qa.fmod.com/t/steam-audio-seems-to-be-stereo-only-in-fmod/21314
