### ISSUE TITLE
STEAMAUDIO_VERSION uses uint32_t instead of IPLuint32

### ISSUE THREAD

**Issue by Redhacker1** [ValveSoftware/steam-audio#320]
**System Information**
Please provide the following information about your system:
- Steam Audio version:
v4.5.2 (although this affects all versions of SteamAudio to my knowledge)
- (If applicable) Unity version:
N/A
- (If applicable) Unreal Engine version:
N/A
- (If applicable) FMOD Studio version:
N/A
- Operating System and version:
Windows 11, although this affects all OS versions and CPU architectures.

**Issue Description**
`STEAMAUDIO_VERSION` should be using `IPLuint32` instead of `uint32_t` (example:)
https://gist.github.com/Redhacker1/b3f9a8daa62dbbb2e8f1e51ff3d352ad
 
A similar issue was fixed a week ago (https://github.com/ValveSoftware/steam-audio/commit/bab44824f5f3ca887ea8d660688fb5299965e0cf), because of that, I don't expect it to be unreasonable, making the change locally the project seems to build and the tests from what I can tell all pass just the same and `#include <stdint.h>` is not necessary.

**Comment by Redhacker1** [comment]
Something I removed because my reasoning for why it was there must not have been correct, although should be something to note: I am not sure `#include <stddef.h>` in phonon.h is necessary either, at least on my end (note I am not using intel oneapi so if it is needed there)

I am however using windows and MSVC and that does have a habit of including more "things" by default that GCC later complains do not exist.

**Comment by wolframw** [comment]
@Redhacker1 `stddef.h` is needed because it contains the definition of `size_t`. If you include any headers before `phonon.h` on your end, there's a good chance that `stddef.h` is already transitively included by some other header further up.

**Comment by Redhacker1** [comment]
That's more than likely what's going on. 

As I said I wasn't really going to push that. I've had incidents where things like that happen.

My bigger thing is that It should be using SteamAudio types for the version rather than uint32_t
