### ISSUE TITLE
[FMOD] No sound in FMOD Studio or game when enabling occulusion with "simulation-defined" option

### ISSUE THREAD

**Issue by tenyuhuang** [ValveSoftware/steam-audio#328]
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.5.2
- Unreal Engine version: 5.3.2
- FMOD Studio version: 2.02.17
- Operating System and version: Windows 10 19044
- CPU architecture: x86-64

**Issue Description**
Setting up any audio event with Steam Audio Spatializer and occlusion enabled in "simulation-defined" mode will result in total silence, whether in FMOD Studio or in-game.

To begin with, this is already a hassle when editing the audio event itself - it doesn't matter if there is an actual simulation set-up on the game engine side, even if this is intended (i.e. no sound if no simulation data) it makes no sense at all.

Under this situation, if any editing on events are to be actually done, one have to manually disable occlusion or the whole spatializer and re-enable it afterwards - it's okay during testing or going with a few events, but in our past projects there are literally a few hundred Ks of events to process through. Despite an option for batch operation, it is known to be inconsistent and as a result potentially troublesome for a larger project.

Then I decided to move on and see if I could make it work with an actual simulation anyway. So I followed current documentations, set up Unreal Engine with Steam Audio and Steam Audio FMOD Support, made a small test map, tagged the geometry with Steam Audio Geometry component and corresponding materials, generated static mesh and probes...to no avail. The audio event is still completely silent with simulation-defined occlusion. Air Absorption doesn't seem to work at all either.

As of now I have a few educated guesses: (a) the intended default behaviour of occlusion module is definitely less favorable than desired; (b) the occlusion module for fmod is probably "broken"; (c) there is something missing or I definitely failed to follow in the docs.

Any guidance or insights into the issue would be greatly appreciated!

**Steps To Reproduce**
1. Set up Steam Audio with FMOD and Unreal Engine with current official docs;
2. Create a new audio event in FMOD and replace the default spatializer with Steam Audio Spatializer;
3. Enable Occlusion with "Simulation-defined" option;
4. Create a test map in Unreal, tag the geometry with Steam Audio Geometry component, generate Steam Audio Static Mesh and probes;
5. Drop forementioned audio event into the map.

The audio event is supposed to play with sound after either step 3 or 5, but the end result is total silence; disabling Occlusion or set it to "User-Defined" will result in a normal playback instead.

**Comment by lakulish** [comment]
@tenyuhuang Can you confirm whether you have correctly configured FMOD Studio and Steam Audio to work with each other within Unreal Engine? To check, in your Unreal project:

* Click Edit > Plugins, and ensure that **FMOD Studio**, **Steam Audio**, and **Steam Audio FMOD Studio Support** are all enabled.
* Click Edit > Project Settings, click FMOD Studio in the left panel. On the right, expand Advanced, click the + next to Plugin Files, and add `phonon_fmod` in the text box that appears.
* Click Edit > Project Settings, click Steam Audio in the left panel. On the right, set Audio Engine to FMOD Studio.

Note that the fact that simulation-defined occlusion doesn't appear to work as expected in the FMOD Studio standalone editor is separate issue (which we can reproduce).

Thanks!

**Comment by tenyuhuang** [comment]
> @tenyuhuang Can you confirm whether you have correctly configured FMOD Studio and Steam Audio to work with each other within Unreal Engine? To check, in your Unreal project:
> 
> * Click Edit > Plugins, and ensure that **FMOD Studio**, **Steam Audio**, and **Steam Audio FMOD Studio Support** are all enabled.
> * Click Edit > Project Settings, click FMOD Studio in the left panel. On the right, expand Advanced, click the + next to Plugin Files, and add `phonon_fmod` in the text box that appears.
> * Click Edit > Project Settings, click Steam Audio in the left panel. On the right, set Audio Engine to FMOD Studio.
> 
> Note that the fact that simulation-defined occlusion doesn't appear to work as expected in the FMOD Studio standalone editor is separate issue (which we can reproduce).
> 
> Thanks!

Yes, I can confirm I have already done all the following steps above.

Even with that, it is almost completely unusable with silence in its default state, with or without setting up the environment in game engine side.

**Comment by tenyuhuang** [comment]
@lakulish Hi, thanks for checking stuffs on your side! I checked with the team earlier and it seems like we have some non-standard implementations in the engine, which may or may not have something to do with the issue. So until we figure something out and isolate the problem, maybe it's better I close the issue for the time being. My apologies!

**Comment by camelCaser69** [comment]
@tenyuhuang were you succesful solving your issue? I have the same one, yet no non-standart implementation

**Comment by AudireSound** [comment]
@camelCaser69 @tenyuhuang @lakulish I have the similar kind of problem, cannot get the occlusion work correctly. Tried within our game project and also created a new project for this with no result. 

I have followed the guides but after turning on the "Enable Occlusion" in the FMODEvent and "Simulate Occlusion" in the SteamAudioSource, I can hear the sound but it doesn't occluse with any geometry.

I'm using UE 5.4.2, FMOD 2.02.25 and Steam Audio 4.5.3.

Any help with this?

**Comment by lakulish** [comment]
@SoundOfSyndrome We are unable to reproduce the issue. Can you double-check to see if you have correctly exported geometry, and that in the Steam Audio project settings, the Audio Engine is set to FMOD Studio? If those are already set up correctly, can you share more details about how your project is set up, or share a minimal project that reproduces the issue? Thanks!

@broken-bytes Can you provide more details (preferably code excerpts) for how you are running occlusion simulation and sending occlusion parameters to the Steam Audio FMOD Studio plugin? Thanks!

**Comment by broken-bytes** [comment]
> [@SoundOfSyndrome](https://github.com/SoundOfSyndrome) We are unable to reproduce the issue. Can you double-check to see if you have correctly exported geometry, and that in the Steam Audio project settings, the Audio Engine is set to FMOD Studio? If those are already set up correctly, can you share more details about how your project is set up, or share a minimal project that reproduces the issue? Thanks!
> 
> [@broken-bytes](https://github.com/broken-bytes) Can you provide more details (preferably code excerpts) for how you are running occlusion simulation and sending occlusion parameters to the Steam Audio FMOD Studio plugin? Thanks!

The issue is that the documentation is horribly outdated for FMOD C API. I managed to get it working with reading through the actual code and doing guesswork by now, but my Z axis is inverted and spatialisation is still a bit weird. 

I noticed that a few things in the FMOD C API documentation are actually marked deprecated in sourcecode or flat up wrong.
In the current state the documentation is barely usable.

And, without any example project, I can only guess what to do and if I am doing it right.
I created an issue here regarding my issues and have linked the URL to the file of my game engine that does the steam audio stuff.
Feel free to check out the other issue here: https://github.com/ValveSoftware/steam-audio/issues/450
