### ISSUE TITLE
[C API] phonon.h uses types from stdint.h but this header is not included

### ISSUE THREAD

**Issue by ethindp** [ValveSoftware/steam-audio#334]
**System Information**
Please provide the following information about your system:
- Steam Audio version: 4.5.2
- (If applicable) Unity version: N/A
- (If applicable) Unreal Engine version: N/A
- (If applicable) FMOD Studio version: N/A
- Operating System and version: Windows 10 22H2 (AMD64) build 19045.4170
- (Optional) CPU architecture (e.g. x86-64, armv7): x86-64

**Issue Description**
The `IPLHRTFSettings` struct uses `uint8_t`, but the header does not include `stdint.h`, which leads to compilation errors. The only workaround is to pollute the global namespace by first including `stdint.h` and then `phonon.h`, in that order.

**Steps To Reproduce**

1. Just include `phonon.h` like you would any other header, without including `stdint.h`. A C/C++ compiler with permissive mode turned off will reject the code because `uint8_t` is undefined in `phonon.h`. (This scenario is common in C++ where one usually includes `<cstdint>`, not `stdint.h`.)

**Crash Dump**
N/A

**Comment by kisak-valve** [comment]
Hello @ethindp, this should have already been addressed by #315.

**Comment by ethindp** [comment]
@kisak-valve Ah, I didn't know about that. No new release has been published fixing this so that's why I opened this issue.

**Comment by Xottab-DUTY** [comment]
https://github.com/ValveSoftware/steam-audio/releases/tag/v4.5.3 was published.
This issue can be closed :)
