### ISSUE TITLE
Crash on exit when using too high real time settings

### ISSUE THREAD

**Issue by Luux** [ValveSoftware/steam-audio#34]
When turning the real time settings too high, the game crashes on exit - when playing in the editor it takes the whole unity editor with it.
While playing there is no problem (it's even stable and fluid), but as soon I try to exit, it crashes every time. The exact point where it crashes seems to be different from scene to scene and from pc to pc (e.g. after it crashed when using my notebook it worked on my PC with the same settings).

One example:

This settings work like a charm both when playing and on exit...

![image](https://user-images.githubusercontent.com/15156652/27591521-406103ec-5b52-11e7-8540-c8d5d0c9cef1.png)

...while this one works like a charm when playing, but it crashes on exit every time (together with the whole unity editor!)

![image](https://user-images.githubusercontent.com/15156652/27591602-722a5c8e-5b52-11e7-935b-a18af0f422a0.png)

I had this problem several times, the only workaround seems to be lowering the settings. But that's no solution, since my PC should be powerful enough to use a bit higher settings, since it's perfectly fluid while playing.

My environment:
Windows 10 Pro 64-bit (10.0, Build 15063) (15063.rs2_release.170317-1834)
Intel(R) Xeon(R) CPU E3-1231 v3 @ 3.40GHz (8 CPUs), ~3.4GHz
8192MB RAM

**Comment by AntonioModer** [comment]
i have same issue

**Comment by CalvinSchulze** [comment]
Same with my rig. 

Windows 10 Pro 64-bit
Intel Xeon E3-1231 v3 @ 3.40GHz
16GB RAM

**Comment by lakulish** [comment]
@Luux We are able to reproduce this issue. Interestingly, slightly _higher_ settings seem to work fine, so something about the specific values you're using seems to be triggering the crash. We're working on a fix. Thanks!

**Comment by achandak** [comment]
@Luux @CalvinSchulze @AntonioModer - we have resolved this issue in Steam Audio 2.0-beta.7 release. More details are [here](http://steamcommunity.com/games/596420/announcements/detail/1443820118333481341)
