### ISSUE TITLE
Steam mobile : Failed to connect to server [Android], latest steam version

### ISSUE THREAD

**Issue by Nu-Illasera** [ValveSoftware/steam-audio#345]
As the title says, i wish i could add more info but i can't.

> Tap "steam chat" app on mobile.
> Insert correct username
> Insert correct password

>> Sign in button tap

Error : "Failed to connect to steam".

This issue doesn't belong here and i don't care, i am spamming it anywhere i can since i can't get a hold of any steam tech support nor issues to open.

Please forward it to whoever it is that is responsible.

**Comment by kisak-valve** [comment]
Hello @Nu-Illasera, please use [Steam Support](https://help.steampowered.com) for issues with the Steam for Android app.

Closing as out of scope for this issue tracker.
