### ISSUE TITLE
Reminder for pre-export

### ISSUE THREAD

**Issue by Luux** [ValveSoftware/steam-audio#35]
There should be a reminder for pre-exporting the scene or automatic pre-export (i don't know how long it will take when pre-exporting larger scenes, so maybe at least an option for that?)

We often forget the pre-export and then either we wonder why changes don't have an effect or the unity editor crashes instead. 

Is it possible to add some kind of notification when the pre-export should be done?

**Comment by CalvinSchulze** [comment]
This is sooo important! This is consuming so much time...
