### ISSUE TITLE
Huge Lags when Setting Ambisonics Order to 3 or 4

### ISSUE THREAD

**Issue by CalvinSchulze** [ValveSoftware/steam-audio#36]
Whenever I do this, the game lags for 0,5s to 1s. I thought it could be a my pc, but every part in it is running low. Nowhere near maximum performance, the CPU Usage stays at 37%. This appears in build projects as well.

I'm using an Intel Xeon e3 1231 v3 @3,40GHz up to 3,9GHz

**Comment by freemancw** [comment]
Compute scales with ambisonics order as (n+1)^2. For 3rd order, that is 16 channels, and 4th order gives 25 channels. That is a very large number of channels to process. Since this is a recurring thing we see, we will look into providing a warning for users when they choose higher order ambisonics.

**Comment by achandak** [comment]
@CalvinSchulze - we have added a warning when a user sets the Ambisonics Order to high values. We will continue to improve performance in future releases.
