### ISSUE TITLE
iplApplyAmbisonicsBinauralEffect is quiet and muffled compared to iplApplyBinauralEffect

### ISSUE THREAD

**Issue by grrrwaaa** [ValveSoftware/steam-audio#39]
The output of iplApplyAmbisonicsBinauralEffect is quiet and muffled compared to the same signal going through iplApplyBinauralEffect. 

It's really odd, but when I look at the spectra, it's almost as if the iplApplyAmbisonicsBinauralEffect spectrum has about 4x less amplitude, and is about 10% squished, like a slight pitch down.

**Comment by achandak** [comment]
@grrrwaaa - Check out the latest 2.0-beta.9 version. We have made quality improvements to iplApplyAmbisonicsBinauralEffect in this release.

**Comment by grrrwaaa** [comment]
I'm looking at beta.10 now. It's definitely different to before -- no longer quiet & muffled, actually the opposite. What I'm seeing now is that iplApplyAmbisonicsBinauralEffect is having almost no effect on the input sound, whereas iplApplyBinauralEffect has a much more drastic effect.

I'm comparing the output spectra of a raw noise signal going to iplApplyBinauralEffect with each cardinal direction, and the same noise signal encoded in B-format going to iplApplyAmbisonicsBinauralEffect with each cardinal direction. In all cases the iplApplyBinauralEffect otuput has a clearly shaped spectrum, whereas the iplApplyAmbisonicsBinauralEffect spectrum is almost flat, and significantly louder.

But perhaps this is because my encoding & decoding is just 1st order ambisonics. I will look into whether 3rd order encoding/decoding looks better.

**Comment by grrrwaaa** [comment]
I tried 3rd order -- but it is so subtle that I'm not even sure there's any panning happening at all.  #56

**Comment by lakulish** [comment]
Closing this issue since it is old and we are unable to repro with the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
