### ISSUE TITLE
Custom HRTFs in the unity plugin

### ISSUE THREAD

**Issue by gilmoregrills** [ValveSoftware/steam-audio#40]
Hi, apologies in advance for opening an issue *essentially* to ask a question, I'm limited in terms of places to turn for guidance on this one! 

I know this feature isn't technically supported, but I've been trying to this plugin to work with my own custom HRTFs in Unity. I think I sorta understand how it's supposed to work, from a combination of the guide posted on the page for the app on Steam and trial and error, but I've hit something of a dead end. 

I have three functions (assigned to the _____callback variables in the HrtfParams): 
`public void onLoadHrtf(int numSamples, int numSpectrumSamples, Phonon.FFTHelper fft, System.IntPtr data)`
`public void onUnloadHrtf()`
`public void onLookupHrtf(System.IntPtr direction, System.IntPtr leftHrtf, System.IntPtr rightHrtf)`

- onLoadHrtf fetches the HRTF set I'm using, processes it as needed, and stores it in the IntPtr named data (there don't seem to be any issues with this function currently)
- onUnloadHrtf currently does nothing because of the thing I'm stuck on, but I understand it should get rid of the HRTF set I've loaded
- onLookupHrtf  should read the Vector3 stored at direction, then identify the correct left/right HRTFs in my dataset, and copy them into leftHrtf and rightHrtf spots in memory 

However, the problem is that I can't find any way to access my HRTF set once I've loaded it using onLoadHrtf! I've checked, as far as I can tell, every class in the Phonon namespace going entirely off Visual Studio prompts that pop up when I start typing "phonon." 

I don't know if I'm misunderstanding the intended way of implementing this, or if it's actually impossible to get custom HRTFs working with this plugin at the moment, literally any tips/pointers would be so appreciated - I'm utterly stumped!

**Comment by gilmoregrills** [comment]
There is this block of code in my current version of BinauralRenderer.cs: 
`HRTFParams hrtfParams = new HRTFParams
            {
                type = HRTFDatabaseType.Custom,
                hrtfData = IntPtr.Zero,
                numHrirSamples = 101,
                loadCallback = OnLoadHrtf,
                unloadCallback = onUnloadHrtf,
                lookupCallback = onLookupHrtf
            };`

I don't know if I should be changing what gets assigned to hrtfData. I was assuming that it was the same pointer that gets passed to the loadCallback, but I'm unsure and can't find a way to access it outside of the loadCallback.

**Comment by lanion** [comment]
In the api I'm seeing you can have IPL_HRTFDATABASETYPE_DEFAULT or IPL_HRTFDATABASETYPE_CUSTOM, but the expected data type for hrtf is IPLComplex? I'm not sure what that means.

There is a lot of information in the steam community post about custom hrtf implementation about setting up memory allocation and that you must set IPL_HRTFINTERPOLATION_BILINEAR rather than nearest neighbor.

**Comment by gilmoregrills** [comment]
Hi! 

So I'm not sure how much those notes apply to the Unity plugin, which is a layer of C# scripts on top of some inscrutable DLLs that I guess are the phonon stuff. For example the database type is set by to "Default" originally, and the suggested values in visual studio are either Default or Custom. The hrtfData variable under it also isn't available in the C API so I've ended up diverging from the guidelines in the guide on the steam community. 

As far as I can tell the interpolation options are adjustable from within the Unity editor too, and I've got them set to Bilinear there 👍

I know it's trying to use my callbacks, and I can see exactly where it fails, it all seems to hinge on setting and fetching stuff from these IntPtr pointers correctly, and at the moment I see no way to get the hrtf dataset data from the IntPtr I'm copying it to in my loadCallback. So I'm sure I must not be doing this the intended way.

**Comment by lanion** [comment]
Oh, I see! Well, my instinct is the same going into the BinauralRenderer.cs ! 
I'm assuming you also posting in the steam community as Benjamin G? You have a bit more detail there about how you are importing your HRTF database.  
What format are your HRTF files in?

**Comment by gilmoregrills** [comment]
Hey yeah that's also me :P 

So the full dataset (all the directions for one person) actually gets imported as JSON which gets parsed in the loadCallback function and converted into a 4D double array. It adds a bit to load times at the moment, but speed isn't really an issue for this thing and it seems so far like the loadCallback only gets called once when the app is started.

**Comment by lanion** [comment]
I'm finding that the data type must be an HRIR .wav file (time domain impulse response) that it then applies an FFT to and becomes a complex data type for the application. 
This seems kind of odd as there is a lot more overhead requiring an import of HRIR rather than letting you use frequency domain HRTFs directly, but that is what it looks like. 

So, it can't be in a double array. It has to be a float32 array. The API is pretty explicit that all data it uses has to be in that type. Unity can do conversions, but phonon.dll can only take in float32. 

I'm not sure if that is relevant as I'd think you would get an understandable error message if that was causing an issue.

**Comment by gilmoregrills** [comment]
Omg, that's super useful to know thank you! It didn't seem to specify, so since I'm doing all my processing in the frequency domain I thought I could just not call the provided fft function and do it however I fancied 😛

It should be easy to send the data over in hrir/wav form, I'll try and tweak my program and give that a try! Thanks! 

I'll also take another look at the errors I'm getting. Part of the problem with them is that Unity often just crashes before I can even see console  output so when I'm doing things wrong I dont always know what is actually causing the thing to break! 

Thanks again ❤️

**Comment by gilmoregrills** [comment]
Omg, that's super useful to know thank you! It didn't seem to specify, so since I'm doing all my processing in the frequency domain I thought I could just not call the provided fft function and do it however I fancied 😛

It should be easy to send the data over in hrir/wav form, I'll try and tweak my program and give that a try! Thanks! 

I'll also take another look at the errors I'm getting. Part of the problem with them is that Unity often just crashes before I can even see console  output so when I'm doing things wrong I dont always know what is actually causing the thing to break! 

Thanks again ❤️

**Comment by gilmoregrills** [comment]
That close was an accident, my bad!

**Comment by lanion** [comment]
Keep the thread updated!

**Comment by lanion** [comment]
It might be helpful to also add this bit about the hrtfLoadCallback requirements (from the API)


**signalSize** | Number of elements in the time-domain (HRIR) data arrays that must be transformed. This will be greater than the actual size of the HRIRs passed to iplCreateBinauralRenderer. Any array passed to fftHelper must contain the HRIR data at the start, and the rest of the elements must be initialized to zero. For example, if signalSize is 1024, and the HRIRs are 200 samples long, the arrays passed to the signal parameter of fftHelper must be 1024 samples long, with the first 200 samples containing the HRIR data, and the remaining 824 samples containing zeroes.
-- | --
**spectrumSize** | Number of elements in the frequency-domain (HRTF) data arrays that will contain the results of the transformation. You will typically allocate arrays of this size for each HRIR; they must not be freed until IPLHrtfUnloadCallback is called.
fftHelper | Pointer to a function that you can call to calculate the Fourier transforms of the HRIRs.
fftHelperData | Internal data required for calculating Fourier transforms. Pass this to fftHelper.

**Comment by achandak** [comment]
We released support for custom HRTFs through SOFA files in [Beta 16 release](https://steamcommunity.com/app/596420/discussions/0/1735468693693167270/).

Also, see the [blog post](https://steamcommunity.com/games/596420/announcements/detail/1681425498140397761) on the topic.
