### ISSUE TITLE
Support for additive scenes in Unity

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#42]
http://steamcommunity.com/app/596420/discussions/0/2132869574276577327/

**Comment by Janooba** [comment]
Any update on this? It's been over a year since I last checked in and almost three since this topic was initially posted. I'd love to use Steam Audio for my projects but I literally can't with the way it's currently set up.

**Comment by achandak** [comment]
@Janooba - We have implemented this feature for the next release already. Should be out in Beta.19

We have updated the feature based on our understanding of how additive scenes are used in Unity. Either of the following would help us test your use scenario before next release:

- Description of how you are using additive scenes in your project. How are they added and removed? Is it mostly for the purposes of breaking down components or they are streamed in and out at runtime? Any other details will be helpful. 

or

- Share a standalone project which mimics you requirement as close as possible. We can try to make sure the next update work on setup similar to yours.

Thanks.

**Comment by Janooba** [comment]
Beautiful! Can't wait.

I've created a small project that mimics my setup as closely as I could. It's too large to upload here directly.

Here's a google drive link. Let me know if you have any issues downloading or setting up the project.

I used Unity 2019.2.21

https://drive.google.com/file/d/182qwe4gOpxUJCzfPW4lV7Eag7VTWcZm0/view?usp=sharing

**Comment by lakulish** [comment]
This issue should be fixed in the latest release, available here: https://github.com/ValveSoftware/steam-audio/releases/tag/v4.0.0.
