### ISSUE TITLE
No scene export option UE 4.17?

### ISSUE THREAD

**Issue by MM-N** [ValveSoftware/steam-audio#44]
I've been having issues with exporting a scene in 4.16 and 4.17. At the moment in 4.17 my only option in the drop down menu next to build is 'Steam Audio: Bake Indirect Sound..'

I've followed the instructions for setting up the scene - creating the shortcut with -audiomixer and then tagging objects in the scene but just wondering what has happened to the export scene option/how to now get it to work?

**Comment by freemancw** [comment]
Hey MM-N,

Check out the new manual for 4.17, here https://github.com/ValveSoftware/steam-audio/releases/download/v2.0-beta.6/steamaudio_manual_unreal_2.0-beta.6.pdf.

Basically, add a PhononScene actor to your level; you will find an "export scene" button in the actor's detail panel.

**Comment by MM-N** [comment]
Ah right, thanks!
