### ISSUE TITLE
Support for source sound direction

### ISSUE THREAD

**Issue by poduncan** [ValveSoftware/steam-audio#45]
I would like to use the C API to accurately simulate how indirect sound behaves in a direction-dependent way in an arbitrary room. For example, this setup:

```
----------
|   s    |
|-----   |
|   r    |
----------
```

...with a single sound receiver and a single sound source. Direct sound is blocked by a wall, so most sound should reach the receiver from the right side, due to the reflection along the right-side wall. I also want to simulate which direction the source sound is facing, so the sound that the receiver gets would be more muffled if the source is facing left, compared to facing right.

I tried to use a mesh around the source to simulate "direction", but I did not get expected results. I tried completely surrounding the source with a mesh that absorbs all sound, but it didn't get blocked. In fact, I was sometimes able to get sound coming in louder from the left of the receiver!

Can this library support this scenario?

**Comment by achandak** [comment]
@poduncan - The kind of scenario you are mentioning should be possible with Steam Audio. Currently, directional sources are not supported in Steam Audio but the way you are modeling it seems interesting.

Will the following reproduce the issue you are facing - 

Place sound source inside a box and listen to it outside of the box, ideally all the sound should be blocked but you are hearing sound outside the box? Can you confirm if your mesh is water tight?

Thanks.

**Comment by poduncan** [comment]
Hi @achandak,

I tried your suggestion and now I'm having a different issue. All sound got blocked as expected. I then added a larger box (to represent a room) around both the source and the listener to see how sound would propagate through the smaller box. I would expect that if I gave the right-side of the smaller box a "transparent" material like { 0, 0, 0, 0.5, 1, 1, 1 }, then the indirect sound should come out the right side, bounce off the right wall of the room and into the listener. This didn't happen though. I was only able to get direct sound to travel through the smaller box.

Am I missing something?

Thanks

**Comment by achandak** [comment]
@poduncan - The transmission support is currently only for direct sound.  Can you not just remove the right-side of the smaller box?

**Comment by poduncan** [comment]
I can't remove the right-side of the box in the general case, because I want to be able to control the percentage of sound passing through that side. This library doesn't appear to meet my needs right now, but I'll keep an eye on it. Thank you for your help!

**Comment by achandak** [comment]
@poduncan - thanks for feedback. I am going to keep this issue open until we have support for directional sources. Also, [added an issue](https://github.com/ValveSoftware/steam-audio/issues/47) to support transmission for indirect sound.

**Comment by achandak** [comment]
We added a feature for source directivity in Steam Audio 2.0-beta.14. See [release notes](https://github.com/ValveSoftware/steam-audio/releases/tag/v2.0-beta.14) for more information.
