### ISSUE TITLE
Sources playing in sync cause occlusion issues

### ISSUE THREAD

**Issue by freemancw** [ValveSoftware/steam-audio#48]
https://steamcommunity.com/app/596420/discussions/0/1519260397782876814/

**Comment by AKAdriano** [comment]
I'm having the exact same issue. Was this ever resolved?

**Comment by 1runeberg** [comment]
Hi - Terribly sorry for the delay.

We've recently updated the plugin including the latest SDK in UE4.23. Let us know if you're still encountering issues on this.


Cheers,
Rune

**Comment by kisak-valve** [comment]
Closing pending feedback.
