### ISSUE TITLE
Unity: Support for changing scene material in real-time

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#49]
Allow changing material associated with the scene geometry in during the gameplay or in realtime.

**Comment by mojoyup1528** [comment]
I have been trying to figure this out for weeks not just for materials, but the entire object to affect the audio output at the receiver/listener. I read all about dynamic objects and situated my scene according to the information provided about the plugin, yet my dynamic components do not affect, or update, SteamAudio reatime affects, either direct or indirect.
