### ISSUE TITLE
Google Chrome detects valvesoftware.github.io as a phishing site.

### ISSUE THREAD

**Issue by thesbros** [ValveSoftware/steam-audio#5]
`valvesoftware.github.io` is marked as a deceptive site in Google Safe Browsing.

![Screenshot](http://i.imgur.com/Pgi241o.png)

**Comment by seppestas** [comment]
I have the same result. MacOS 10.12.3, Google Chrome 56.0.2924.87, Proximus ISP in center of Brussels, Belgium.

**Comment by movedoa** [comment]
Same in Firefox 51.0.1 Windows 10

**Comment by minecrawler** [comment]
Same in Chrome 56.0.2924.87 on Windows, but not on Firefox 45.7.0.

**Comment by achandak** [comment]
We reported a detection problem to Google. Are you guys still seeing this issue?

**Comment by BlackBank** [comment]
I use Chrome 56.0.2924.87 and it's working over here right, without any warnings or errors.

**Comment by thesbros** [comment]
@achandak Looks like it's propagated now. I'm not getting the issue anymore.
