### ISSUE TITLE
Ambisonics decoding bug

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#50]
http://steamcommunity.com/app/596420/discussions/0/1483232961047242437/

**Comment by mecowhy** [comment]
@achandak Are you able to provide some workaround to mentioned bug? it looks like simple channel reordering could help, and we don't have to wait for the fix till beta.11 which will be released, I assume, not sooner that in a month.

**Comment by achandak** [comment]
@mecowhy - yup, channel reordering should do the job.

**Comment by mecowhy** [comment]
@achandak could you provide the channel mappings we have to perform in order to get proper results with this bug ?

**Comment by achandak** [comment]
@mecowhy - For first order, the following remapping of channels should work.

0 1 2 3 to 0 -3 2 1

For higher orders you need to apply rotation to Ambisonics input. Let us know if the above workaround will be sufficient for the time being.

**Comment by achandak** [comment]
Resolved in 2.0-beta.11 release.

Workout should not required anymore.
