### ISSUE TITLE
Issue with Object Pooling and Steam Audio

### ISSUE THREAD

**Issue by spaggi2** [ValveSoftware/steam-audio#55]
Hi,

I've setup Steam Audio on a Audio Source Gameobject. I'm pooling those Audiosource objects to optimize my game's performance. 

Pooling means that all Audio Objects get instantiated on game start and are then being enabled and disabled when required. Audio Samples are being exchanged depending on what should be played.

However when having a Phonon Source assigned to my Audio Object, no Sound is played and I'm getting the following error:

NullReferenceException: Object reference not set to an instance of an object
Phonon.PhononSource+<EndOfFrameUpdate>c__Iterator0.MoveNext () (at Assets/Phonon/Simulator/PhononSource.cs:127)
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress) (at C:/buildslave/unity/build/Runtime/Export/Coroutines.cs:17)
UnityEngine.MonoBehaviour:StartCoroutine(IEnumerator)
Phonon.PhononSource:OnEnable() (at Assets/Phonon/Simulator/PhononSource.cs:40)
UnityEngine.GameObject:SetActive(Boolean)

This looks to me like SA does not support having objects setup on game start and enabling them later.
Without having looked too deep into this: Is Object Pooling something that is supported by SA?

Thank you!

**Comment by achandak** [comment]
@spaggi2 - Can you share self contained sample project that we can take a look at? You should be able to pool audio objects with Steam Audio Source components on them.

**Comment by achandak** [comment]
@spaggi2 - Tested the issue you reported on a simple project where we pooled GameObjects with AudioSource component attached in Unity. With a keypress, AudioSource was enabled, assigned an AudioClip and then played. All of this worked fine on our end with the latest 2.0-beta.14 release and Unity 2018.1.1.  Let us know if you are still facing the issue. Thanks.
