### ISSUE TITLE
Crash when enabling spatializing in audio source in Unity 2017.3

### ISSUE THREAD

**Issue by DuckBoss** [ValveSoftware/steam-audio#58]
The engine crashes after integrating steam audio into Unity and enabling spatial audio in an Audio Source component.

EDIT: Reproducible on new/empty projects every time.

**Comment by achandak** [comment]
@DuckBoss - we are running into [this](https://forum.unity.com/threads/cant-open-projects-in-2017-3-starting-server-timing-out.509512/) issue with Unity 2017.3 right now. We will look into this issue as Unity fixes the problem.

**Comment by achandak** [comment]
@DuckBoss - We are not able to reproduce the issue on our end. We can successfully import the Steam Audio and have Audio Source use spatial audio effect in Unity 2017.3.0 p1 on a new project.

**Comment by DuckBoss** [comment]
Hmm, that's odd. I was using 2017.3f instead of the patch releases. I checked on a couple new projects and it seems to be a hit or miss. Sometimes it works perfectly, sometimes it doesn't now. Thanks for looking into it.
