### ISSUE TITLE
[Unity] Popping when playing audio source for the first time

### ISSUE THREAD

**Issue by Luux** [ValveSoftware/steam-audio#61]
When playing an audio source for the first time, there's a weird, loud and really annoying sound artifact. 

It seems similar to https://github.com/ValveSoftware/steam-audio/issues/22, but it doesn't only occur on specific DSP buffer settings.

Instead it only occurs when playing an audio source for the first time. I tried several workarounds like "initializing" the sounds by playing them with low Listener volume, but since the effect even occurs when spatializing is turned off for a specific audio source, the only 'solution' that works is to deactivate the Steam Audio Spatializer completely...

**Comment by achandak** [comment]
@Luux - can you provide a snapshot of Steam Audio Source component on Unity side? Also, can you share a small self-contained Unity project where we can reproduce the issue on our end?

**Comment by achandak** [comment]
@Luux - let us know if this is still an issue. Get the latest version of Steam Audio Unity integration [here](https://valvesoftware.github.io/steam-audio/downloads.html).

**Comment by lakulish** [comment]
@Luux I'm closing this issue out; let us know if you continue to face this issue in the latest release of Steam Audio, and we'll reopen it.
