### ISSUE TITLE
FMOD Studio + Custom game engine: some Spatializer parameters are not set 

### ISSUE THREAD

**Issue by TrianglesPCT** [ValveSoftware/steam-audio#63]
(You can close this, I figured out what was wrong, needed to call initSpatializerParamDescs)
 
I've been working on getting Steam Audio working in a custom game engine that uses FMOD Studio. 

 The docs don't appear to cover this situation--
 
I took the src code for the FMOD Studio plugin and used spatializer_effect.cpp as the basis for the DSP plugin. 

When the SpatializeEffectState is created, as far as I can tell FMOD is supposed to call these functions to set the effect up correctly.

    setSpatializerFloat
    setSpatializerInt
    setSpatializerBool
    setSpatializerData

  What I'm seeing is that the Bool version is called with the correct data, but the float one appears to be always passed 0. This causes directLevel to be 0.f, and thus no sound is produced.  If I override directLevel so that it is 1.0, I do hear sound.

**setSpatializerData** is never called, so the soucePosition is never set, I can only hear the sound if physics-based attenuation and air absorption are disabled.  

 When I create the event I'm calling EventInstance::set3DAttributes to set the position etc, it works correctly if I do not use the Steam Audio Spatializer.

 Anyone have any idea what I'm missing to get setSpatializerFloat/setSpatializerData working correctly?

Thanks

**Comment by kisak-valve** [comment]
Closing as this issue appears to have been resolved.
