### ISSUE TITLE
FMOD Studio vs Unity?

### ISSUE THREAD

**Issue by tslug** [ValveSoftware/steam-audio#65]
What are the differences in using FMOD Studio vs Unity to render sound?  I couldn't find a discussion on this.

**Comment by lakulish** [comment]
As far as being able to use the feature set of Steam Audio is concerned, FMOD Studio and the built-in Unity audio engine are more or less similar. Of course, FMOD Studio and Unity have their own trade-offs independent of Steam Audio, which are beyond our scope here :) I would recommend reviewing the documentation for both to get a sense of feature and workflow differences between the two.
