### ISSUE TITLE
which acoustic configurations are used for material presets?

### ISSUE THREAD

**Issue by thbc** [ValveSoftware/steam-audio#66]
Is there a way to get to know the used settings for presets like "wood, ceramic, etc."?

**Comment by jampekka** [comment]
These seem to be documented in the `phonon.h` file of the C-API:

    /** The acoustic properties of a surface. You can specify the acoustic material properties of each triangle,
     *  although typically many triangles will share a common material. The acoustic material properties are specified
     *  for three frequency bands with center frequencies of 400 Hz, 2.5 KHz, and 15 KHz.
     *
     *  Below are the acoustic material properties for a few standard materials.
     *
     *  ```cpp
     *  {"generic",{0.10f,0.20f,0.30f,0.05f,0.100f,0.050f,0.030f}}
     *  {"brick",{0.03f,0.04f,0.07f,0.05f,0.015f,0.015f,0.015f}}
     *  {"concrete",{0.05f,0.07f,0.08f,0.05f,0.015f,0.002f,0.001f}}
     *  {"ceramic",{0.01f,0.02f,0.02f,0.05f,0.060f,0.044f,0.011f}}
     *  {"gravel",{0.60f,0.70f,0.80f,0.05f,0.031f,0.012f,0.008f}},
     *  {"carpet",{0.24f,0.69f,0.73f,0.05f,0.020f,0.005f,0.003f}}
     *  {"glass",{0.06f,0.03f,0.02f,0.05f,0.060f,0.044f,0.011f}}
     *  {"plaster",{0.12f,0.06f,0.04f,0.05f,0.056f,0.056f,0.004f}}
     *  {"wood",{0.11f,0.07f,0.06f,0.05f,0.070f,0.014f,0.005f}}
     *  {"metal",{0.20f,0.07f,0.06f,0.05f,0.200f,0.025f,0.010f}}
     *  {"rock",{0.13f,0.20f,0.24f,0.05f,0.015f,0.002f,0.001f}}
     *  ```
     */

**Comment by achandak** [comment]
@jampekka has answered the question very well.

Also, in Unity, if you select a material (say brick) and then change to a custom material, the settings of the custom material will be copied from that of brick.
