### ISSUE TITLE
Support for Moving Geometry in Unity Plugin

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#7]
Currently, geometry needs to be pre-exported during design time and cannot change during the game play. Add support for moving geometry during gameplay in the Unity Plugin for Steam Audio.

There are some limitations when accessing game geometry at runtime in Unity. To avoid them, we require that scene be pre-exported during design time.

**Comment by AndersMalmgren** [comment]
Moving geometry is one thing, but portals are even more fundamental. I'm thinking about doors. Look at my clip here at 28 seconds

https://www.youtube.com/watch?v=ibStAYcyGt8

One way could be to derive from the geometry component and add a float ranging from 0-1 telling how much the portal is open

**Comment by 13Flo** [comment]
A moving geometry feature would be awesome. It's a huge issue in VR when using doors.

**Comment by tslug** [comment]
Hi there.  I'm new to Steam Audio.  It sounds super cool, but my initial integration efforts and forum reading lead me to believe I might be in for some hurt.  I have only dynamic, additive scenes w/ moving geometry, and I'm only interested how an HRTF will respond to its absorption / reflection properties and don't need transmission.  Is Steam Audio the wrong library for me?

**Comment by 13Flo** [comment]
@tslug if you have a lot of moving parts forget about it. I'm not sure how SteamAudio deals with additive scenes either but I doubt it's supported at the moment.

**Comment by mojoyup1528** [comment]
> Currently, geometry needs to be pre-exported during design time and cannot change during the game play. Add support for moving geometry during gameplay in the Unity Plugin for Steam Audio.
> 
> There are some limitations when accessing game geometry at runtime in Unity. To avoid them, we require that scene be pre-exported during design time.

Is this focused on dynamic objects? I am wondering because I am trying to set up dynamic objects (walls) for my scene for runtime and it is not updating steamaudio even when I am using embree as requested. Can I discuss my issue in this topic or should I create a new one? THanks guys. AMAZING plugin so far!

**Comment by achandak** [comment]
Support for dynamic geometry is now part of Steam Audio 2.0-beta.17. We are closing this issue, but if you encounter issues with dynamic geometry support, feel free to open a new issue.
