### ISSUE TITLE
[Unity] Steam Audio + FMOD ceases to work when loading new scene

### ISSUE THREAD

**Issue by FelixHansson** [ValveSoftware/steam-audio#70]
When using FMOD's audio engine with Steam Audio in Unity it will initially work in the Editor but when loading a scene it will stop working, even when I reload the current scene. When using Unity's audio engine with Steam Audio it will keep on working leading me to the conclusion that something is wrong with the FMOD implementation. Furthermore, if I Live-Connect with FMOD Studio and Bypass the Steam Audio Spatializer the sound will play normally.

I looked into the Steam Audio code for FMOD integration a little but couldn't really find anything conclusive. The two ideas I have are that either something is wrong Steam Audio code for FMOD, or that FMOD somehow drops the plugin or connection when a scene closes down and the Steam Audio Manager is destroyed and then when a new scene with a Steam Audio Manager is loaded FMOD simply ignores it.

I have a test project to demonstrate the problem and can provide it if anyone is interested, with all the plugins etc its a bit big to upload here directly.

/Felix

**Comment by FelixHansson** [comment]
I tried what you did with DontDestroyOnLoad and it seems to work when changing scenes, I made a copy of the first but removed on of the boxes in the middle and the sound did change accordingly. Likewise I'm not sure if this causes any problems. It is somewhat weird since you need a Steam Audio Manager Settings in every scene to build the scene data and you can have scene specific settings, so something feels off.

**Comment by lakulish** [comment]
We're trying to repro this issue. Would it be possible for you to share the test scene you had for this, if you still have it? Thanks.

**Comment by FelixHansson** [comment]
This should be the one: https://github.com/FelixHansson/SteamAudioFMODTest

Do note that it's pretty old stuff.

**Comment by lakulish** [comment]
Thanks, we were able to repro the issue. The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix. Feel free to try it out, and if the issue persists, reopen it here.
