### ISSUE TITLE
Only Baking One Source with Multiple Selected, Others Get Errors

### ISSUE THREAD

**Issue by wderstine** [ValveSoftware/steam-audio#72]
When trying to bake multiple static audio sources, it allows one Steam Audio Source to begin baking, while the others get the error **_"Unique identifier not specified for GameObject XXXXXXX"_**

They all have their unique identifiers. I've tried _re_-Pre-Exporting the scene, and re-generating the probes. But when I try to bake them either from the Steam Audio Manager's consolidated baking, or by selecting all of the objects and hitting bake on their SAS component, I still get the errors. When I only select one it will begin baking. But when I select all of the others after it's done they get the same error. I've also tried giving each source its own probe box and still got errors. 

I can bake each one individually one at a time and all of the Bake Settings on each Source becomes uninteractable which seems related to why it kicks out the errors? But I doubt that the intended method is manually baking each source this way and rather automatically baking each source.

Perhaps there is something that I have been doing incorrectly?

All of my Steam Audio Sources look like this:
![image](https://user-images.githubusercontent.com/26384603/39832904-295122d8-538e-11e8-98f7-945c1de7967e.png)

I'm on Unity 2017.3.1f1

**Comment by achandak** [comment]
@wderstine - This is unusual. I did a quick testing on our end and was not able to replicate the issue. Can you tell me the version of Steam Audio you are using as well? Is there a short project you can share that I can quickly use to reproduce the issue or steps I should take to recreate a simple scene that replicate the issue you have.

Also, I am assuming that when you say all of your Steam Audio Source have the settings, the unique identifier is different for each source, please confirm.

**Comment by kisak-valve** [comment]
You can throw files into an archive and drag and drop the archive into the comment box of this issue report.

**Comment by achandak** [comment]
@wderstine - I repeated the steps you mentioned again and could not reproduce the issue on the latest release 2.0-beta.14. I am using Unity 2018.1.1. 

As far as baking multiple static Steam Audio Source is concerned, you would always want to use Steam Audio Manager (Window > Steam Audio). Multi-selecting and clicking bake will only bake one of the static sources.
