### ISSUE TITLE
Feature request regarding UE4

### ISSUE THREAD

**Issue by ghost** [ValveSoftware/steam-audio#74]
I am dying to make a game using Steam Audio, and want to use Unreal Engine 4.19 as the base for all of my changes, I do not wish to upgrade any further, the feature set is perfect for me.

Unfortunately, it tends to take Epic a while to upgrade to each new Steam Audio version and I'm worried that since I want to use 4.19 that I won't get to take advantage of all the sweet new updates.

I was hoping that the latest release with Embree support would be made available for UE4? I can integrate it myself if need be, but it would be nice if there was a way to let people use it for "outdated" UE4 versions as well.

If this isn't feasible then I understand.

**Comment by dyanikoglu** [comment]
https://github.com/EpicGames/UnrealEngine/pull/5940

**Comment by achandak** [comment]
We have updated the Steam Audio plugin for Unreal 4.24. This updates Steam Audio to 2.0-beta.17. The pull request is at: https://github.com/EpicGames/UnrealEngine/pull/6203. You can grab these changes and merge them back into the Unreal 4.19 branch to use the latest Steam Audio features.

For more information, see https://steamcommunity.com/games/596420/announcements/detail/1589135317217982691.
