### ISSUE TITLE
[Unity Plugin] Query all OpenCL capable devices for Radeon Rays

### ISSUE THREAD

**Issue by achandak** [ValveSoftware/steam-audio#77]
[Steam Audio Forum](https://steamcommunity.com/app/596420/discussions/0/1735468693698975121) related to this issue.

Currently, Steam Audio Unity plugin fails if the first OpenCL device does not support Radeon Rays. Go through all the devices before complete failure in case another OpenCL device does support Radeon Rays.

**Comment by AntonioModer** [comment]
This crash archive with Unity-project:
https://www.dropbox.com/s/xy6ckahi8778zny/Unity%20crash%20Steam%20Audio.zip?dl=0

![unity report](https://user-images.githubusercontent.com/3039538/47692053-8fc80e00-dc05-11e8-8e6a-1fbfe325a278.PNG)

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), includes a fix for this bug.
