### ISSUE TITLE
[Unity Plugin] Unity always crash during baking with RadeonRays-RayTracer

### ISSUE THREAD

**Issue by AntonioModer** [ValveSoftware/steam-audio#78]
Steamaudio_unity_2.0-beta.16
Steamaudio_radeonrays_2.0-beta.16

I turn off integrated Intel GPU in video-driver by WindowsDeviceManager, because with Intel GPU i have SteamAudio error: https://steamcommunity.com/app/596420/discussions/0/1735468693698975121/

Unity-crash archive, Unity-project: https://www.dropbox.com/s/xy6ckahi8778zny/Unity%20crash%20Steam%20Audio.zip?dl=0

**Comment by LtdJorge** [comment]
The same happens to me with beta 17, downloaded, not compiled. My graphics card has OpenCL 1.2 (GTX 750Ti) which is listed as the minimum here: https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#amd-radeon-rays

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), includes a fix for this bug.

Feel free to try this out, and if the crash persists, reopen this issue.
