### ISSUE TITLE
Ambisonics output

### ISSUE THREAD

**Issue by ArcadyNoskov** [ValveSoftware/steam-audio#81]
SteamAudio can use 3rd order - that's great! But it remains solely within Unity. The output of Unity, via binaural or 7.1 - it is ordinary thing for practical using in games. While SteamAudio has already become something more serious - sound modeling tool -  and will grow in its capabilities further. I think a lot of sound researching people will support asking this: it is very needed a 16-channel 3rd order output from Unity, and if possible, without waiting for Unity to expand its sound pipeline to 16 channels. Something like a "output hook", recorder/render to a interleaved audio file or, even better - realtime runtime render to existing in OS virtual audioports like jack, loopback or something similar to monitor the ambisonic field parameters using visualizers like Flare http://www.blueripplesound.com/story/new-o3a-flare or IEM Energy Visualizator https://plugins.iem.at/#tab-EnergyVisualizer

**Comment by achandak** [comment]
Bypassing Unity's audio engine is outside the scope of Steam Audio at the moment. If and when Unity adds native Ambisonic output to its audio engine, we can revisit this issue. 

In the meantime, feel free to modify the [native plugin code](https://github.com/ValveSoftware/steam-audio/tree/master/unity/src/native) to record or render the Ambisonic outputs as needed.
