### ISSUE TITLE
[Unity plugin] Spatialization not working

### ISSUE THREAD

**Issue by JorgeBravo** [ValveSoftware/steam-audio#86]
Hi,

I was testing the latest unity plugin available on the website in Unity 2018.3.9f1 (64-bit), and after following the steps stated in the [guide](https://valvesoftware.github.io/steam-audio/doc/phonon_unity.html#unity-integration), the spatialization is not working at all (the sound is maintained as a normal stereo).
1. The spatializer has been selected as indicated:
![image](https://user-images.githubusercontent.com/43028407/54933154-64c7b900-4f1c-11e9-826b-f8d75338d855.png)
2. I have added Window > Steam Audio and the manager is available and setup as follows:
![image](https://user-images.githubusercontent.com/43028407/54933236-8a54c280-4f1c-11e9-8569-bb721155b8cf.png)
3. An AudioSource has been added with the following config:
![image](https://user-images.githubusercontent.com/43028407/54933427-e7e90f00-4f1c-11e9-9325-7e24b84c0356.png)

According to the docs, at this point I should be able to notice the spatialization with the default HRTFs. However, when testing the scenario, the output sound has no binaural rendering.
I managed to make the plugin work with Unity 2018.3.8f1 (64-bit) last week, but when trying again now the problem is the same.
Is there any step that I'm missing?
If there is anything else that I can upload in order to catch this issue, please do not hesitate telling me.

Best regards,

Jorge

**Comment by achandak** [comment]
@JorgeBravo - You need to set Spatial Blend to 3D. This is necessary. Reverb Zone Mix in Step 3 that you highlighted is irrelevant for Steam Audio. Also, Steam Audio will use the distance attenuation curve of an Audio Source. You can make it flat if you do not want any distance attenuation to be applied. Let me know if this helps.

**Comment by JorgeBravo** [comment]
Hi @achandak ,
I'm really sorry for the stupid question then, I totally misread the labels.
This totally helped and now is working perfectly.
Again, thank you very much for the answer and sorry for taking your time.

Best regards,
Jorge
