### ISSUE TITLE
Steam Audio updates past beta 13 planned for UE4?

### ISSUE THREAD

**Issue by mastercoms** [ValveSoftware/steam-audio#88]
Hi, I was wondering if the upcoming release mentioned in this quote was still planned.

>Embree support will be enabled in the Steam® Audio Unreal Engine 4 plugin in an upcoming release.
https://steamcommunity.com/games/596420/announcements/detail/1674659226616741624

Our team would like to know how we should prioritize audio implementation in our game, and knowing if this is being worked on by Valve/Epic would help us make more informed decisions. We wouldn't want to do duplicate work with additional implementation efforts that were already in the pipeline.

**Comment by iniside** [comment]
Any info on this ? Also interested if there is ever to be going update.

**Comment by dyanikoglu** [comment]
bump

**Comment by freemancw** [comment]
https://github.com/EpicGames/UnrealEngine/pull/6203
