### ISSUE TITLE
[Unity Plugin] Disabling parent gameobject when using dynamic object crashes Unity

### ISSUE THREAD

**Issue by peroht** [ValveSoftware/steam-audio#90]
In Unity, during playback in Editor, when disabling a parent gameobject - containing gameobjects with the Steam Audio Dynamic Object component - (and also a specific gameobject) will lead to a complete crash of Unity. I get no error logs. 

Removing the Steam Audio Dynamic Object component and disabling the parent gameobject does not crash Unity. I added a screenshot to show my setup. When pressing play and disabling the "Wall with opening" gameobject Unity will crash.

![Unity Steam Audio 17  Bug with disable](https://user-images.githubusercontent.com/14336296/57250087-e562f480-7046-11e9-99b0-2022d5f66a7d.png)

Tested with

Steam Audio Beta 17
Unity 2018.3.11f1

**Comment by lakulish** [comment]
We are able to reproduce this issue and have a potential fix. This will be included in the next release of Steam Audio.

**Comment by peroht** [comment]
Great.
