### ISSUE TITLE
Unity/Ambisonics: Crackles if speaker layout is 5.1 or 7.1

### ISSUE THREAD

**Issue by Schroedingers-Cat** [ValveSoftware/steam-audio#93]
The current unity version of steam audio doesn't seem to support decoding ambisonics to surround speaker layouts like 5.1 or 7.1. Whenever I set these speaker modes, Steam Audio either outputs a 3 channel audio stream in the audio mixer or - with the Steam Audio Ambisonics Source Script attached - outputs a 5.0 or 7.0 channel stream with a lot of crackling added.

What is the current status of decoding ambisonics to other channel layouts than stereo?

**Comment by Schroedingers-Cat** [comment]
I completely forgot to mention, that I'm talking about the Unity Steam Audio package used in the Unity engine 2019.1.6f1. I have the same behaviour with the 2018 version cycle.  

Can you give a status report of what the ambisonics decoder of the untiy version currently supports and if decoding ambisonics to multichannel arrays like 7.1 will be supported in the future?

**Comment by Schroedingers-Cat** [comment]
Using Steam Audio's Ambisonics Decoder in Unity 2018 and 2019 produces loud crackles with the speaker mode set to 5.1 or 7.1. @freemancw @lakulish @achandak 

This is in contrast to the docs of the Steam Audio API clearly stating that decoding ambisonics to "standard speaker layouts" is supported:
https://valvesoftware.github.io/steam-audio/doc/capi/group__audiobuffer.html#gaf6effca02547c6553609d1db3981217c
https://valvesoftware.github.io/steam-audio/doc/capi/group__ambisonicspanning.html#details

The crackling ambisonics decoder in the 5.1/7.1 configuration is even more surprising given the fact that Steam Audio itself supports 5.1 and 7.1 just fine (setting "Direct Binaural" to false on a spatialized audio source is enough). This even includes geometric reverb.  

I had a look at the ambisonics decoder code. The initialize method of the ambisonics decoder seems to fail without a binaural renderer:
https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/ambisonic_decoder_effect.cpp#L138-L139
I'm not familiar with the API but once the "Enable Binaural" bool is disabled in the "SteamAudioAmbisonicsSource" component in the Unity editor, aren't you expected to have something else than a "binaural renderer"? Something like a "panning renderer" or "speaker renderer" or "ambisonics renderer"?

Is this just a confusing variable name and that binaural renderer is also used for other speaker formats? Or will the ambisonics decoder really fail initialization if binaural rendering is disabled?

Is decoding ambisonics to 5.1/7.1 supposed to work with Steam Audio in Unity and this is just a bug or a misconfiguration?

**Comment by Schroedingers-Cat** [comment]
I had a more in-depth look at the steam audio API and its unity integration code today. It looks like SteamAudio's ambisonics decoder *should* support surround speaker layouts like 7.1. 

The problem seems to be the `processAmbisonicDecoder` callback always being called with the parameter `outChannels` set to `4`, no matter the speaker configuration. While the speaker configuration value is being transferred to the callback via `UnityAudioEffectState` (which is correctly being used by Steam Audio to detect the speaker layout), the initializing memset-call uses the `outChannels` value to create the final buffer handed over to Unity making it impossible to use a speaker layout with more than 4 speakers:
https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/ambisonic_decoder_effect.cpp#L250

So one problem seems to be on Unity's side by just expecting to receive a buffer with samples for just four channels. This is in contradiction to Unity's [manual](https://docs.unity3d.com/Manual/AmbisonicAudio.html):
```The plugin interface includes the information to support binaural stereo, quad , 5.1, and 7.1 output, but the level of support is really determined by the plugin.```
Can any of the devs @freemancw @lakulish @achandak confirm this and help contacting the Unity devs about this?

The other problem seems to be the Assert ensuring that the input and output-channels are the same:
https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/ambisonic_decoder_effect.cpp#L247
That condition does not make any sense for an ambisonics decoder as it should be possible to convert ambisonics audio to any possible speaker configuration on a sphere.
Can the devs shine any light on why that is necessary?

**Comment by Schroedingers-Cat** [comment]
The crackles are caused by the inner for-loop's index variable `j`ranging to `ambisonicOutChannels` and thus running out of the (intended) channel bounds set by the outer for-loop increment (`outChannels`):
https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/ambisonic_decoder_effect.cpp#L338-L347

As this is just about normalization, I tried a quick test with this code disabled. A better approach would be to iterate over `outChannels` in the inner loop. 
While the crackles are gone, the spatial image of the ambisonics file is totally wrong for all speaker channels except for the front channels.

**Comment by Schroedingers-Cat** [comment]
The crackles are caused by the code I linked to above and also by this one:
https://github.com/ValveSoftware/steam-audio/blob/53d19fd938e8e2e5508eb95324019f8acfa6b69b/unity/src/native/ambisonic_decoder_effect.cpp#L232-L239

I uploaded the source code containing the fix and a compiled dll for Winx64 for anybody else experiencing this:
[SteamAudioAmbisonicsCracklesFix.zip](https://github.com/ValveSoftware/steam-audio/files/3910880/SteamAudioAmbisonicsCracklesFix.zip)

Until the Steam Audio devs release the fix to this, the contents of the zip file can be used to workaround the crackling issue.

However, there's still the problem of completely wrong positioning of the audio content. This is a another bug in Unity's Ambisonics decoder SDK, which is being tracked here: https://issuetracker.unity3d.com/issues/surround-sound-gets-misplaced-when-speaker-layout-has-a-higher-channel-count-than-4

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue. Feel free to reopen if the issue persists on your end.
