### ISSUE TITLE
Why is the audio output from applyBinauralEffect is garbled?

### ISSUE THREAD

**Issue by sadernalwis** [ValveSoftware/steam-audio#95]
int main2(){
        auto inputaudio = load_input_audio("/home/Music/inputaudio.raw");

        IPLhandle context{nullptr};
        iplCreateContext(nullptr, nullptr, nullptr, &context);

        auto const samplingrate = 44100;
        auto const framesize    = 1024;

        IPLRenderingSettings settings{ samplingrate, framesize };
        IPLhandle renderer{ nullptr };
        IPLHrtfParams hrtfParams{ IPL_HRTFDATABASETYPE_DEFAULT, nullptr, 0};
        iplCreateBinauralRenderer(context, settings, hrtfParams, &renderer);
    
        IPLAudioFormat mono;
        mono.channelLayoutType  = IPL_CHANNELLAYOUTTYPE_SPEAKERS;
        mono.channelLayout      = IPL_CHANNELLAYOUT_MONO;
        mono.channelOrder       = IPL_CHANNELORDER_INTERLEAVED;
    
        IPLAudioFormat stereo;
        stereo.channelLayoutType  = IPL_CHANNELLAYOUTTYPE_SPEAKERS;
        stereo.channelLayout      = IPL_CHANNELLAYOUT_STEREO;
        stereo.channelOrder       = IPL_CHANNELORDER_INTERLEAVED;
    
        IPLhandle effect{ nullptr };
        iplCreateBinauralEffect(renderer, mono, stereo, &effect);
        std::vector<float> outputaudioframe(2 * framesize);
        std::vector<float> outputaudio;
    
        IPLAudioBuffer inbuffer{ mono, framesize, inputaudio.data() };
        IPLAudioBuffer outbuffer{ stereo, framesize, outputaudioframe.data() };
    
        auto numframes = static_cast<int>(inputaudio.size() / framesize);
        for (auto i = 0; i < numframes; ++i)
        {
                iplApplyBinauralEffect(effect,renderer, inbuffer, IPLVector3{ 0.0f, 0.0f, 0.0f },
    IPL_HRTFINTERPOLATION_NEAREST, outbuffer);
                std::copy(std::begin(outputaudioframe), std::end(outputaudioframe),         std::back_inserter(outputaudio));
                inbuffer.interleavedBuffer += framesize;
        }
        iplDestroyBinauralEffect(&effect);
        iplDestroyBinauralRenderer(&renderer);
        iplDestroyContext(&context);
        iplCleanup();
        save_output_audio("/home//Music/outputaudio.raw", outputaudio);
        return 0;
   }
`

i am using the following code from tutorial, raw data exported in 32 bit mono from Audacity.
output is twice the size but no matter however i load it its garbled in 32bit stereo playback from Audacity ,24bit,16bit checked everything .. different files.. different setting everytime. is there  something i can try that might work? 
(i tried setting IPLVector3{ 1.0f, 1.0f, 1.0f } first.)

please help?

**Comment by lakulish** [comment]
We tried to repro this issue using the code you provided above, but are unable to.

What is the version of Steam Audio that you're using? What is your OS? We can't repro this issue on Steam Audio 2.0-beta.17, Windows 64-bit.

Can you also make sure that your Audacity import is set to 32-bit float, little-endian, stereo?

**Comment by lakulish** [comment]
Closing this issue since we're not able to repro it. If the issue persists with the latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), feel free to reopen.
