### ISSUE TITLE
[Unity Plugin] IL2CPP support

### ISSUE THREAD

**Issue by Agoxandr** [ValveSoftware/steam-audio#96]
Core.cs is causing the dreaded
`NotSupportedException: To marshal a manged method, please add 
an attribute named 'MonoPInvokeCallback' to the method definition`

Method _iplCreateContext_ and any other call similar to this.

Should be an easy fix.

**Comment by Agoxandr** [comment]
I don't see them stating anywhere that they only support Unity 2017. I know it used to say that.

**Comment by Agoxandr** [comment]
`        [MonoPInvokeCallback(typeof(OnLog))]
        public static void Log(string message)
        {
            Debug.Log(message);
        }
        public delegate void OnLog(string message);

        [DllImport("phonon")]
        public static extern void iplGetVersion([In, Out] ref uint major, [In, Out] ref uint minor, [In, Out] ref uint patch);

        [DllImport("phonon")]
        public static extern Error iplCreateContext(OnLog logCallback, IntPtr allocateCallback, IntPtr freeCallback, [In, Out] ref IntPtr context);`

This is a fix. I'm just to lazy to make a pull request right now.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue.
