### ISSUE TITLE
[Unity] Sound freeze problem - no exception or informaction.

### ISSUE THREAD

**Issue by Nephasia** [ValveSoftware/steam-audio#99]
Hi,
During using Your plugin in Unity (2019.2.0f1 version here - i think version does not matter), when one object with unity's AudioSource and SteamAudioSource reach the same position (x, y and z) as second object with Unity's AudioListener - all sounds get freezed, stop working.
Until one of this two objects change position (even change one of 0.00001 in position resolves the problem). 
Game still works and sounds begin to work after any position change.

I am sure that this two types of objects can't have the same position but there is no exception or even no proper information about it.

**Comment by lakulish** [comment]
The latest release, [Steam Audio 2.0-beta.18](https://github.com/ValveSoftware/steam-audio/releases/), contains a fix for this issue. Feel free to reopen if the issue persists on your end.
